// --------------------Demo Daten fiktiv !!!!!!!!!!!-----------------

//var projekteNamen = ['ADAPT', 'APOLLO', 'ComP-ASS', 'DigiPlat4Train', 'EduPLEx_API', 'ELe-com', 'ExpanderWB3', 'HUBGrade', 'IWWB-PLUS', 'KAINE', 'KAMAELEON', 'KI4CoLearnET', 'KIM', 'KIPerWeb', 'KIRA', 'KIRA_Pro', 'KIWI', 'KUPPEL', 'LIMo', 'LiSiL', 'MINDED_RUHR', 'MyEduLife', 'NetOEV', 'OnCaPflege', 'PolyEx', 'SEARCH', 'SG4BB', 'SMALO', 'StuBu', 'TRIPLEADAPT', 'VerDatAs', 'WBsmart', 'Weiterb.4.OWL', 'WISYatKI'];

//var projekteNamen = ['Projekt1', 'APOLLO', 'ComP-ASS', 'DigiPlat4Train', 'EduPLEx_API', 'ELe-com', 'ExpanderWB3', 'HUBGrade', 'IWWB-PLUS', 'KAINE', 'KAMAELEON', 'KI4CoLearnET', 'KIM', 'KIPerWeb', 'KIRA', 'KIRA_Pro', 'KIWI', 'KUPPEL', 'LIMo', 'LiSiL', 'MINDED_RUHR', 'MyEduLife', 'NetOEV', 'OnCaPflege', 'PolyEx', 'SEARCH', 'SG4BB', 'SMALO', 'StuBu', 'TRIPLEADAPT', 'VerDatAs', 'WBsmart', 'Weiterb.4.OWL', 'WISYatKI'];
var projekteNamen = ['Projekt_1', 'Projekt_2', 'Projekt_3', 'Projekt_4', 'Projekt_5', 'Projekt_6', 'Projekt_7', 'Projekt_8', 'Projekt_9', 'Projekt_10', 'Projekt_11', 'Projekt_12', 'Projekt_13', 'Projekt_14', 'Projekt_15', 'Projekt_16', 'Projekt_17', 'Projekt_18', 'Projekt_19', 'Projekt_20', 'Projekt_21', 'Projekt_22', 'Projekt_23', 'Projekt_24', 'Projekt_25', 'Projekt_26'];


var projekteAuspraegung = ['Dim k.A.', 'Dim in Ansätzen.', 'Dim adressiert.', 'Dim ausgepr.'];


/// Zustand welche Projekte gerade in Einzeplorjektanzeige an sind
var projekteEinzelStatusInLegende = Array(projekteNamen.length).fill(0);

/// daten und Beschreibung der Oberdimensionen 
var dataDimensionenStandAntrag = [
    { id: 1, value1: 26, value2: 25, value3: 49, dimension: "Interoperabilität durch offene Bildungstandards", nameKurz: "Interoperabilität", name: "Interoperabilität durch offene Bildungstandards", textLang: "Fragen der unterstützten Standards und Technologien zur Etablierung\neines gemeinsamen digitalen Weiterbildungsraumes, z. B. zu Kompe-\ntenzen und Wissen, sowie dem Austausch von Kurs-, Leistungs- oder\n Lernergebnissen und Lerninhalten." },
    { id: 2, value1: 48, value2: 27, value3: 25, dimension: "Algorithmen zur Unterstützung der Lernenden", nameKurz: "Algorithmen", name: "Algorithmen zur Unterstützung der Lernenden", textLang: "Fragen des Einsatzes und der Entwicklung von Algorithmen z.B. zur\nSprachverarbeitung (NLP, NLU, NLG), Analyse des Lernverhaltens\n(Learning Analytics) oder der Anpassungsfähigkeit von Lernangeboten\nund -empfehlungen sowie Suchfunktionen durch Nutzende." },
    { id: 3, value1: 15, value2: 23, value3: 62, dimension: "Mitgestaltung, Zugänglichkeit und Zusammenarbeit", nameKurz: "Mitgestaltung", name: "Mitgestaltung, Zugänglichkeit und Zusammenarbeit", textLang: "Spektrum der geplanten und umgesetzten Möglichkeiten der Beteiligung,\nZusammenarbeit und Mitgestaltung von Lerninhalten durch Nutzende\nsowie Lösungen zur Nutzbarkeit und zum Nutzungserlebnis." },
    { id: 4, value1: 31, value2: 29, value3: 41, dimension: "Nachnutzbarkeit durch Dritte", nameKurz: "Nachnutzbarkeit", name: "Nachnutzbarkeit durch Dritte", textLang: "Fragen der Offenheit der eingesetzten und zu entwickelnden Systeme,\nModelle und Funktionalitäten bspw. als Open Source Software oder über\ngut dokumentierte API." },
    { id: 5, value1: 22, value2: 56, value3: 23, dimension: "Informationssicherheit & Datensouveränität", nameKurz: "Informationssicherheit", name: "Informationssicherheit & Datensouveränität", textLang: "Fragen der eingesetzten oder zu entwickelnden Sicherheits- und Schutz-\nmaßnahmen im Rahmen von Plattformen und Funktionalitäten im Sinne\nder gesetzlichen Anforderungen sowie Fragen der Datenethik und Selbst-\nbestimmung bei der Ablage von personenbezogenen Informationen." },
    { id: 6, value1: 40, value2: 40, value3: 20, dimension: "Weitere technologische Aspekte", nameKurz: "Weitere", name: "Weitere technologische Aspekte", textLang: "Weitere technologische Merkmale in den Vorhaben die nicht durch die\nanderen Dimensionen abgedeckt sind." },

];
var dataDimensionenStandZeitpunktA = dataDimensionenStandAntrag; //Zeitpunkt A ist 1. auf slider

var dataDimensionenStandDezember2022 = [
    { id: "1", value1: 18, value2: 33, value3: 49, dimension: "Interoperabilität durch offene Bildungstandards", nameKurz: "Interoperabilität", name: "Interoperabilität durch offene Bildungstandards", textLang: "Fragen der unterstützten Standards und Technologien zur Etablierung\neines gemeinsamen digitalen Weiterbildungsraumes, z. B. zu Kompe-\ntenzen und Wissen, sowie dem Austausch von Kurs-, Leistungs- oder\n Lernergebnissen und Lerninhalten." },
    { id: "2", value1: 38, value2: 29, value3: 33, dimension: "Algorithmen zur Unterstützung der Lernenden", nameKurz: "Algorithmen", name: "Algorithmen zur Unterstützung der Lernenden", textLang: "Fragen des Einsatzes und der Entwicklung von Algorithmen z.B. zur\nSprachverarbeitung (NLP, NLU, NLG), Analyse des Lernverhaltens\n(Learning Analytics) oder der Anpassungsfähigkeit von Lernangeboten\nund -empfehlungen sowie Suchfunktionen durch Nutzende." },
    { id: "3", value1: 7, value2: 25, value3: 68, dimension: "Mitgestaltung, Zugänglichkeit und Zusammenarbeit", nameKurz: "Mitgestaltung", name: "Mitgestaltung, Zugänglichkeit und Zus.arbeit", textLang: "Spektrum der geplanten und umgesetzten Möglichkeiten der Beteiligung,\nZusammenarbeit und Mitgestaltung von Lerninhalten durch Nutzende\nsowie Lösungen zur Nutzbarkeit und zum Nutzungserlebnis." },
    { id: "4", value1: 27, value2: 31, value3: 42, dimension: "Nachnutzbarkeit durch Dritte", nameKurz: "Nachnutzbarkeit", name: "Nachnutzbarkeit durch Dritte", textLang: "Fragen der Offenheit der eingesetzten und zu entwickelnden Systeme,\nModelle und Funktionalitäten bspw. als Open Source Software oder über\ngut dokumentierte API." },
    { id: "5", value1: 13, value2: 60, value3: 27, dimension: "Informationssicherheit & Datensouveränität", nameKurz: "Informationssicherheit", name: "Informationssicherheit & Datensouveränität", textLang: "Fragen der eingesetzten oder zu entwickelnden Sicherheits- und Schutz-\nmaßnahmen im Rahmen von Plattformen und Funktionalitäten im Sinne\nder gesetzlichen Anforderungen sowie darüber hinaus Fragen der Daten-\nethik und Selbstbestimmung im Umgang mit und bei der Ablage von\npersonenbezogenen Informationen." },
    { id: "6", value1: 34, value2: 27, value3: 39, dimension: "Weitere technologische Aspekte", nameKurz: "Weitere", name: "Weitere technologische Aspekte", textLang: "Weitere technologische Merkmale in den Vorhaben die nicht durch die\nanderen Dimensionen abgedeckt sind." },

];
var dataDimensionenStandZeitpunktB = dataDimensionenStandDezember2022; //Zeitpunkt B ist 2. auf slider und stellt Stand Dezember 2022 dar

var dataDimensionenStandAugust2023 = [
    { id: "1", value1: 28, value2: 32, value3: 40, dimension: "Interoperabilität durch offene Bildungstandards", nameKurz: "Interoperabilität", name: "Interoperabilität durch offene Bildungstandards", textLang: "Fragen der unterstützten Standards und Technologien zur Etablierung\neines gemeinsamen digitalen Weiterbildungsraumes, z. B. zu Kompe-\ntenzen und Wissen, sowie dem Austausch von Kurs-, Leistungs- oder\n Lernergebnissen und Lerninhalten." },
    { id: "2", value1: 53, value2: 22, value3: 25, dimension: "Algorithmen zur Unterstützung der Lernenden", nameKurz: "Algorithmen", name: "Algorithmen zur Unterstützung der Lernenden", textLang: "Fragen des Einsatzes und der Entwicklung von Algorithmen z.B. zur\nSprachverarbeitung (NLP, NLU, NLG), Analyse des Lernverhaltens\n(Learning Analytics) oder der Anpassungsfähigkeit von Lernangeboten\nund -empfehlungen sowie Suchfunktionen durch Nutzende." },
    { id: "3", value1: 19, value2: 28, value3: 53, dimension: "Mitgestaltung, Zugänglichkeit und Zusammenarbeit", nameKurz: "Mitgestaltung", name: "Mitgestaltung, Zugänglichkeit und Zusammenarbeit", textLang: "Spektrum der geplanten und umgesetzten Möglichkeiten der Beteiligung,\nZusammenarbeit und Mitgestaltung von Lerninhalten durch Nutzende\nsowie Lösungen zur Nutzbarkeit und zum Nutzungserlebnis." },
    { id: "4", value1: 34, value2: 30, value3: 36, dimension: "Nachnutzbarkeit durch Dritte", nameKurz: "Nachnutzbarkeit", name: "Nachnutzbarkeit durch Dritte", textLang: "Fragen der Offenheit der eingesetzten und zu entwickelnden Systeme,\nModelle und Funktionalitäten bspw. als Open Source Software oder über\ngut dokumentierte API." },
    { id: "5", value1: 24, value2: 58, value3: 18, dimension: "Informationssicherheit & Datensouveränität", nameKurz: "Informationssicherheit", name: "Informationssicherheit & Datensouveränität", textLang: "Fragen der eingesetzten oder zu entwickelnden Sicherheits- und Schutz-\nmaßnahmen im Rahmen von Plattformen und Funktionalitäten im Sinne\nder gesetzlichen Anforderungen sowie darüber hinaus Fragen der Daten-\nethik und Selbstbestimmung im Umgang mit und bei der Ablage von\npersonenbezogenen Informationen." },
    { id: "6", value1: 43, value2: 33, value3: 24, dimension: "Weitere technologische Aspekte", nameKurz: "Weitere", name: "Weitere technologische Aspekte", textLang: "Weitere technologische Merkmale in den Vorhaben die nicht durch die\nanderen Dimensionen abgedeckt sind." },

];
var dataDimensionenStandZeitpunktC = dataDimensionenStandAugust2023; // 3. Position auf Zeit slider

var dataDimensionen = dataDimensionenStandZeitpunktA;
var dataOhneLetzteDimension = dataDimensionen.slice(0, dataDimensionen.length - 1); //Für Initiale Anzeige Kopie des Datenarray aber ohne das letzte element= Dimension Sontiges

/// Daten für Beschreibung der Unterdimesionen, Prozent und absolut Werte der UnterDim sind jetzt in datensatz Einzeldimension

var dataBeschreibungUnterDimensionen = [ /// hier nur noch Text beschreibungen für die UDims, GesamtValues absolut und Prozent kommen aus Einzeldatensatz
    { dimension: "Kompetenzstandards", nameKurz: "Kompetenzstand.", name: "Kompetenzstandards", oberdimension: "Interoperabilität", textLang: "(ESCO, EQR, Europass) Kompetenzstandards dienen der Beschreibung\nvon Fähigkeiten, Qualifikationen und Berufen. Sie können dazu genutzt\nwerden den Weiterbildungsbedarf der Lernenden standardisiert zu\nerheben, Lernziele zu definieren, Lerninhalte einer Weiterbildungsplatt-\nform zu beschreiben und bei Bildungsnachweisen das erreichte\nKompetenzlevel zu dokumentieren." },
    { dimension: "Bildungsnachweise", nameKurz: "Bildungsnachw.", name: "Bildungsnachweise", oberdimension: "Interoperabilität", textLang: "Standards zum Austausch von digitalen Bildungsnachweisen wie  Euro-\npass und EDCI. Es werden einheitliche digitale Nachweise für\nLernleistungen und Qualifikationen ausgestellt. EDCI definiert auch ein\ndazu passendes Datenmodell." },
    { dimension: "Standards Lerninhalte", nameKurz: "Lerninhalte", name: "Standards Lerninhalte", oberdimension: "Interoperabilität", textLang: "Standards zum Datenaustausch von Lerninhalten wie z.B. HP5, xAPI und\nSCORM. Es wird die Kommunikation zwischen Lernmanagementsystemen\nermöglicht, indem Lerninhalte standardisiert beschrieben werden. Damit\nkönnen auch Autorenwerkzeuge Lerninhalte erstellen die in verschiedenen\nLMS verwendet werden können. xAPI geht über SCORM hinaus indem\nzusätzlich Aktivitäten der Lernenden beschrieben und zwischen LMS\nausgetauscht werden können" },
    { dimension: "Wissensrepräsen.", nameKurz: "Wissensrepräs.", name: "Wissensrepräsen.", oberdimension: "Interoperabilität", textLang: "Bei Wissensrepräsentationen werden eine Menge von Begriffen und ihre\nBeziehung untereinander beschrieben. Damit kann „Wissen“\n(z.B. in der Pflege) maschinenlesbar abgespeichert und verarbeitet werden." },
    { dimension: "Intelligente Suche", nameKurz: "Intellig. Suche", name: "Intelligente Suche", oberdimension: "Algorithmen", textLang: "Intelligente Suchfunktionen gehen über die einfache Suche nach Wörtern\nin Text hinaus. Dies umschließt Suchalgorithmen von traditionellen,\nintelligenten Such-Algorithmen, welche die regelbasierte Verarbeitung\nvon Suchwörtern durchführen, bis hin zu solchen, welche menschliche\nSprache verstehen und die semantische Suche mit einem kontext-\nbezogenen Verständnis der Abfrage ermöglichen. Maschinelles und\nDeep Learning werden eingesetzt, um dem Kern der Suchabfrage auf\nden Grund zu gehen." },
    { dimension: "Learning Analytics", nameKurz: "L. Analytics", name: "Learning Analytics", oberdimension: "Algorithmen", textLang: "Learning Analytics verwendet Datenaggregation, Data Mining und\nweitere Algorithmen, um Trends und Bewertungsmetriken im Zeit\nverlauf zu verstehen. Je nach Entwicklungsstufe des zugrundeliegenden\nSystems bietet dieses einen Einblick in vergangene Lernerfahrungen,\nerklärt die Ursachen von Ereignissen im Lernverlauf und gibt Empfeh-\nlungen zu möglichen zukünftigen Lernereignissen." },
    { dimension: "Adaptive Lerninh.", nameKurz: "Adapt. Lerninh.", name: "Adaptive Lerninh.", oberdimension: "Algorithmen", textLang: "Adaptive Lerninhalte und –pfade passen die Art der Wissensvermittlung\nan den Wissensstand, die Lernpräferenzen und das Umfeld des Lernenden\nan, um einen für alle Lernenden vergleichbaren Lernerfolg zu erzielen." },
    { dimension: "Recommendersysteme", nameKurz: "Recomm. Systeme", name: "Recommendersyst.", oberdimension: "Algorithmen", textLang: "Lernempfehlungssysteme sind nutzerzentrierte Recommender Systeme\nfür Lernplattformen. Auf Basis vorheriger Nutzerentscheidungen werden\npassende Lerninhalte empfohlen." },
    { dimension: "Kollaboration", nameKurz: "Kollaboration", name: "Kollaboration", oberdimension: "Mitgestaltung", textLang: "Kollaboration bedeutet, gemeinsam mit anderen Lernenden zu arbeiten.\nBei der Kollaboration zwischen Lernenden sind alle Lernenden am gemein-\nsamen Prozess, bei dem gemeinsam ein Ergebnis konstruiert wird, in allen\nArbeitsschritten beteiligt und bringen sich in den Prozess ein. Das\nVorhaben sollte adäquaten digitalen Tool zur Unterstützung des gemein-\nsamen Lernens einsetzten." },
    { dimension: "Peer-Support", nameKurz: "Peer-Support", name: "Peer-Support", oberdimension: "Mitgestaltung", textLang: "Lernpatenschaften/ Peer-Support bedeutet die Unterstützung beim Lernen\ndurch einen Mentor. Bei Lernpatenschaften und Peer-Support arbeiten die\nLernenden bzw. Lehrenden zusammen und unterstützen sich, um Leistungs-\ndefizite auszugleichen. Das Vorhaben sollte adäquaten digitalen Tool zur\nUnterstützung des Lernen mit einem Mentor einsetzen." },
    { dimension: "Partizipation", nameKurz: "Partizipation", name: "Partizipation", oberdimension: "Mitgestaltung", textLang: "(Partizipative Gestaltung) Bei der partizipativen Gestaltung werden die\n (Bedürfnisse der) Stakeholder bei der Anpassung der Plattform mitein-\nbezogen. Dieses kann z.B. auch durch den Einsatz von KI geschehen.\nPlattform bietet Feedbackmöglichkeiten an. " },
    { dimension: "Accessibility", nameKurz: "Accessibility", name: "Accessibility", oberdimension: "Mitgestaltung", textLang: "(Accessability und Usability) Web-Zugänglichkeit (Accessibility) bezieht\nsich auf die inklusive Praxis, Websites für Menschen aller Fähigkeiten und\nBehinderungen nutzbar zu machen. Ein internationaler Standard wird mit\nden Content Accessibility Guidelines (WCAG) des W3C gesetzt (seit 2012\n ISO-Standard ISO/IEC 40500:2012). Die WCAG bieten\nEmpfehlungen für die barrierefreie Gestaltung von Webseiten und\nmobilen Anwendungen. Die WCAG 2.1 umfassen 13 Richtlinien, die vier\nübergeordneten Prinzipien zuzuordnen sind: Wahrnehmbarkeit, \nedienbarkeit, Verständlichkeit und Robustheit. Das Vorhaben sollte die\nGuidelines und / oder Prinzipien umsetzten." },
    { dimension: "OSS & KI Modelle", nameKurz: "OSS & KI Modelle", name: "OSS & KI Modelle", oberdimension: "Nachnutzbarkeit", textLang: "Lizenzierung der Software als Open Source & Lizenzierung der KI Modelle\nals Open Source, Verwendung von „Standard“ KI-Bibliotheken\n(etwa Keras, pytorch, TensorFlow) und Publikation des trainierten Modells\n(etwa in binärer Form). Im besten Fall wird zusätzlich auch der Code zum\nTraining des Models publiziert. " },
    { dimension: "OSS LMS & Plugin", nameKurz: "OSS LMS & Plugin", name: "OSS LMS & Plugin", oberdimension: "Nachnutzbarkeit", textLang: "(Free Open Source Software, Nutzung von Open Source Lernmanagement-\nsystemen & Erstellung von Plugins) Basis der Software-Entwicklung ist ein\nFOSS LMS. Wesentlich ist, dass Quellcode des Ursprungsprojekts\ngewartet wird, und dies auch zukünftig zu erwarten ist. Das Projekt muss\ndarüber hinaus glaubhaft machen, dass eine Nachnutzung möglich ist, etwas\ndurch Implementation als ein Plugin und Dokumentation der Integration.\nIm besten Fall wird das Plugin in einem „offiziellen“ Kanal des LMS publiziert." },
    { dimension: "API Zugriff", nameKurz: "API Zugriff", name: "API Zugriff", oberdimension: "Nachnutzbarkeit", textLang: "(Zugriff auf Plattform über gut dokumentierte API Bsp. REST API) Kriterium\nist wie weitreichend die API die Funktionalitäten des Projekts abdeckt. Ist\ndas zentrale Element (etwa das KI Modell) nicht darüber erreichbar, wäre\ndas Kriterium nicht voll erfüllt. Weitere Kriterien sind Dokumentation der\nSchnittstelle, sowie Dauerhaftigkeit der Erreichbarkeit." },
    { dimension: "OER", nameKurz: "OER", name: "OER", oberdimension: "Nachnutzbarkeit", textLang: "(Bereitstellung von Ergebnissen als Open Educational Resources) Die auf\nder Plattform verfügbaren Lerninhalte sind mit einer freien Lizenz publiziert\n(CC, GPL, oder vergleichbar) und glaubhaft dauerhaft publiziert, etwa auf\neiner Drittplattform (Github, Gitlab, OER Drittplattform)." },
    { dimension: "IT-Sicherheit", nameKurz: "IT-Sicherheit", name: "IT-Sicherheit", oberdimension: "Informationssicherheit", textLang: "Aufrechterhaltung der Schutzziele Vertraulichkeit, Integrität und\nVerfügbarkeit von Informationen.  Absicherung der Weiterbildungs-\nPlattform gegen Cyberattacken Datendiebstahl und weitere Sicherheits-\nrisiken.  Berücksichtigung einschlägiger Normen und Standards wie\nISO 27001/27002 oder BSI-Grundschutz. Beachtung der Grundsätze\nsichere Softwareentwicklung" },
    { dimension: "Datenschutz", nameKurz: "Datenschutz", name: "Datenschutz", oberdimension: "Informationssicherheit", textLang: "(Datenschutz und Privacy) Einhaltung der gesetzlichen und vertraglichen\nAnforderungen bzgl. Schutz personenbezogener Daten Beachtung der\nAnforderungen der ISO 27701 in Ergänzung der ISO 27001/27002 unter\nanderem privacy by design/by default, Anonymisierung, Pseudo¬\nnymisierung, Mandaten Trennung. Informations- und Transparenz-\npflichten. Umgang mit Betroffenenrechten, Übernahme von Corporate\nDigital Responsibility (CDR)" },
    { dimension: "Datenethik", nameKurz: "Datenethik", name: "Datenethik", oberdimension: "Informationssicherheit", textLang: "Die Digitale Ethik oder Datenethik beschäftigt sich mit den sittlichen\nNormsetzungen, die für Digitalisierung, Big Data und KI gelten sollen.\nDie Vorhaben sollten berücksichtigen, welchen Bias die Daten möglicherweise\nenthalten und auch wie ethisch verantwortungsvoll mit den gesammelten\nDaten umgegangen werden kann. Zudem müssen in den Projekten die Ethik-\nLeitlienien für vertrauenswürdige KI enthalten und die Empfehlungen der\nDatenethik-kommission der Bundesregierung beachtet werden." },
    { dimension: "Digitale Identitäten", nameKurz: "Dig. Identitäten", name: "Digitale Identitäten", oberdimension: "Informationssicherheit", textLang: "Mit Digital Credentials sollen mit Hilfe kryptographischer Software Zeug-\nnisse und Leistungsnachweise sicher dokumentiert und gemanaged werden.\nDazu gehören u.a. Authentifizierung, eID, Learning Record Store, Blockchain\nzur fälschungssicheren Ablage als Teil der Digital Credentials Infrastruktur." },

];

var dataUnterDimensionenEinzelStandAntrag = [ /// Array für Radarboard Unterdimensionen und Radarboard Einzelvorhaben zusammen, damit Daten an einer Stelle
    { id: "1", dimension: "Kompetenzstandards", value1: 32, valueProzentGesamt1: 32, value2: 28, valueProzentGesamt2: 28, value3: 40, valueProzentGesamt3: 40, valueGesamt1: 17, valueGesamt2: 6, valueGesamt3: 11, value1: 0, value2: 1, value3: 1, value4: 2, value5: 3, value6: 2, value7: 3, value8: 2, value9: 3, value10: 0, value11: 1, value12: 3, value13: 0, value14: 3, value15: 1, value16: 1, value17: 3, value18: 2, value19: 0, value20: 1, value21: 0, value22: 2, value23: 0, value24: 3, value25: 0, value26: 1, value27: 3, value28: 1, value29: 3, value30: 3, value31: 3, value32: 0, value33: 1, value34: 2 },
    { id: "2", dimension: "Bildungsnachweise", value1: 26, valueProzentGesamt1: 26, value2: 16, valueProzentGesamt2: 16, value3: 58, valueProzentGesamt3: 58, valueGesamt1: 23, valueGesamt2: 2, valueGesamt3: 9, value1: 0, value2: 0, value3: 0, value4: 3, value5: 0, value6: 2, value7: 1, value8: 0, value9: 3, value10: 1, value11: 0, value12: 1, value13: 0, value14: 0, value15: 3, value16: 3, value17: 0, value18: 1, value19: 1, value20: 2, value21: 0, value22: 3, value23: 1, value24: 1, value25: 3, value26: 0, value27: 3, value28: 3, value29: 1, value30: 1, value31: 0, value32: 1, value33: 0, value34: 3 },
    { id: "3", dimension: "Standards Lerninhalte", value1: 29, valueProzentGesamt1: 29, value2: 34, valueProzentGesamt2: 34, value3: 37, valueProzentGesamt3: 37, valueGesamt1: 16, valueGesamt2: 8, valueGesamt3: 10, value1: 1, value2: 1, value3: 1, value4: 0, value5: 2, value6: 3, value7: 2, value8: 3, value9: 2, value10: 3, value11: 3, value12: 0, value13: 0, value14: 2, value15: 3, value16: 1, value17: 1, value18: 1, value19: 3, value20: 2, value21: 0, value22: 0, value23: 2, value24: 1, value25: 0, value26: 1, value27: 3, value28: 2, value29: 2, value30: 3, value31: 3, value32: 1, value33: 0, value34: 3 },
    { id: "4", dimension: "Wissensrepräsen.", value1: 26, valueProzentGesamt1: 26, value2: 31, valueProzentGesamt2: 31, value3: 43, valueProzentGesamt3: 43, valueGesamt1: 18, valueGesamt2: 7, valueGesamt3: 9, value1: 2, value2: 0, value3: 0, value4: 1, value5: 0, value6: 2, value7: 3, value8: 0, value9: 2, value10: 0, value11: 3, value12: 1, value13: 1, value14: 2, value15: 3, value16: 0, value17: 2, value18: 0, value19: 3, value20: 1, value21: 0, value22: 1, value23: 3, value24: 2, value25: 3, value26: 2, value27: 1, value28: 0, value29: 3, value30: 0, value31: 3, value32: 1, value33: 1, value34: 3 },
    { id: "5", dimension: "Intelligente Suche", value1: 17, valueProzentGesamt1: 17, value2: 34, valueProzentGesamt2: 34, value3: 49, valueProzentGesamt3: 49, valueGesamt1: 20, valueGesamt2: 8, valueGesamt3: 6, value1: 0, value2: 2, value3: 0, value4: 2, value5: 1, value6: 0, value7: 0, value8: 2, value9: 3, value10: 0, value11: 0, value12: 0, value13: 2, value14: 1, value15: 2, value16: 3, value17: 2, value18: 1, value19: 0, value20: 3, value21: 1, value22: 0, value23: 3, value24: 2, value25: 2, value26: 1, value27: 0, value28: 0, value29: 1, value30: 1, value31: 3, value32: 3, value33: 1, value34: 1 },
    { id: "6", dimension: "Learning Analytics", value1: 26, valueProzentGesamt1: 26, value2: 31, valueProzentGesamt2: 31, value3: 43, valueProzentGesamt3: 43, valueGesamt1: 18, valueGesamt2: 7, valueGesamt3: 9, value1: 0, value2: 1, value3: 2, value4: 1, value5: 0, value6: 3, value7: 0, value8: 3, value9: 0, value10: 2, value11: 3, value12: 2, value13: 1, value14: 2, value15: 1, value16: 3, value17: 0, value18: 1, value19: 2, value20: 0, value21: 1, value22: 0, value23: 2, value24: 1, value25: 3, value26: 0, value27: 2, value28: 3, value29: 3, value30: 1, value31: 0, value32: 3, value33: 1, value34: 3 },
    { id: "7", dimension: "Adaptive Lerninh.", value1: 24, valueProzentGesamt1: 24, value2: 36, valueProzentGesamt2: 36, value3: 40, valueProzentGesamt3: 40, valueGesamt1: 17, valueGesamt2: 9, valueGesamt3: 8, value1: 1, value2: 2, value3: 3, value4: 2, value5: 2, value6: 1, value7: 1, value8: 2, value9: 0, value10: 2, value11: 0, value12: 1, value13: 3, value14: 0, value15: 1, value16: 0, value17: 3, value18: 3, value19: 3, value20: 0, value21: 1, value22: 3, value23: 0, value24: 2, value25: 0, value26: 2, value27: 0, value28: 1, value29: 1, value30: 3, value31: 0, value32: 3, value33: 2, value34: 2 },
    { id: "8", dimension: "Lernempfehlungssyst.", value1: 29, valueProzentGesamt1: 29, value2: 34, valueProzentGesamt2: 34, value3: 37, valueProzentGesamt3: 37, valueGesamt1: 16, valueGesamt2: 8, valueGesamt3: 10, value1: 1, value2: 2, value3: 2, value4: 1, value5: 3, value6: 1, value7: 2, value8: 2, value9: 1, value10: 3, value11: 1, value12: 3, value13: 0, value14: 2, value15: 1, value16: 3, value17: 3, value18: 3, value19: 3, value20: 3, value21: 0, value22: 2, value23: 1, value24: 2, value25: 1, value26: 3, value27: 0, value28: 1, value29: 2, value30: 0, value31: 1, value32: 1, value33: 1, value34: 3 },
    { id: "9", dimension: "Kollaboration", value1: 38, valueProzentGesamt1: 38, value2: 34, valueProzentGesamt2: 34, value3: 28, valueProzentGesamt3: 28, valueGesamt1: 13, valueGesamt2: 8, valueGesamt3: 13, value1: 0, value2: 0, value3: 2, value4: 3, value5: 1, value6: 3, value7: 1, value8: 1, value9: 0, value10: 2, value11: 1, value12: 3, value13: 3, value14: 3, value15: 3, value16: 3, value17: 2, value18: 3, value19: 1, value20: 3, value21: 0, value22: 1, value23: 1, value24: 1, value25: 3, value26: 2, value27: 3, value28: 2, value29: 2, value30: 2, value31: 0, value32: 3, value33: 2, value34: 3 },
    { id: "10", dimension: "Peer-Support", value1: 36, valueProzentGesamt1: 36, value2: 36, valueProzentGesamt2: 36, value3: 28, valueProzentGesamt3: 28, valueGesamt1: 13, valueGesamt2: 9, valueGesamt3: 12, value1: 1, value2: 2, value3: 1, value4: 3, value5: 3, value6: 1, value7: 3, value8: 2, value9: 0, value10: 3, value11: 2, value12: 2, value13: 3, value14: 3, value15: 1, value16: 3, value17: 3, value18: 1, value19: 0, value20: 2, value21: 2, value22: 0, value23: 0, value24: 1, value25: 0, value26: 2, value27: 2, value28: 3, value29: 1, value30: 2, value31: 3, value32: 1, value33: 3, value34: 3 },
    { id: "11", dimension: "Partizipation", value1: 20, valueProzentGesamt1: 20, value2: 28, valueProzentGesamt2: 28, value3: 52, valueProzentGesamt3: 52, valueGesamt1: 21, valueGesamt2: 6, valueGesamt3: 7, value1: 1, value2: 0, value3: 3, value4: 0, value5: 2, value6: 1, value7: 3, value8: 3, value9: 1, value10: 1, value11: 0, value12: 2, value13: 1, value14: 0, value15: 1, value16: 3, value17: 3, value18: 2, value19: 0, value20: 1, value21: 1, value22: 2, value23: 1, value24: 3, value25: 2, value26: 1, value27: 1, value28: 2, value29: 3, value30: 0, value31: 1, value32: 0, value33: 1, value34: 0 },
    { id: "12", dimension: "Accessability", value1: 18, valueProzentGesamt1: 18, value2: 36, valueProzentGesamt2: 36, value3: 46, valueProzentGesamt3: 46, valueGesamt1: 19, valueGesamt2: 9, valueGesamt3: 6, value1: 3, value2: 0, value3: 1, value4: 1, value5: 1, value6: 1, value7: 3, value8: 1, value9: 1, value10: 0, value11: 1, value12: 0, value13: 2, value14: 1, value15: 3, value16: 2, value17: 3, value18: 1, value19: 0, value20: 1, value21: 3, value22: 2, value23: 2, value24: 3, value25: 2, value26: 1, value27: 2, value28: 1, value29: 1, value30: 2, value31: 2, value32: 0, value33: 2, value34: 1 },
    { id: "13", dimension: "OSS & KI Modelle", value1: 27, valueProzentGesamt1: 27, value2: 39, valueProzentGesamt2: 39, value3: 34, valueProzentGesamt3: 34, valueGesamt1: 15, valueGesamt2: 10, valueGesamt3: 9, value1: 1, value2: 3, value3: 3, value4: 2, value5: 3, value6: 3, value7: 2, value8: 1, value9: 2, value10: 3, value11: 3, value12: 3, value13: 0, value14: 3, value15: 3, value16: 0, value17: 0, value18: 0, value19: 2, value20: 2, value21: 2, value22: 0, value23: 2, value24: 2, value25: 1, value26: 0, value27: 1, value28: 0, value29: 0, value30: 2, value31: 0, value32: 2, value33: 1, value34: 0 },
    { id: "14", dimension: "OSS LMS & Plugin", value1: 32, valueProzentGesamt1: 32, value2: 34, valueProzentGesamt2: 34, value3: 34, valueProzentGesamt3: 34, valueGesamt1: 15, valueGesamt2: 8, valueGesamt3: 11, value1: 0, value2: 3, value3: 3, value4: 2, value5: 2, value6: 0, value7: 0, value8: 1, value9: 0, value10: 2, value11: 0, value12: 2, value13: 1, value14: 1, value15: 3, value16: 2, value17: 1, value18: 3, value19: 0, value20: 3, value21: 1, value22: 2, value23: 0, value24: 1, value25: 0, value26: 3, value27: 3, value28: 3, value29: 2, value30: 2, value31: 3, value32: 0, value33: 3, value34: 3 },
    { id: "15", dimension: "API Zugriff", value1: 26, valueProzentGesamt1: 26, value2: 34, valueProzentGesamt2: 34, value3: 40, valueProzentGesamt3: 40, valueGesamt1: 17, valueGesamt2: 8, valueGesamt3: 9, value1: 1, value2: 2, value3: 0, value4: 3, value5: 2, value6: 2, value7: 3, value8: 1, value9: 3, value10: 2, value11: 1, value12: 3, value13: 3, value14: 2, value15: 2, value16: 1, value17: 1, value18: 1, value19: 0, value20: 0, value21: 1, value22: 3, value23: 3, value24: 0, value25: 0, value26: 2, value27: 3, value28: 1, value29: 1, value30: 1, value31: 3, value32: 1, value33: 0, value34: 2 },
    { id: "16", dimension: "OER", value1: 18, valueProzentGesamt1: 18, value2: 42, valueProzentGesamt2: 42, value3: 40, valueProzentGesamt3: 40, valueGesamt1: 17, valueGesamt2: 11, valueGesamt3: 6, value1: 0, value2: 1, value3: 0, value4: 2, value5: 2, value6: 2, value7: 1, value8: 2, value9: 1, value10: 2, value11: 1, value12: 0, value13: 0, value14: 2, value15: 3, value16: 0, value17: 1, value18: 2, value19: 3, value20: 3, value21: 2, value22: 2, value23: 0, value24: 0, value25: 1, value26: 0, value27: 3, value28: 2, value29: 2, value30: 0, value31: 3, value32: 0, value33: 0, value34: 3 },
    { id: "17", dimension: "IT-Sicherheit", value1: 33, valueProzentGesamt1: 33, value2: 45, valueProzentGesamt2: 45, value3: 22, valueProzentGesamt3: 22, valueGesamt1: 11, valueGesamt2: 12, valueGesamt3: 11, value1: 1, value2: 0, value3: 0, value4: 1, value5: 2, value6: 3, value7: 2, value8: 0, value9: 3, value10: 3, value11: 2, value12: 0, value13: 3, value14: 3, value15: 2, value16: 2, value17: 0, value18: 2, value19: 3, value20: 2, value21: 0, value22: 3, value23: 3, value24: 1, value25: 0, value26: 2, value27: 2, value28: 2, value29: 3, value30: 2, value31: 1, value32: 2, value33: 3, value34: 3 },
    { id: "18", dimension: "Datenschutz", value1: 18, valueProzentGesamt1: 18, value2: 36, valueProzentGesamt2: 36, value3: 46, valueProzentGesamt3: 46, valueGesamt1: 19, valueGesamt2: 9, valueGesamt3: 6, value1: 0, value2: 2, value3: 1, value4: 2, value5: 3, value6: 2, value7: 3, value8: 2, value9: 3, value10: 1, value11: 1, value12: 0, value13: 0, value14: 1, value15: 1, value16: 3, value17: 0, value18: 0, value19: 3, value20: 2, value21: 1, value22: 2, value23: 1, value24: 1, value25: 0, value26: 1, value27: 1, value28: 0, value29: 1, value30: 0, value31: 2, value32: 3, value33: 2, value34: 2 },
    { id: "19", dimension: "Datenethik", value1: 33, valueProzentGesamt1: 33, value2: 39, valueProzentGesamt2: 39, value3: 28, valueProzentGesamt3: 28, valueGesamt1: 13, valueGesamt2: 10, valueGesamt3: 11, value1: 1, value2: 3, value3: 3, value4: 3, value5: 0, value6: 2, value7: 3, value8: 0, value9: 2, value10: 2, value11: 3, value12: 1, value13: 2, value14: 0, value15: 2, value16: 2, value17: 2, value18: 3, value19: 1, value20: 2, value21: 3, value22: 0, value23: 1, value24: 1, value25: 1, value26: 2, value27: 3, value28: 3, value29: 0, value30: 2, value31: 3, value32: 1, value33: 3, value34: 1 },
    { id: "20", dimension: "Digitale Identitäten", value1: 9, valueProzentGesamt1: 9, value2: 51, valueProzentGesamt2: 51, value3: 40, valueProzentGesamt3: 40, valueGesamt1: 17, valueGesamt2: 14, valueGesamt3: 3, value1: 0, value2: 1, value3: 3, value4: 1, value5: 2, value6: 2, value7: 3, value8: 1, value9: 0, value10: 0, value11: 0, value12: 2, value13: 2, value14: 2, value15: 1, value16: 1, value17: 1, value18: 1, value19: 0, value20: 2, value21: 2, value22: 1, value23: 2, value24: 1, value25: 3, value26: 2, value27: 2, value28: 2, value29: 2, value30: 2, value31: 2, value32: 1, value33: 1, value34: 0 },

];
var dataUnterDimensionenEinzelStandZeitpunktA = dataUnterDimensionenEinzelStandAntrag; //Datensatz Slider erste position (=links) 

var dataUnterDimensionenEinzelStandZB2021 = [ //Daten Array für Radarboard Einzelvorhaben
    { id: "1", dimension: "Kompetenzstandards", valueProzentGesamt1: 24, valueProzentGesamt2: 50, valueProzentGesamt3: 26, valueGesamt1: 14, valueGesamt2: 12, valueGesamt3: 8, value1: 3, value2: 0, value3: 2, value4: 0, value5: 3, value6: 0, value7: 2, value8: 3, value9: 2, value10: 1, value11: 2, value12: 0, value13: 0, value14: 2, value15: 2, value16: 3, value17: 2, value18: 0, value19: 2, value20: 0, value21: 2, value22: 3, value23: 2, value24: 3, value25: 1, value26: 1, value27: 3, value28: 3, value29: 1, value30: 2, value31: 0, value32: 0, value33: 1, value34: 2 },
    { id: "2", dimension: "Bildungsnachweise", valueProzentGesamt1: 23, valueProzentGesamt2: 39, valueProzentGesamt3: 38, valueGesamt1: 18, valueGesamt2: 8, valueGesamt3: 8, value1: 3, value2: 2, value3: 1, value4: 2, value5: 3, value6: 1, value7: 1, value8: 1, value9: 2, value10: 2, value11: 0, value12: 3, value13: 0, value14: 1, value15: 2, value16: 1, value17: 2, value18: 3, value19: 3, value20: 3, value21: 1, value22: 1, value23: 0, value24: 1, value25: 0, value26: 2, value27: 3, value28: 0, value29: 0, value30: 3, value31: 0, value32: 1, value33: 2, value34: 0 },
    { id: "3", dimension: "Standards Lerninhalte", valueProzentGesamt1: 12, valueProzentGesamt2: 50, valueProzentGesamt3: 38, valueGesamt1: 18, valueGesamt2: 12, valueGesamt3: 4, value1: 0, value2: 0, value3: 3, value4: 0, value5: 0, value6: 3, value7: 2, value8: 1, value9: 0, value10: 0, value11: 2, value12: 1, value13: 0, value14: 0, value15: 2, value16: 2, value17: 0, value18: 3, value19: 0, value20: 3, value21: 2, value22: 2, value23: 0, value24: 0, value25: 1, value26: 2, value27: 2, value28: 2, value29: 0, value30: 1, value31: 2, value32: 2, value33: 2, value34: 1 },
    { id: "4", dimension: "Wissensrepräsen.", valueProzentGesamt1: 15, valueProzentGesamt2: 50, valueProzentGesamt3: 35, valueGesamt1: 17, valueGesamt2: 12, valueGesamt3: 5, value1: 2, value2: 2, value3: 2, value4: 3, value5: 1, value6: 2, value7: 0, value8: 1, value9: 2, value10: 1, value11: 2, value12: 1, value13: 3, value14: 2, value15: 2, value16: 0, value17: 3, value18: 1, value19: 3, value20: 0, value21: 2, value22: 2, value23: 2, value24: 1, value25: 3, value26: 0, value27: 0, value28: 1, value29: 1, value30: 2, value31: 1, value32: 0, value33: 0, value34: 1 },
    { id: "5", dimension: "Intelligente Suche", valueProzentGesamt1: 23, valueProzentGesamt2: 39, valueProzentGesamt3: 38, valueGesamt1: 18, valueGesamt2: 8, valueGesamt3: 8, value1: 0, value2: 2, value3: 3, value4: 2, value5: 3, value6: 1, value7: 1, value8: 3, value9: 0, value10: 0, value11: 0, value12: 0, value13: 2, value14: 3, value15: 1, value16: 2, value17: 1, value18: 1, value19: 2, value20: 0, value21: 0, value22: 1, value23: 2, value24: 1, value25: 3, value26: 0, value27: 3, value28: 0, value29: 3, value30: 2, value31: 0, value32: 3, value33: 2, value34: 1 },
    { id: "6", dimension: "Learning Analytics", valueProzentGesamt1: 21, valueProzentGesamt2: 47, valueProzentGesamt3: 32, valueGesamt1: 16, valueGesamt2: 11, valueGesamt3: 7, value1: 2, value2: 2, value3: 1, value4: 3, value5: 1, value6: 2, value7: 1, value8: 3, value9: 2, value10: 0, value11: 1, value12: 2, value13: 3, value14: 0, value15: 0, value16: 0, value17: 2, value18: 0, value19: 3, value20: 2, value21: 3, value22: 2, value23: 1, value24: 0, value25: 2, value26: 1, value27: 3, value28: 2, value29: 1, value30: 0, value31: 1, value32: 3, value33: 1, value34: 2 },
    { id: "7", dimension: "Adaptive Lerninh.", valueProzentGesamt1: 27, valueProzentGesamt2: 41, valueProzentGesamt3: 32, valueGesamt1: 16, valueGesamt2: 9, valueGesamt3: 9, value1: 2, value2: 1, value3: 3, value4: 0, value5: 1, value6: 0, value7: 1, value8: 1, value9: 1, value10: 1, value11: 2, value12: 1, value13: 0, value14: 0, value15: 2, value16: 0, value17: 2, value18: 3, value19: 3, value20: 3, value21: 3, value22: 2, value23: 1, value24: 2, value25: 1, value26: 3, value27: 0, value28: 2, value29: 3, value30: 1, value31: 2, value32: 3, value33: 2, value34: 3 },
    { id: "8", dimension: "Lernempfehlungssyst.", valueProzentGesamt1: 29, valueProzentGesamt2: 39, valueProzentGesamt3: 32, valueGesamt1: 16, valueGesamt2: 8, valueGesamt3: 10, value1: 3, value2: 2, value3: 1, value4: 1, value5: 3, value6: 3, value7: 3, value8: 0, value9: 0, value10: 3, value11: 0, value12: 0, value13: 0, value14: 2, value15: 2, value16: 2, value17: 1, value18: 0, value19: 2, value20: 3, value21: 1, value22: 0, value23: 0, value24: 1, value25: 3, value26: 3, value27: 2, value28: 1, value29: 3, value30: 2, value31: 2, value32: 0, value33: 0, value34: 3 },
    { id: "9", dimension: "Kollaboration", valueProzentGesamt1: 23, valueProzentGesamt2: 39, valueProzentGesamt3: 38, valueGesamt1: 18, valueGesamt2: 8, valueGesamt3: 8, value1: 2, value2: 3, value3: 0, value4: 2, value5: 2, value6: 0, value7: 0, value8: 1, value9: 0, value10: 3, value11: 3, value12: 1, value13: 0, value14: 2, value15: 3, value16: 1, value17: 1, value18: 3, value19: 3, value20: 0, value21: 2, value22: 2, value23: 1, value24: 3, value25: 0, value26: 3, value27: 1, value28: 0, value29: 0, value30: 0, value31: 1, value32: 2, value33: 2, value34: 0 },
    { id: "10", dimension: "Peer-Support", valueProzentGesamt1: 9, valueProzentGesamt2: 47, valueProzentGesamt3: 44, valueGesamt1: 20, valueGesamt2: 11, valueGesamt3: 3, value1: 2, value2: 1, value3: 1, value4: 2, value5: 0, value6: 0, value7: 1, value8: 0, value9: 2, value10: 1, value11: 2, value12: 0, value13: 3, value14: 2, value15: 1, value16: 0, value17: 2, value18: 1, value19: 2, value20: 0, value21: 0, value22: 1, value23: 1, value24: 1, value25: 2, value26: 2, value27: 2, value28: 1, value29: 3, value30: 2, value31: 1, value32: 0, value33: 3, value34: 0 },
    { id: "11", dimension: "Partizipation", valueProzentGesamt1: 23, valueProzentGesamt2: 27, valueProzentGesamt3: 50, valueGesamt1: 22, valueGesamt2: 4, valueGesamt3: 8, value1: 3, value2: 3, value3: 3, value4: 1, value5: 1, value6: 0, value7: 2, value8: 1, value9: 1, value10: 3, value11: 2, value12: 0, value13: 1, value14: 1, value15: 3, value16: 2, value17: 0, value18: 1, value19: 1, value20: 0, value21: 3, value22: 0, value23: 0, value24: 0, value25: 0, value26: 1, value27: 1, value28: 2, value29: 1, value30: 3, value31: 0, value32: 3, value33: 0, value34: 1 },
    { id: "12", dimension: "Accessability", valueProzentGesamt1: 24, valueProzentGesamt2: 41, valueProzentGesamt3: 35, valueGesamt1: 17, valueGesamt2: 9, valueGesamt3: 8, value1: 3, value2: 0, value3: 2, value4: 3, value5: 3, value6: 0, value7: 3, value8: 3, value9: 2, value10: 1, value11: 1, value12: 2, value13: 0, value14: 3, value15: 2, value16: 0, value17: 0, value18: 1, value19: 0, value20: 1, value21: 1, value22: 3, value23: 1, value24: 1, value25: 2, value26: 0, value27: 0, value28: 1, value29: 2, value30: 3, value31: 2, value32: 2, value33: 1, value34: 2 },
    { id: "13", dimension: "OSS & KI Modelle", valueProzentGesamt1: 26, valueProzentGesamt2: 30, valueProzentGesamt3: 44, valueGesamt1: 20, valueGesamt2: 5, valueGesamt3: 9, value1: 2, value2: 2, value3: 1, value4: 1, value5: 3, value6: 3, value7: 3, value8: 3, value9: 1, value10: 1, value11: 0, value12: 0, value13: 1, value14: 2, value15: 2, value16: 0, value17: 3, value18: 0, value19: 1, value20: 2, value21: 3, value22: 3, value23: 1, value24: 1, value25: 0, value26: 0, value27: 0, value28: 0, value29: 3, value30: 1, value31: 1, value32: 1, value33: 3, value34: 0 },
    { id: "14", dimension: "OSS LMS & Plugin", valueProzentGesamt1: 17, valueProzentGesamt2: 39, valueProzentGesamt3: 44, valueGesamt1: 20, valueGesamt2: 8, valueGesamt3: 6, value1: 0, value2: 0, value3: 1, value4: 2, value5: 0, value6: 0, value7: 2, value8: 3, value9: 0, value10: 3, value11: 2, value12: 3, value13: 0, value14: 2, value15: 1, value16: 3, value17: 1, value18: 2, value19: 3, value20: 0, value21: 1, value22: 0, value23: 2, value24: 3, value25: 0, value26: 0, value27: 1, value28: 2, value29: 0, value30: 1, value31: 0, value32: 2, value33: 0, value34: 1 },
    { id: "15", dimension: "API Zugriff", valueProzentGesamt1: 29, valueProzentGesamt2: 33, valueProzentGesamt3: 38, valueGesamt1: 18, valueGesamt2: 6, valueGesamt3: 10, value1: 1, value2: 0, value3: 1, value4: 1, value5: 1, value6: 1, value7: 0, value8: 1, value9: 3, value10: 0, value11: 3, value12: 2, value13: 3, value14: 3, value15: 3, value16: 2, value17: 3, value18: 3, value19: 3, value20: 1, value21: 1, value22: 0, value23: 0, value24: 1, value25: 3, value26: 1, value27: 0, value28: 0, value29: 2, value30: 3, value31: 2, value32: 2, value33: 1, value34: 2 },
    { id: "16", dimension: "OER", valueProzentGesamt1: 30, valueProzentGesamt2: 41, valueProzentGesamt3: 29, valueGesamt1: 15, valueGesamt2: 9, valueGesamt3: 10, value1: 3, value2: 0, value3: 1, value4: 0, value5: 2, value6: 1, value7: 1, value8: 3, value9: 2, value10: 3, value11: 3, value12: 3, value13: 0, value14: 1, value15: 3, value16: 2, value17: 0, value18: 2, value19: 3, value20: 2, value21: 0, value22: 2, value23: 2, value24: 3, value25: 3, value26: 0, value27: 1, value28: 0, value29: 1, value30: 2, value31: 0, value32: 1, value33: 2, value34: 3 },
    { id: "17", dimension: "IT-Sicherheit", valueProzentGesamt1: 23, valueProzentGesamt2: 30, valueProzentGesamt3: 47, valueGesamt1: 21, valueGesamt2: 5, valueGesamt3: 8, value1: 0, value2: 1, value3: 0, value4: 0, value5: 0, value6: 0, value7: 2, value8: 3, value9: 1, value10: 3, value11: 1, value12: 0, value13: 0, value14: 1, value15: 0, value16: 1, value17: 0, value18: 1, value19: 0, value20: 2, value21: 0, value22: 2, value23: 3, value24: 3, value25: 1, value26: 1, value27: 3, value28: 3, value29: 1, value30: 3, value31: 2, value32: 2, value33: 3, value34: 1 },
    { id: "18", dimension: "Datenschutz", valueProzentGesamt1: 24, valueProzentGesamt2: 41, valueProzentGesamt3: 35, valueGesamt1: 17, valueGesamt2: 9, valueGesamt3: 8, value1: 0, value2: 1, value3: 3, value4: 0, value5: 0, value6: 1, value7: 3, value8: 2, value9: 1, value10: 3, value11: 0, value12: 3, value13: 3, value14: 2, value15: 0, value16: 1, value17: 2, value18: 2, value19: 3, value20: 3, value21: 1, value22: 0, value23: 2, value24: 3, value25: 1, value26: 0, value27: 0, value28: 1, value29: 2, value30: 2, value31: 2, value32: 2, value33: 0, value34: 1 },
    { id: "19", dimension: "Datenethik", valueProzentGesamt1: 24, valueProzentGesamt2: 44, valueProzentGesamt3: 32, valueGesamt1: 16, valueGesamt2: 10, valueGesamt3: 8, value1: 0, value2: 3, value3: 1, value4: 1, value5: 2, value6: 3, value7: 3, value8: 2, value9: 2, value10: 3, value11: 1, value12: 3, value13: 0, value14: 2, value15: 0, value16: 1, value17: 2, value18: 0, value19: 0, value20: 0, value21: 2, value22: 1, value23: 2, value24: 3, value25: 1, value26: 1, value27: 1, value28: 1, value29: 1, value30: 3, value31: 2, value32: 2, value33: 2, value34: 3 },
    { id: "20", dimension: "Digitale Identitäten", valueProzentGesamt1: 41, valueProzentGesamt2: 36, valueProzentGesamt3: 23, valueGesamt1: 13, valueGesamt2: 7, valueGesamt3: 14, value1: 1, value2: 1, value3: 2, value4: 3, value5: 2, value6: 2, value7: 0, value8: 2, value9: 3, value10: 3, value11: 0, value12: 3, value13: 3, value14: 2, value15: 2, value16: 0, value17: 3, value18: 0, value19: 0, value20: 0, value21: 3, value22: 1, value23: 3, value24: 3, value25: 2, value26: 3, value27: 3, value28: 1, value29: 3, value30: 0, value31: 0, value32: 3, value33: 3, value34: 0 },

];
var dataUnterDimensionenEinzelStandZeitpunktB = dataUnterDimensionenEinzelStandZB2021; //Datensatz Slider 2. position (=mitte) 

var dataUnterDimensionenEinzelStandTagung2022 = [ //Daten Array für Radarboard Einzelvorhaben
    { id: "1", dimension: "Kompetenzstandards", valueProzentGesamt1: 21, valueProzentGesamt2: 31, valueProzentGesamt3: 48, valueGesamt1: 18, valueGesamt2: 9, valueGesamt3: 7, value1: 1, value2: 1, value3: 2, value4: 3, value5: 2, value6: 3, value7: 0, value8: 2, value9: 1, value10: 3, value11: 1, value12: 3, value13: 0, value14: 3, value15: 1, value16: 2, value17: 1, value18: 3, value19: 2, value20: 0, value21: 2, value22: 2, value23: 2, value24: 1, value25: 0, value26: 0, value27: 3, value28: 0, value29: 1, value30: 0, value31: 1, value32: 2, value33: 1, value34: 1 },
    { id: "2", dimension: "Bildungsnachweise", valueProzentGesamt1: 32, valueProzentGesamt2: 20, valueProzentGesamt3: 48, valueGesamt1: 18, valueGesamt2: 5, valueGesamt3: 11, value1: 0, value2: 2, value3: 3, value4: 1, value5: 3, value6: 3, value7: 3, value8: 0, value9: 0, value10: 3, value11: 3, value12: 2, value13: 1, value14: 1, value15: 2, value16: 0, value17: 1, value18: 2, value19: 3, value20: 3, value21: 0, value22: 3, value23: 1, value24: 0, value25: 0, value26: 1, value27: 0, value28: 3, value29: 0, value30: 1, value31: 0, value32: 3, value33: 0, value34: 2 },
    { id: "3", dimension: "Standards Lerninhalte", valueProzentGesamt1: 6, valueProzentGesamt2: 34, valueProzentGesamt3: 60, valueGesamt1: 22, valueGesamt2: 10, valueGesamt3: 2, value1: 1, value2: 2, value3: 0, value4: 0, value5: 2, value6: 0, value7: 2, value8: 1, value9: 1, value10: 0, value11: 2, value12: 2, value13: 0, value14: 1, value15: 1, value16: 2, value17: 0, value18: 0, value19: 1, value20: 1, value21: 2, value22: 2, value23: 0, value24: 0, value25: 3, value26: 2, value27: 0, value28: 3, value29: 2, value30: 0, value31: 1, value32: 0, value33: 0, value34: 0 },
    { id: "4", dimension: "Wissensrepräsen.", valueProzentGesamt1: 29, valueProzentGesamt2: 26, valueProzentGesamt3: 45, valueGesamt1: 17, valueGesamt2: 7, valueGesamt3: 10, value1: 1, value2: 1, value3: 3, value4: 0, value5: 3, value6: 2, value7: 2, value8: 0, value9: 3, value10: 2, value11: 3, value12: 3, value13: 2, value14: 1, value15: 1, value16: 2, value17: 0, value18: 1, value19: 0, value20: 1, value21: 0, value22: 2, value23: 1, value24: 3, value25: 0, value26: 2, value27: 0, value28: 3, value29: 3, value30: 3, value31: 0, value32: 1, value33: 3, value34: 0 },
    { id: "5", dimension: "Intelligente Suche", valueProzentGesamt1: 23, valueProzentGesamt2: 26, valueProzentGesamt3: 51, valueGesamt1: 19, valueGesamt2: 7, valueGesamt3: 8, value1: 0, value2: 3, value3: 2, value4: 0, value5: 3, value6: 1, value7: 1, value8: 3, value9: 1, value10: 1, value11: 0, value12: 3, value13: 0, value14: 2, value15: 0, value16: 3, value17: 0, value18: 0, value19: 2, value20: 1, value21: 2, value22: 1, value23: 1, value24: 0, value25: 2, value26: 1, value27: 1, value28: 2, value29: 1, value30: 3, value31: 3, value32: 2, value33: 0, value34: 3 },
    { id: "6", dimension: "Learning Analytics", valueProzentGesamt1: 30, valueProzentGesamt2: 31, valueProzentGesamt3: 39, valueGesamt1: 15, valueGesamt2: 9, valueGesamt3: 10, value1: 3, value2: 2, value3: 3, value4: 3, value5: 1, value6: 3, value7: 1, value8: 0, value9: 2, value10: 2, value11: 2, value12: 3, value13: 2, value14: 3, value15: 3, value16: 0, value17: 0, value18: 3, value19: 2, value20: 1, value21: 1, value22: 0, value23: 1, value24: 3, value25: 1, value26: 2, value27: 3, value28: 1, value29: 0, value30: 1, value31: 0, value32: 0, value33: 2, value34: 2 },
    { id: "7", dimension: "Adaptive Lerninh.", valueProzentGesamt1: 23, valueProzentGesamt2: 29, valueProzentGesamt3: 48, valueGesamt1: 18, valueGesamt2: 8, valueGesamt3: 8, value1: 0, value2: 2, value3: 1, value4: 1, value5: 3, value6: 1, value7: 2, value8: 2, value9: 0, value10: 0, value11: 1, value12: 0, value13: 3, value14: 0, value15: 0, value16: 3, value17: 2, value18: 3, value19: 2, value20: 3, value21: 3, value22: 1, value23: 1, value24: 1, value25: 2, value26: 2, value27: 2, value28: 0, value29: 1, value30: 1, value31: 3, value32: 0, value33: 3, value34: 0 },
    { id: "8", dimension: "Lernempfehlungssyst.", valueProzentGesamt1: 21, valueProzentGesamt2: 31, valueProzentGesamt3: 48, valueGesamt1: 18, valueGesamt2: 9, valueGesamt3: 7, value1: 0, value2: 1, value3: 2, value4: 1, value5: 1, value6: 1, value7: 3, value8: 2, value9: 2, value10: 1, value11: 1, value12: 0, value13: 2, value14: 2, value15: 1, value16: 3, value17: 3, value18: 2, value19: 3, value20: 1, value21: 2, value22: 1, value23: 1, value24: 3, value25: 1, value26: 2, value27: 3, value28: 2, value29: 0, value30: 1, value31: 1, value32: 1, value33: 3, value34: 0 },
    { id: "9", dimension: "Kollaboration", valueProzentGesamt1: 12, valueProzentGesamt2: 31, valueProzentGesamt3: 57, valueGesamt1: 21, valueGesamt2: 9, valueGesamt3: 4, value1: 2, value2: 3, value3: 1, value4: 2, value5: 2, value6: 2, value7: 1, value8: 0, value9: 1, value10: 1, value11: 0, value12: 1, value13: 1, value14: 0, value15: 1, value16: 1, value17: 1, value18: 2, value19: 1, value20: 2, value21: 1, value22: 1, value23: 1, value24: 1, value25: 1, value26: 3, value27: 1, value28: 1, value29: 2, value30: 1, value31: 3, value32: 2, value33: 2, value34: 3 },
    { id: "10", dimension: "Peer-Support", valueProzentGesamt1: 14, valueProzentGesamt2: 23, valueProzentGesamt3: 63, valueGesamt1: 23, valueGesamt2: 6, valueGesamt3: 5, value1: 2, value2: 0, value3: 1, value4: 3, value5: 3, value6: 2, value7: 2, value8: 0, value9: 1, value10: 0, value11: 3, value12: 1, value13: 1, value14: 3, value15: 0, value16: 0, value17: 1, value18: 0, value19: 0, value20: 1, value21: 0, value22: 1, value23: 0, value24: 0, value25: 3, value26: 2, value27: 2, value28: 1, value29: 1, value30: 1, value31: 0, value32: 2, value33: 1, value34: 0 },
    { id: "11", dimension: "Partizipation", valueProzentGesamt1: 26, valueProzentGesamt2: 29, valueProzentGesamt3: 45, valueGesamt1: 17, valueGesamt2: 8, valueGesamt3: 9, value1: 3, value2: 3, value3: 3, value4: 2, value5: 3, value6: 1, value7: 2, value8: 2, value9: 1, value10: 3, value11: 1, value12: 0, value13: 0, value14: 0, value15: 1, value16: 1, value17: 1, value18: 2, value19: 3, value20: 1, value21: 1, value22: 1, value23: 1, value24: 2, value25: 3, value26: 2, value27: 1, value28: 1, value29: 3, value30: 2, value31: 1, value32: 0, value33: 2, value34: 3 },
    { id: "12", dimension: "Accessability", valueProzentGesamt1: 26, valueProzentGesamt2: 29, valueProzentGesamt3: 45, valueGesamt1: 17, valueGesamt2: 8, valueGesamt3: 9, value1: 0, value2: 2, value3: 2, value4: 1, value5: 2, value6: 2, value7: 0, value8: 1, value9: 3, value10: 1, value11: 0, value12: 1, value13: 3, value14: 1, value15: 3, value16: 1, value17: 2, value18: 2, value19: 3, value20: 3, value21: 1, value22: 3, value23: 0, value24: 3, value25: 3, value26: 1, value27: 0, value28: 1, value29: 3, value30: 0, value31: 2, value32: 2, value33: 0, value34: 1 },
    { id: "13", dimension: "OSS & KI Modelle", valueProzentGesamt1: 18, valueProzentGesamt2: 40, valueProzentGesamt3: 42, valueGesamt1: 16, valueGesamt2: 12, valueGesamt3: 6, value1: 1, value2: 0, value3: 3, value4: 0, value5: 2, value6: 2, value7: 0, value8: 2, value9: 2, value10: 0, value11: 2, value12: 3, value13: 0, value14: 0, value15: 3, value16: 3, value17: 2, value18: 1, value19: 1, value20: 2, value21: 2, value22: 2, value23: 0, value24: 0, value25: 0, value26: 2, value27: 2, value28: 3, value29: 2, value30: 1, value31: 3, value32: 0, value33: 0, value34: 1 },
    { id: "14", dimension: "OSS LMS & Plugin", valueProzentGesamt1: 18, valueProzentGesamt2: 31, valueProzentGesamt3: 51, valueGesamt1: 19, valueGesamt2: 9, valueGesamt3: 6, value1: 2, value2: 3, value3: 2, value4: 1, value5: 3, value6: 2, value7: 1, value8: 0, value9: 2, value10: 2, value11: 2, value12: 3, value13: 0, value14: 0, value15: 0, value16: 2, value17: 1, value18: 1, value19: 0, value20: 0, value21: 1, value22: 1, value23: 3, value24: 1, value25: 1, value26: 0, value27: 2, value28: 2, value29: 0, value30: 1, value31: 3, value32: 0, value33: 0, value34: 3 },
    { id: "15", dimension: "API Zugriff", valueProzentGesamt1: 26, valueProzentGesamt2: 29, valueProzentGesamt3: 45, valueGesamt1: 17, valueGesamt2: 8, valueGesamt3: 9, value1: 0, value2: 3, value3: 1, value4: 3, value5: 0, value6: 1, value7: 0, value8: 0, value9: 3, value10: 0, value11: 2, value12: 3, value13: 3, value14: 2, value15: 2, value16: 1, value17: 2, value18: 3, value19: 3, value20: 2, value21: 1, value22: 3, value23: 0, value24: 2, value25: 2, value26: 0, value27: 2, value28: 3, value29: 1, value30: 1, value31: 1, value32: 0, value33: 0, value34: 0 },
    { id: "16", dimension: "OER", valueProzentGesamt1: 17, valueProzentGesamt2: 29, valueProzentGesamt3: 54, valueGesamt1: 20, valueGesamt2: 8, valueGesamt3: 6, value1: 1, value2: 0, value3: 2, value4: 2, value5: 2, value6: 0, value7: 2, value8: 3, value9: 1, value10: 1, value11: 3, value12: 0, value13: 2, value14: 1, value15: 1, value16: 2, value17: 1, value18: 3, value19: 0, value20: 1, value21: 1, value22: 1, value23: 3, value24: 2, value25: 3, value26: 1, value27: 2, value28: 1, value29: 1, value30: 1, value31: 3, value32: 0, value33: 0, value34: 0 },
    { id: "17", dimension: "IT-Sicherheit", valueProzentGesamt1: 21, valueProzentGesamt2: 40, valueProzentGesamt3: 39, valueGesamt1: 15, valueGesamt2: 12, valueGesamt3: 7, value1: 2, value2: 2, value3: 1, value4: 3, value5: 3, value6: 1, value7: 2, value8: 3, value9: 1, value10: 2, value11: 0, value12: 1, value13: 3, value14: 1, value15: 2, value16: 3, value17: 0, value18: 2, value19: 2, value20: 1, value21: 1, value22: 3, value23: 2, value24: 3, value25: 1, value26: 2, value27: 1, value28: 0, value29: 2, value30: 1, value31: 0, value32: 1, value33: 2, value34: 2 },
    { id: "18", dimension: "Datenschutz", valueProzentGesamt1: 24, valueProzentGesamt2: 34, valueProzentGesamt3: 42, valueGesamt1: 16, valueGesamt2: 10, valueGesamt3: 8, value1: 3, value2: 3, value3: 3, value4: 3, value5: 1, value6: 0, value7: 1, value8: 0, value9: 0, value10: 1, value11: 1, value12: 3, value13: 0, value14: 1, value15: 1, value16: 1, value17: 2, value18: 2, value19: 3, value20: 2, value21: 0, value22: 2, value23: 2, value24: 2, value25: 3, value26: 0, value27: 2, value28: 1, value29: 0, value30: 3, value31: 1, value32: 2, value33: 2, value34: 2 },
    { id: "19", dimension: "Datenethik", valueProzentGesamt1: 26, valueProzentGesamt2: 23, valueProzentGesamt3: 51, valueGesamt1: 19, valueGesamt2: 6, valueGesamt3: 9, value1: 1, value2: 1, value3: 1, value4: 3, value5: 3, value6: 0, value7: 2, value8: 1, value9: 1, value10: 0, value11: 1, value12: 0, value13: 0, value14: 3, value15: 3, value16: 3, value17: 2, value18: 2, value19: 3, value20: 0, value21: 2, value22: 1, value23: 3, value24: 0, value25: 3, value26: 0, value27: 1, value28: 0, value29: 2, value30: 1, value31: 1, value32: 3, value33: 2, value34: 1 },
    { id: "20", dimension: "Digitale Identitäten", valueProzentGesamt1: 12, valueProzentGesamt2: 46, valueProzentGesamt3: 42, valueGesamt1: 16, valueGesamt2: 14, valueGesamt3: 4, value1: 1, value2: 0, value3: 2, value4: 0, value5: 3, value6: 0, value7: 0, value8: 2, value9: 2, value10: 0, value11: 0, value12: 0, value13: 1, value14: 2, value15: 2, value16: 2, value17: 3, value18: 1, value19: 0, value20: 2, value21: 1, value22: 3, value23: 1, value24: 2, value25: 2, value26: 2, value27: 2, value28: 2, value29: 0, value30: 0, value31: 2, value32: 2, value33: 0, value34: 3 },

];
var dataUnterDimensionenEinzelStandZeitpunktC = dataUnterDimensionenEinzelStandTagung2022; //Datensatz Slider 3. position (=rechts) 


//var dataUnterDimensionenEinzel = dataUnterDimensionenEinzelStandZB2021; ///aktuellen Datensatz auf den letzten Stand setzen, dieser ist dann der inital angezeigte Datensatz
var dataUnterDimensionenEinzel = dataUnterDimensionenEinzelStandAntrag; /// slider steht zu Beginn auf StandAntrag
var dataUnterDimensionen = dataUnterDimensionenEinzel; //values nur noch in Einzelarray enthalten

var dataUnterDimensionenEinzelTexte = [ ///Daten Array für Texte jedes Einzel-Radarboards
    { id: "1", name: "Projekt_1", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "2", name: "Projekt_2", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "3", name: "Projekt_3", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "4", name: "Projekt_4", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "5", name: "Projekt_5", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "6", name: "Projekt_6", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "7", name: "Projekt_7", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "8", name: "Projekt_8", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "9", name: "Projekt_9", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "10", name: "Projekt_10", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "11", name: "Projekt_11", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "12", name: "Projekt_12", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "13", name: "Projekt_13", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "14", name: "Projekt_14", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "15", name: "Projekt_15", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "16", name: "Projekt_16", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "17", name: "Projekt_17", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "18", name: "Projekt_18", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "19", name: "Projekt_19", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "20", name: "Projekt_20", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "21", name: "Projekt_21", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "22", name: "Projekt_22", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "23", name: "Projekt_23", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "24", name: "Projekt_24", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "25", name: "Projekt_25", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "26", name: "Projekt_26", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "27", name: "Projekt_27", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "28", name: "Projekt_28", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "29", name: "Projekt_29", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "30", name: "Projekt_30", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "31", name: "Projekt_31", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "32", name: "Projekt_32", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "33", name: "Projekt_33", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },
    { id: "34", name: "Projekt_34", entwicklungsfeld: "", thema: "Adaptives Weiterbildungsunterstützungssystem für die Berufsfelder …", branche: "übergreifend", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, Gamification, personalisierte Lernpfade und Userprofile", technologischeZiel: "Cross-Plattform, Recommendersystem, NLP zur Analyse von ...,  MLOps, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "", besonderheiten: "" },

];

