//#region ///--------C Set Data------------------------------------------------------------------------------------------------
var projekteNamen = ['ADAPT', 'APOLLO', 'ComP-ASS', 'DigiPlat4Train', 'EduPLEx_API', 'ELe-com', 'ExpanderWB3', 'HUBGrade', 'IWWB-PLUS', 'KAINE', 'KAMAELEON', 'KI4CoLearnET', 'KIM', 'KIPerWeb', 'KIRA', 'KIRA_Pro', 'KIWI', 'KUPPEL', 'LIMo', 'LiSiL', 'MINDED_RUHR', 'MyEduLife', 'NetOEV', 'OnCaPflege', 'PolyEx', 'SEARCH', 'SG4BB', 'SMALO', 'StuBu', 'TRIPLEADAPT', 'VerDatAs', 'WBsmart', 'Weiterb.4.OWL', 'WISYatKI'];
var projekteAuspraegung = ['Dim k.A.', 'Dim in Ansätzen.', 'Dim adressiert.', 'Dim ausgepr.'];


/// Zustand welche Projekte gerade in Einzeplorjektanzeige an sind
var projekteEinzelStatusInLegende = Array(projekteNamen.length).fill(0);
//console.log("projekteEinzelStatusInLegende:" + projekteEinzelStatusInLegende);

/// daten und Beschreibung der Oberdimensionen 
var dataDimensionenStandAntrag = [
    { id: 1, value1: 16, value2: 25, value3: 59, dimension: "Unterstützung von KMU beim Strukturwandel", nameKurz: "Unterstützung von KMU beim Strukturwandel", name: "Unterstützung von KMU beim Strukturwandel", textLang: "Wird ein Beitrag zur Strukturentwicklung durch die Unterstützung von\nKMUs durch Agile Management Tools geleistet?" },
    { id: 2, value1: 38, value2: 27, value3: 35, dimension: "Digitale Ökosysteme", nameKurz: "Digitale Ökosysteme", name: "Digitale Ökosysteme", textLang: "Leistet das betrachtete Projekt einen Beitrag zur Transparenz in der\nWeiterbildungslandschaft durch regionale Vernetzung zu digitalen\nÖko- bzw. Bildungssystemen?" },
    { id: 3, value1: 5, value2: 23, value3: 72, dimension: "Niedrigschwellige Zugangsmöglichkeiten", nameKurz: "Niedrigschwellige Zugangsmöglichkeiten", name: "Niedrigschwellige Zugangsmöglichkeiten", textLang: "Leisten Projektentwicklungen einen Beitrag zur Erhöhung der Weiter\nbildungs-Beteiligung durch niedrigschwellige Zugangsmöglichkeiten?" },
    { id: 4, value1: 21, value2: 29, value3: 50, dimension: "Digitale Kompetenzvalidierung", nameKurz: "Digitale Kompetenzvalidierung", name: "Digitale Kompetenzvalidierung", textLang: "Wird ein Beitrag zur digitalen Kompetenzvalidierung sowie –erfassung\ndurch die Orientierung an bestehenden Kompetenzsystematiken, der\n(Weiter-) Entwicklung von Kompetenzmodellen oder der Erfassung \ninformeller Kompetenzen erbracht?" },
    { id: 5, value1: 12, value2: 56, value3: 32, dimension: "Personalisierung und Adaptivität", nameKurz: "Personalisierung und Adaptivität", name: "Personalisierung und Adaptivität", textLang: "Gibt es einen Beitrag zur Erhöhung der Qualität durch Personalisierung\nund Adaptivität?" },
    { id: 6, value1: 30, value2: 40, value3: 30, dimension: "Sonstige Aspekte", nameKurz: "Sonstige", name: "Sonstige Aspekte", textLang: "Weitere inhaltliche Merkmale in den Vorhaben die nicht durch die\nanderen Dimensionen abgedeckt sind." },

];
var dataDimensionenStandZeitpunktA = dataDimensionenStandAntrag; //Zeitpunkt A ist 1. auf slider

var dataDimensionenStandDezember2022 = [
    { id: "1", value1: 18, value2: 33, value3: 49, dimension: "Interoperabilität durch offene Bildungstandards", nameKurz: "Interoperabilität", name: "Interoperabilität durch offene Bildungstandards", textLang: "Fragen der unterstützten Standards und Technologien zur Etablierung\neines gemeinsamen digitalen Weiterbildungsraumes, z. B. zu Kompe-\ntenzen und Wissen, sowie dem Austausch von Kurs-, Leistungs- oder\n Lernergebnissen und Lerninhalten." },
    { id: "2", value1: 38, value2: 29, value3: 33, dimension: "Algorithmen zur Unterstützung der Lernenden", nameKurz: "Algorithmen", name: "Algorithmen zur Unterstützung der Lernenden", textLang: "Fragen des Einsatzes und der Entwicklung von Algorithmen z.B. zur\nSprachverarbeitung (NLP, NLU, NLG), Analyse des Lernverhaltens\n(Learning Analytics) oder der Anpassungsfähigkeit von Lernangeboten\nund -empfehlungen sowie Suchfunktionen durch Nutzende." },
    { id: "3", value1: 7, value2: 25, value3: 68, dimension: "Mitgestaltung, Zugänglichkeit und Zusammenarbeit", nameKurz: "Mitgestaltung", name: "Mitgestaltung, Zugänglichkeit und Zus.arbeit", textLang: "Spektrum der geplanten und umgesetzten Möglichkeiten der Beteiligung,\nZusammenarbeit und Mitgestaltung von Lerninhalten durch Nutzende\nsowie Lösungen zur Nutzbarkeit und zum Nutzungserlebnis." },
    { id: "4", value1: 27, value2: 31, value3: 42, dimension: "Nachnutzbarkeit durch Dritte", nameKurz: "Nachnutzbarkeit", name: "Nachnutzbarkeit durch Dritte", textLang: "Fragen der Offenheit der eingesetzten und zu entwickelnden Systeme,\nModelle und Funktionalitäten bspw. als Open Source Software oder über\ngut dokumentierte API." },
    { id: "5", value1: 13, value2: 60, value3: 27, dimension: "Informationssicherheit & Datensouveränität", nameKurz: "Informationssicherheit", name: "Informationssicherheit & Datensouveränität", textLang: "Fragen der eingesetzten oder zu entwickelnden Sicherheits- und Schutz-\nmaßnahmen im Rahmen von Plattformen und Funktionalitäten im Sinne\nder gesetzlichen Anforderungen sowie darüber hinaus Fragen der Daten-\nethik und Selbstbestimmung im Umgang mit und bei der Ablage von\npersonenbezogenen Informationen." },
    { id: "6", value1: 34, value2: 27, value3: 39, dimension: "Weitere technologische Aspekte", nameKurz: "Weitere", name: "Weitere technologische Aspekte", textLang: "Weitere technologische Merkmale in den Vorhaben die nicht durch die\nanderen Dimensionen abgedeckt sind." },

];
var dataDimensionenStandZeitpunktB = dataDimensionenStandDezember2022; //Zeitpunkt B ist 2. auf slider und stellt Stand Dezember 2022 dar

var dataDimensionenStandAugust2023 = [
    { id: "1", value1: 18, value2: 32, value3: 50, dimension: "Interoperabilität durch offene Bildungstandards", nameKurz: "Interoperabilität", name: "Interoperabilität durch offene Bildungstandards", textLang: "Fragen der unterstützten Standards und Technologien zur Etablierung\neines gemeinsamen digitalen Weiterbildungsraumes, z. B. zu Kompe-\ntenzen und Wissen, sowie dem Austausch von Kurs-, Leistungs- oder\n Lernergebnissen und Lerninhalten." },
    { id: "2", value1: 43, value2: 22, value3: 35, dimension: "Algorithmen zur Unterstützung der Lernenden", nameKurz: "Algorithmen", name: "Algorithmen zur Unterstützung der Lernenden", textLang: "Fragen des Einsatzes und der Entwicklung von Algorithmen z.B. zur\nSprachverarbeitung (NLP, NLU, NLG), Analyse des Lernverhaltens\n(Learning Analytics) oder der Anpassungsfähigkeit von Lernangeboten\nund -empfehlungen sowie Suchfunktionen durch Nutzende." },
    { id: "3", value1: 9, value2: 28, value3: 63, dimension: "Mitgestaltung, Zugänglichkeit und Zusammenarbeit", nameKurz: "Mitgestaltung", name: "Mitgestaltung, Zugänglichkeit und Zusammenarbeit", textLang: "Spektrum der geplanten und umgesetzten Möglichkeiten der Beteiligung,\nZusammenarbeit und Mitgestaltung von Lerninhalten durch Nutzende\nsowie Lösungen zur Nutzbarkeit und zum Nutzungserlebnis." },
    { id: "4", value1: 24, value2: 30, value3: 46, dimension: "Nachnutzbarkeit durch Dritte", nameKurz: "Nachnutzbarkeit", name: "Nachnutzbarkeit durch Dritte", textLang: "Fragen der Offenheit der eingesetzten und zu entwickelnden Systeme,\nModelle und Funktionalitäten bspw. als Open Source Software oder über\ngut dokumentierte API." },
    { id: "5", value1: 14, value2: 58, value3: 28, dimension: "Informationssicherheit & Datensouveränität", nameKurz: "Informationssicherheit", name: "Informationssicherheit & Datensouveränität", textLang: "Fragen der eingesetzten oder zu entwickelnden Sicherheits- und Schutz-\nmaßnahmen im Rahmen von Plattformen und Funktionalitäten im Sinne\nder gesetzlichen Anforderungen sowie darüber hinaus Fragen der Daten-\nethik und Selbstbestimmung im Umgang mit und bei der Ablage von\npersonenbezogenen Informationen." },
    { id: "6", value1: 33, value2: 33, value3: 34, dimension: "Weitere technologische Aspekte", nameKurz: "Weitere", name: "Weitere technologische Aspekte", textLang: "Weitere technologische Merkmale in den Vorhaben die nicht durch die\nanderen Dimensionen abgedeckt sind." },

];
var dataDimensionenStandZeitpunktC = dataDimensionenStandAugust2023; // 3. Position auf Zeit slider

var dataDimensionen = dataDimensionenStandZeitpunktA;
var dataOhneLetzteDimension = dataDimensionen.slice(0, dataDimensionen.length - 1); //Für Initiale Anzeige Kopie des Datenarray aber ohne das letzte element= Dimension Sontiges

/// Daten für Beschreibung der Unterdimesionen, Prozent und absolut Werte der UnterDim sind jetzt in datensatz Einzeldimension

var dataBeschreibungUnterDimensionen = [ /// hier nur noch Text beschreibungen für die UDims, GesamtValues absolut und Prozent kommen aus Einzeldatensatz
    { dimension: "Digitale Ansätze zur Organisationsentwicklung", nameKurz: "Digitale Ansätze zur Organisationsentwicklung", name: "Digitale Ansätze zur Organisationsentwicklung", oberdimension: "Unterstützung von KMU beim Strukturwandel", textLang: "Begriffsverständnis\nDigitale Ansätze zur OE bezeichnen Ansätze, die KMU auf struktureller Ebene\nunterstützen, den digitalen Wandel zu meistern und Zugang zu Weiterbildungs-\nstrukturen und -plattformen erhalten. Besonders KMU verfügen oft nicht über\ndie betrieblichen Ressourcen für den Aufbau eigener Weiterbildungsstrukturen.\nLeitfragen\nWerden digitale Ansätze entwickelt, um den Zugang zu Weiterbildungsstrukturen\nund -plattformen für KMU zu erleichtern? Unterstützen diese Ansätze\nKMU ebenfalls auf struktureller Ebene?" },
    { dimension: "Personalentwicklung", nameKurz: "Personalentwicklung", name: "Personalentwicklung", oberdimension: "Unterstützung von KMU beim Strukturwandel", textLang: "Begriffsverständnis\nHier geht es darum, KMU bei der systematischen und strategischen Personal-\nentwicklung von Mitarbeitenden zu unterstützen.\nLeitfragen\nWerden KMU bei der individuellen Personalentwicklung ihrer Mitarbeitenden\nunterstützt? Gibt es digitale Ansätze zur Unterstützung bei der strategischen\nund systematischen Personalentwicklung in KMU?" },
    { dimension: "weitere Unterdimension", nameKurz: "weitere Unterdimension", name: "weitere Unterdimension", oberdimension: "Unterstützung von KMU beim Strukturwandel", textLang: "weitere Unterdimension" },
    { dimension: "Plattformvernetzung", nameKurz: "Plattformvernetzung", name: "Plattformvernetzung", oberdimension: "Digitale Ökosysteme", textLang: "Begriffsverständnis\nBei der Plattformvernetzung geht es um Aktivitäten zur Vernetzung bereits\nbestehender (Weiter-) Bildungsplattformen. Kriterien sind hier neben der\nAnzahl vernetzter WB-Plattformen ebenfalls die Größe und die jeweilige\nBedeutung der Plattformen für die berufliche Weiterbildung. \nLeitfrage\nWerden Plattformen miteinander vernetzt, um die Weiterbildungslandschaft\nübersichtlicher zu gestalten?" },
    { dimension: "Regionale Weiterbildungslandschaften", nameKurz: "Regionale Weiterbildungslandschaften", name: "Regionale Weiterbildungslandschaften", oberdimension: "Digitale Ökosysteme", textLang: "Begriffsverständnis\nRegionale Weiterbildungslandschaften fungieren als Treiber für Weiter-\nbildungsteilhabe und Professionsentwicklung. Zur Entwicklung einer \nkoordinierten (WB-)Anbieterstruktur sind gezielte Regionalentwicklung\n(Kooperation und Vernetzung auf organisationaler Ebene) und förderliche\ninstitutionelle Rahmenbedingungen notwendig.\nLeitfrage\nWerden regionale Weiterbildungsinitiativen bei der Vernetzung unterstützt\nund durch diese Vernetzung strukturentwickelnde regionale Weiterbildungs-\nlandschaften geschaffen?" },
    { dimension: "Digitaler, nationaler Bildungsraum", nameKurz: "Digitaler, nationaler Bildungsraum", name: "Digitaler, nationaler Bildungsraum", oberdimension: "Digitale Ökosysteme", textLang: "Begriffsverständnis\nIn einem „Digitalen Bildungsraum“ werden die Vermittlung, der Erwerb und\ndie Weiterentwicklung digitaler Kompetenzen in allen Bildungsbereichen und\nüber alle Bildungsphasen vernetzt. Kernelemente sind u.a. die sich im Aufbau\nbefindenden Plattformen NBP (Nationale Bildungsplattform; eine nutzer-\nzentrierte, anbieterneutrale Meta-Plattform) und NOW (Nationale Online-\nWeiterbildungsplattform).\nLeitfrage\nInwiefern tragen die Ergebnisse des Projektvorhabens dazu bei, den nationalen\n Bildungsraum zu erweitern? Finden Aktivitäten zur Anbindung an die sich im\nAufbau befindenden nationalen Plattformen NBP/NOW statt?" },
    { dimension: "Anreize für bisher nicht an der WB beteiligte Personengruppen", nameKurz: "Anreize für bisher nicht an der WB beteiligte Personengruppen", name: "Anreize für bisher nicht an der WB beteiligte Personengruppen", oberdimension: "Niedrigschwellige Zugangsmöglichkeiten", textLang: "Begriffsverständnis\nBisher nicht an der WB beteiligte Personen werden an den in der NWS\nentwickelten Leitlinien orientiert. Zu dieser Zielgruppe gehören u.a.\nNiedrigqualifizierte, Quereinsteiger*innen, Umschüler*innen, Lernende mit\nMigrationshintergrund, Migrant*innen, Beschäftigten mit niedrigerer\nBerufsqualifikation oder mit sprachlichen Barrieren, Menschen mit\nBehinderungen, Berufsrückkehrer*innen.\nLeitfrage\nWerden gezielte Anreize für bisher nicht an der Weiterbildung beteiligte\nZielgruppen geschaffen?" },
    { dimension: "Leichter Zugang und Barrierefreiheit", nameKurz: "Leichter Zugang und Barrierefreiheit", name: "Leichter Zugang und Barrierefreiheit", oberdimension: "Niedrigschwellige Zugangsmöglichkeiten", textLang: "Begriffsverständnis\nBarrierefreiheit bezeichnet den freien und uneingeschränkten Zugang aller\nMenschen zu Angeboten nach Leitlinien wie der BITV 2.0 und der WCAG. \nLeichter technischer Zugang muss nicht zwingend allen Vorgaben zu\nBarrierefreiheit entsprechen, muss allerdings den Zugang durch vereinfachte\ntechnische Möglichkeiten erleichtern.\nLeitfrage\nWerden die Angebote des Projekts entsprechend den Richtlinien der\nBarrierefreiheit zugänglich gemacht und/oder leichter technischer Zugang\ngewährt?" },
    { dimension: "Mehrsprachige (Bildungs-) Angebote", nameKurz: "Mehrsprachige (Bildungs-) Angebote", name: "Mehrsprachige (Bildungs-) Angebote", oberdimension: "Niedrigschwellige Zugangsmöglichkeiten", textLang: "Begriffsverständnis\nMehrsprachigkeit bezeichnet in diesem Zusammenhang die Übersetzung oder\ndie Ermöglichung von Übersetzungen von Bildungsangeboten in verschiedene\nSprachen (bspw. nicht nur auf eine Übersetzung in die englische Sprache). Der\nBezug zur gezielten Ansprache für bisher nicht an der WB beteiligte Personen-\ngruppen sollte erkennbar sein.\nLeitfrage\nWerden Weiterbildungsangebote für Zielgruppen mit unterschiedlichen\nMuttersprachen gezielt erreichbar gemacht?" },
    { dimension: "Orientierung an Kompetenzsystematiken", nameKurz: "Orientierung an Kompetenzsystematiken", name: "Orientierung an Kompetenzsystematiken", oberdimension: "Digitale Kompetenzvalidierung", textLang: "Begriffsverständnis\nEs wird auf bereits bestehende Kompetenzsystematiken zurückgegriffen\n(u.a. ESCO, DQR, EQR, OECD, HQR, Europass, Bloom‘schen Taxonomie, etc.).\nLeitfrage\nGibt es Kompetenzsystematiken, die der Projektarbeit zugrunde liegen?" },
    { dimension: "Weiter-Entwicklung von Kompetenzmodellen", nameKurz: "(Weiter-)Entwicklung von Kompetenzmodellen", name: "(Weiter-)Entwicklung von Kompetenzmodellen", oberdimension: "Digitale Kompetenzvalidierung", textLang: "Begriffsverständnis\nEs werden neue Kompetenzsystematiken weiterentwickelt (ggfs. Unter\nBerücksichtigung bereits bestehender Heuristiken).\nLeitfrage\nFindet eine Weiterentwicklung bereits bestehender Kompetenzsystematiken\nstatt?" },
    { dimension: "Erfassung informeller Kompetenzen", nameKurz: "Erfassung informeller Kompetenzen", name: "Erfassung informeller Kompetenzen", oberdimension: "Digitale Kompetenzvalidierung", textLang: "Begriffsverständnis\nInformelles Lernen findet außerhalb eines institutionellen Rahmens statt.\nEs bezeichnet das Lernen, das im Alltag, am Arbeitsplatz, im Familienkreis\noder in der Freizeit stattfindet. Es ist in Bezug auf Lernziele, Lernzeit oder\nLernförderung nicht organisiert oder strukturiert. Informelle Kompetenzen\nbezeichnet somit Fähigkeiten und Fertigkeiten, die außerhalb eines insti-\ntutionellen Rahmens angeeignet werden (ungleich non-formale Bildung).\nLeitfrage\nWerden informell erworbene Kompetenzen anerkannt und erfasst?" },
    { dimension: "Individualisierte Matching-Tools", nameKurz: "Individualisierte Matching-Tools", name: "Individualisierte Matching-Tools", oberdimension: "Personalisierung und Adaptivität", textLang: "Begriffsverständnis\nIndividualisierte Matching-Tools bezeichnen Tools zur technischen Vernetzung\nvon Lernenden und Weiterbildungsmöglichkeiten oder Lernelementen, oftmals\nunterstützt durch künstliche Intelligenz.\nLeitfrage\nWerden im Projekt neue Matching-Tools angewandt? " },
    { dimension: "Individualisierte Lernpfade", nameKurz: "Individualisierte Lernpfade", name: "Individualisierte Lernpfade", oberdimension: "Personalisierung und Adaptivität", textLang: "Begriffsverständnis\nEin Lernpfad wird zumeist in einer digitalen Lernumgebung durchlaufen, die mit\neiner Sequenz von aufeinander abgestimmten Schritten strukturierte Pfade durch\ninteraktive Materialien anbietet. Auf einem Lernpfad arbeiten Lernende handlungs-\norientiert, selbsttätig und eigenverantwortlich auf ein Ziel hin. Da die Schritte eine\nBausteinstruktur aufweisen, können die Lernenden jeweils für ihren Leistungsstand\ngeeignete Elemente auswählen. Eine adaptive Lernumgebung stellt verschiedene\nLernpfade durch die gesamten verfügbaren Lerninhalte bereit. Adaptive Lernpfade\npassen die Art der Wissensvermittlung an den Wissensstand, die Lernpräferenzen\nund das Umfeld des Lernenden an, um einen für alle Lernenden vergleichbaren\nLernerfolg zu erzielen.\nLeitfrage\nWerden im Projektverlauf neue individualisierte Lernpfade oder adaptive\nLernpfade entwickelt? " },
    { dimension: "Innovative Lernarrangements", nameKurz: "Innovative Lernarrangements", name: "Innovative Lernarrangements", oberdimension: "Personalisierung und Adaptivität", textLang: "Begriffsverständnis\nBei innovativen Lernarrangements handelt es sich um Lernarrangements, die einen\nneuen (technischen oder didaktischen) Ansatz zur Steigerung der Lernbeteiligung\nWeiterbildungsinteressierter oder Weiterbildungsferner Zielgruppen schaffen.\nLeitfrage\nWerden im Rahmen des Projektes neue technisch oder didaktisch innovative\nLernarrangements erschaffen, die einen höheren Anreiz zur Weiterbildung für die\njeweilige  Zielgruppen schaffen? " },

];

var dataUnterDimensionenEinzelStandAntrag = [ /// Array für Radarboard Unterdimensionen und Radarboard Einzelvorhaben zusammen, damit Daten an einer Stelle
    { id: "1", dimension: "Plattformvernetzung", value1: 38, valueProzentGesamt1: 38, value2: 18, valueProzentGesamt2: 18, value3: 44, valueProzentGesamt3: 44, valueGesamt1: 15, valueGesamt2: 6, valueGesamt3: 13, value1: 1, value2: 3, value3: 1, value4: 2, value5: 2, value6: 1, value7: 3, value8: 3, value9: 3, value10: 1, value11: 0, value12: 3, value13: 1, value14: 1, value15: 1, value16: 1, value17: 3, value18: 3, value19: 1, value20: 1, value21: 2, value22: 0, value23: 3, value24: 2, value25: 1, value26: 1, value27: 2, value28: 3, value29: 2, value30: 3, value31: 3, value32: 1, value33: 3, value34: 3 },
    { id: "2", dimension: "Regionale WB-Landschaften", value1: 8, valueProzentGesamt1: 8, value2: 24, valueProzentGesamt2: 24, value3: 68, valueProzentGesamt3: 68, valueGesamt1: 23, valueGesamt2: 8, valueGesamt3: 3, value1: 0, value2: 2, value3: 1, value4: 2, value5: 1, value6: 1, value7: 3, value8: 2, value9: 1, value10: 0, value11: 0, value12: 1, value13: 0, value14: 1, value15: 2, value16: 0, value17: 0, value18: 1, value19: 0, value20: 2, value21: 1, value22: 0, value23: 0, value24: 1, value25: 0, value26: 1, value27: 1, value28: 3, value29: 2, value30: 1, value31: 2, value32: 1, value33: 3, value34: 2 },
    { id: "3", dimension: "Nachhaltige Geschäftsmodelle", value1: 18, valueProzentGesamt1: 18, value2: 38, valueProzentGesamt2: 38, value3: 44, valueProzentGesamt3: 44, valueGesamt1: 15, valueGesamt2: 13, valueGesamt3: 6, value1: 1, value2: 2, value3: 1, value4: 0, value5: 2, value6: 3, value7: 2, value8: 1, value9: 2, value10: 1, value11: 0, value12: 1, value13: 2, value14: 2, value15: 2, value16: 1, value17: 1, value18: 1, value19: 3, value20: 1, value21: 3, value22: 3, value23: 3, value24: 2, value25: 1, value26: 2, value27: 2, value28: 1, value29: 1, value30: 2, value31: 2, value32: 1, value33: 3, value34: 2 },
    { id: "4", dimension: "Ansprache spezifischer Zielgruppen", value1: 38, valueProzentGesamt1: 38, value2: 21, valueProzentGesamt2: 21, value3: 41, valueProzentGesamt3: 41, valueGesamt1: 14, valueGesamt2: 7, valueGesamt3: 13, value1: 3, value2: 2, value3: 3, value4: 3, value5: 1, value6: 3, value7: 1, value8: 3, value9: 3, value10: 0, value11: 1, value12: 3, value13: 1, value14: 2, value15: 3, value16: 1, value17: 1, value18: 3, value19: 1, value20: 1, value21: 2, value22: 1, value23: 3, value24: 2, value25: 2, value26: 1, value27: 3, value28: 3, value29: 1, value30: 2, value31: 1, value32: 3, value33: 1, value34: 2 },
    { id: "5", dimension: "Barrierefreiheit", value1: 12, valueProzentGesamt1: 12, value2: 41, valueProzentGesamt2: 41, value3: 47, valueProzentGesamt3: 47, valueGesamt1: 16, valueGesamt2: 14, valueGesamt3: 4, value1: 1, value2: 3, value3: 0, value4: 2, value5: 1, value6: 2, value7: 1, value8: 3, value9: 3, value10: 2, value11: 1, value12: 1, value13: 2, value14: 2, value15: 1, value16: 2, value17: 2, value18: 1, value19: 3, value20: 2, value21: 1, value22: 1, value23: 2, value24: 2, value25: 2, value26: 1, value27: 1, value28: 2, value29: 2, value30: 1, value31: 1, value32: 1, value33: 1, value34: 2 },
    { id: "6", dimension: "Mehrsprachigkeit", value1: 9, valueProzentGesamt1: 9, value2: 9, valueProzentGesamt2: 9, value3: 82, valueProzentGesamt3: 82, valueGesamt1: 28, valueGesamt2: 3, valueGesamt3: 3, value1: 1, value2: 1, value3: 0, value4: 3, value5: 1, value6: 0, value7: 0, value8: 0, value9: 0, value10: 0, value11: 2, value12: 0, value13: 0, value14: 0, value15: 0, value16: 1, value17: 2, value18: 0, value19: 0, value20: 0, value21: 0, value22: 3, value23: 1, value24: 3, value25: 0, value26: 0, value27: 0, value28: 0, value29: 1, value30: 1, value31: 2, value32: 1, value33: 0, value34: 0 },
    { id: "7", dimension: "Bestehende Kompetenzmodelle", value1: 36, valueProzentGesamt1: 36, value2: 35, valueProzentGesamt2: 35, value3: 29, valueProzentGesamt3: 29, valueGesamt1: 10, valueGesamt2: 12, valueGesamt3: 12, value1: 3, value2: 3, value3: 1, value4: 2, value5: 2, value6: 1, value7: 3, value8: 2, value9: 1, value10: 0, value11: 1, value12: 3, value13: 3, value14: 1, value15: 3, value16: 3, value17: 2, value18: 3, value19: 2, value20: 2, value21: 1, value22: 3, value23: 2, value24: 3, value25: 1, value26: 2, value27: 2, value28: 0, value29: 0, value30: 2, value31: 2, value32: 3, value33: 2, value34: 3 },
    { id: "8", dimension: "Weiter-Entwicklung von Kompetenzmodellen", value1: 17, valueProzentGesamt1: 17, value2: 18, valueProzentGesamt2: 18, value3: 65, valueProzentGesamt3: 65, valueGesamt1: 22, valueGesamt2: 6, valueGesamt3: 6, value1: 3, value2: 2, value3: 1, value4: 0, value5: 2, value6: 0, value7: 1, value8: 1, value9: 0, value10: 0, value11: 1, value12: 3, value13: 1, value14: 1, value15: 1, value16: 2, value17: 1, value18: 2, value19: 1, value20: 1, value21: 1, value22: 1, value23: 1, value24: 3, value25: 2, value26: 1, value27: 0, value28: 0, value29: 0, value30: 3, value31: 2, value32: 3, value33: 1, value34: 3 },
    { id: "9", dimension: "Erfassung informeller Kompetenzen", value1: 15, valueProzentGesamt1: 15, value2: 26, valueProzentGesamt2: 26, value3: 59, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 9, valueGesamt3: 5, value1: 3, value2: 3, value3: 1, value4: 1, value5: 0, value6: 1, value7: 2, value8: 1, value9: 1, value10: 0, value11: 2, value12: 2, value13: 2, value14: 2, value15: 3, value16: 1, value17: 1, value18: 2, value19: 3, value20: 1, value21: 0, value22: 1, value23: 3, value24: 1, value25: 1, value26: 0, value27: 0, value28: 0, value29: 0, value30: 2, value31: 1, value32: 2, value33: 0, value34: 2 },
    { id: "10", dimension: "Innovative Lernarrangements", value1: 44, valueProzentGesamt1: 44, value2: 32, valueProzentGesamt2: 32, value3: 24, valueProzentGesamt3: 24, valueGesamt1: 8, valueGesamt2: 11, valueGesamt3: 15, value1: 3, value2: 2, value3: 3, value4: 3, value5: 2, value6: 3, value7: 3, value8: 2, value9: 1, value10: 2, value11: 3, value12: 2, value13: 1, value14: 3, value15: 1, value16: 2, value17: 3, value18: 3, value19: 3, value20: 3, value21: 1, value22: 1, value23: 1, value24: 3, value25: 1, value26: 2, value27: 3, value28: 2, value29: 2, value30: 3, value31: 2, value32: 3, value33: 2, value34: 0 },
    { id: "11", dimension: "Adaptive Lernpfade", value1: 55, valueProzentGesamt1: 55, value2: 21, valueProzentGesamt2: 21, value3: 24, valueProzentGesamt3: 24, valueGesamt1: 8, valueGesamt2: 7, valueGesamt3: 19, value1: 3, value2: 2, value3: 2, value4: 3, value5: 3, value6: 3, value7: 3, value8: 1, value9: 0, value10: 3, value11: 3, value12: 2, value13: 3, value14: 3, value15: 0, value16: 3, value17: 2, value18: 3, value19: 1, value20: 2, value21: 3, value22: 0, value23: 1, value24: 3, value25: 3, value26: 3, value27: 3, value28: 3, value29: 2, value30: 3, value31: 2, value32: 3, value33: 1, value34: 0 },
    { id: "12", dimension: "Recommendersysteme", value1: 61, valueProzentGesamt1: 61, value2: 21, valueProzentGesamt2: 21, value3: 18, valueProzentGesamt3: 18, valueGesamt1: 6, valueGesamt2: 7, valueGesamt3: 21, value1: 3, value2: 3, value3: 1, value4: 1, value5: 3, value6: 3, value7: 3, value8: 2, value9: 3, value10: 3, value11: 3, value12: 1, value13: 3, value14: 3, value15: 3, value16: 3, value17: 3, value18: 3, value19: 2, value20: 0, value21: 2, value22: 2, value23: 3, value24: 2, value25: 3, value26: 3, value27: 3, value28: 2, value29: 1, value30: 2, value31: 3, value32: 3, value33: 1, value34: 3 },
    { id: "13", dimension: "Einbindung relevanter Stakeholder", value1: 15, valueProzentGesamt1: 15, value2: 26, valueProzentGesamt2: 26, value3: 59, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 9, valueGesamt3: 5, value1: 1, value2: 0, value3: 1, value4: 0, value5: 2, value6: 0, value7: 0, value8: 1, value9: 1, value10: 0, value11: 1, value12: 3, value13: 0, value14: 2, value15: 2, value16: 1, value17: 1, value18: 1, value19: 2, value20: 2, value21: 2, value22: 0, value23: 3, value24: 3, value25: 1, value26: 2, value27: 0, value28: 3, value29: 1, value30: 2, value31: 2, value32: 1, value33: 3, value34: 1 },
    { id: "14", dimension: "Personalentwicklung", value1: 33, valueProzentGesamt1: 33, value2: 38, valueProzentGesamt2: 38, value3: 29, valueProzentGesamt3: 29, valueGesamt1: 10, valueGesamt2: 13, valueGesamt3: 11, value1: 3, value2: 2, value3: 1, value4: 3, value5: 3, value6: 1, value7: 0, value8: 2, value9: 1, value10: 2, value11: 2, value12: 2, value13: 0, value14: 3, value15: 1, value16: 3, value17: 2, value18: 0, value19: 3, value20: 2, value21: 1, value22: 3, value23: 3, value24: 2, value25: 2, value26: 1, value27: 2, value28: 3, value29: 0, value30: 2, value31: 2, value32: 3, value33: 3, value34: 2 },
    { id: "15", dimension: "Organisationsentwicklung", value1: 17, valueProzentGesamt1: 17, value2: 24, valueProzentGesamt2: 24, value3: 59, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 8, valueGesamt3: 6, value1: 2, value2: 1, value3: 1, value4: 3, value5: 3, value6: 2, value7: 2, value8: 1, value9: 1, value10: 1, value11: 1, value12: 1, value13: 0, value14: 1, value15: 1, value16: 3, value17: 2, value18: 0, value19: 3, value20: 2, value21: 0, value22: 1, value23: 3, value24: 2, value25: 2, value26: 1, value27: 1, value28: 2, value29: 0, value30: 1, value31: 1, value32: 3, value33: 1, value34: 1 },

];
var dataUnterDimensionenEinzelStandZeitpunktA = dataUnterDimensionenEinzelStandAntrag; //Datensatz Slider erste position (=links) 

var dataUnterDimensionenEinzelStandZB2021 = [ //Daten Array für Radarboard Einzelvorhaben
    { id: "1", dimension: "Plattformvernetzung", value1: 38, valueProzentGesamt1: 38, value2: 18, valueProzentGesamt2: 18, value3: 44, valueProzentGesamt3: 44, valueGesamt1: 15, valueGesamt2: 6, valueGesamt3: 13, value1: 1, value2: 3, value3: 1, value4: 2, value5: 2, value6: 1, value7: 3, value8: 3, value9: 3, value10: 1, value11: 0, value12: 3, value13: 1, value14: 1, value15: 1, value16: 1, value17: 3, value18: 3, value19: 1, value20: 1, value21: 2, value22: 0, value23: 3, value24: 2, value25: 1, value26: 1, value27: 2, value28: 3, value29: 2, value30: 3, value31: 3, value32: 1, value33: 3, value34: 3 },
    { id: "2", dimension: "Regionale WB-Landschaften", value1: 8, valueProzentGesamt1: 8, value2: 24, valueProzentGesamt2: 24, value3: 68, valueProzentGesamt3: 68, valueGesamt1: 23, valueGesamt2: 8, valueGesamt3: 3, value1: 0, value2: 2, value3: 1, value4: 2, value5: 1, value6: 1, value7: 3, value8: 2, value9: 1, value10: 0, value11: 0, value12: 1, value13: 0, value14: 1, value15: 2, value16: 0, value17: 0, value18: 1, value19: 0, value20: 2, value21: 1, value22: 0, value23: 0, value24: 1, value25: 0, value26: 1, value27: 1, value28: 3, value29: 2, value30: 1, value31: 2, value32: 1, value33: 3, value34: 2 },
    { id: "3", dimension: "Nachhaltige Geschäftsmodelle", value1: 18, valueProzentGesamt1: 18, value2: 38, valueProzentGesamt2: 38, value3: 44, valueProzentGesamt3: 44, valueGesamt1: 15, valueGesamt2: 13, valueGesamt3: 6, value1: 1, value2: 2, value3: 1, value4: 0, value5: 2, value6: 3, value7: 2, value8: 1, value9: 2, value10: 1, value11: 0, value12: 1, value13: 2, value14: 2, value15: 2, value16: 1, value17: 1, value18: 1, value19: 3, value20: 1, value21: 3, value22: 3, value23: 3, value24: 2, value25: 1, value26: 2, value27: 2, value28: 1, value29: 1, value30: 2, value31: 2, value32: 1, value33: 3, value34: 2 },
    { id: "4", dimension: "Ansprache spezifischer Zielgruppen", value1: 38, valueProzentGesamt1: 38, value2: 21, valueProzentGesamt2: 21, value3: 41, valueProzentGesamt3: 41, valueGesamt1: 14, valueGesamt2: 7, valueGesamt3: 13, value1: 3, value2: 2, value3: 3, value4: 3, value5: 1, value6: 3, value7: 1, value8: 3, value9: 3, value10: 0, value11: 1, value12: 3, value13: 1, value14: 2, value15: 3, value16: 1, value17: 1, value18: 3, value19: 1, value20: 1, value21: 2, value22: 1, value23: 3, value24: 2, value25: 2, value26: 1, value27: 3, value28: 3, value29: 1, value30: 2, value31: 1, value32: 3, value33: 1, value34: 2 },
    { id: "5", dimension: "Barrierefreiheit", value1: 12, valueProzentGesamt1: 12, value2: 41, valueProzentGesamt2: 41, value3: 47, valueProzentGesamt3: 47, valueGesamt1: 16, valueGesamt2: 14, valueGesamt3: 4, value1: 1, value2: 3, value3: 0, value4: 2, value5: 1, value6: 2, value7: 1, value8: 3, value9: 3, value10: 2, value11: 1, value12: 1, value13: 2, value14: 2, value15: 1, value16: 2, value17: 2, value18: 1, value19: 3, value20: 2, value21: 1, value22: 1, value23: 2, value24: 2, value25: 2, value26: 1, value27: 1, value28: 2, value29: 2, value30: 1, value31: 1, value32: 1, value33: 1, value34: 2 },
    { id: "6", dimension: "Mehrsprachigkeit", value1: 9, valueProzentGesamt1: 9, value2: 9, valueProzentGesamt2: 9, value3: 82, valueProzentGesamt3: 82, valueGesamt1: 28, valueGesamt2: 3, valueGesamt3: 3, value1: 1, value2: 1, value3: 0, value4: 3, value5: 1, value6: 0, value7: 0, value8: 0, value9: 0, value10: 0, value11: 2, value12: 0, value13: 0, value14: 0, value15: 0, value16: 1, value17: 2, value18: 0, value19: 0, value20: 0, value21: 0, value22: 3, value23: 1, value24: 3, value25: 0, value26: 0, value27: 0, value28: 0, value29: 1, value30: 1, value31: 2, value32: 1, value33: 0, value34: 0 },
    { id: "7", dimension: "Bestehende Kompetenzmodelle", value1: 36, valueProzentGesamt1: 36, value2: 35, valueProzentGesamt2: 35, value3: 29, valueProzentGesamt3: 29, valueGesamt1: 10, valueGesamt2: 12, valueGesamt3: 12, value1: 3, value2: 3, value3: 1, value4: 2, value5: 2, value6: 1, value7: 3, value8: 2, value9: 1, value10: 0, value11: 1, value12: 3, value13: 3, value14: 1, value15: 3, value16: 3, value17: 2, value18: 3, value19: 2, value20: 2, value21: 1, value22: 3, value23: 2, value24: 3, value25: 1, value26: 2, value27: 2, value28: 0, value29: 0, value30: 2, value31: 2, value32: 3, value33: 2, value34: 3 },
    { id: "8", dimension: "Weiter-Entwicklung von Kompetenzmodellen", value1: 17, valueProzentGesamt1: 17, value2: 18, valueProzentGesamt2: 18, value3: 65, valueProzentGesamt3: 65, valueGesamt1: 22, valueGesamt2: 6, valueGesamt3: 6, value1: 3, value2: 2, value3: 1, value4: 0, value5: 2, value6: 0, value7: 1, value8: 1, value9: 0, value10: 0, value11: 1, value12: 3, value13: 1, value14: 1, value15: 1, value16: 2, value17: 1, value18: 2, value19: 1, value20: 1, value21: 1, value22: 1, value23: 1, value24: 3, value25: 2, value26: 1, value27: 0, value28: 0, value29: 0, value30: 3, value31: 2, value32: 3, value33: 1, value34: 3 },
    { id: "9", dimension: "Erfassung informeller Kompetenzen", value1: 15, valueProzentGesamt1: 15, value2: 26, valueProzentGesamt2: 26, value3: 59, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 9, valueGesamt3: 5, value1: 3, value2: 3, value3: 1, value4: 1, value5: 0, value6: 1, value7: 2, value8: 1, value9: 1, value10: 0, value11: 2, value12: 2, value13: 2, value14: 2, value15: 3, value16: 1, value17: 1, value18: 2, value19: 3, value20: 1, value21: 0, value22: 1, value23: 3, value24: 1, value25: 1, value26: 0, value27: 0, value28: 0, value29: 0, value30: 2, value31: 1, value32: 2, value33: 0, value34: 2 },
    { id: "10", dimension: "Innovative Lernarrangements", value1: 44, valueProzentGesamt1: 44, value2: 32, valueProzentGesamt2: 32, value3: 24, valueProzentGesamt3: 24, valueGesamt1: 8, valueGesamt2: 11, valueGesamt3: 15, value1: 3, value2: 2, value3: 3, value4: 3, value5: 2, value6: 3, value7: 3, value8: 2, value9: 1, value10: 2, value11: 3, value12: 2, value13: 1, value14: 3, value15: 1, value16: 2, value17: 3, value18: 3, value19: 3, value20: 3, value21: 1, value22: 1, value23: 1, value24: 3, value25: 1, value26: 2, value27: 3, value28: 2, value29: 2, value30: 3, value31: 2, value32: 3, value33: 2, value34: 0 },
    { id: "11", dimension: "Adaptive Lernpfade", value1: 55, valueProzentGesamt1: 55, value2: 21, valueProzentGesamt2: 21, value3: 24, valueProzentGesamt3: 24, valueGesamt1: 8, valueGesamt2: 7, valueGesamt3: 19, value1: 3, value2: 2, value3: 2, value4: 3, value5: 3, value6: 3, value7: 3, value8: 1, value9: 0, value10: 3, value11: 3, value12: 2, value13: 3, value14: 3, value15: 0, value16: 3, value17: 2, value18: 3, value19: 1, value20: 2, value21: 3, value22: 0, value23: 1, value24: 3, value25: 3, value26: 3, value27: 3, value28: 3, value29: 2, value30: 3, value31: 2, value32: 3, value33: 1, value34: 0 },
    { id: "12", dimension: "Recommendersysteme", value1: 61, valueProzentGesamt1: 61, value2: 21, valueProzentGesamt2: 21, value3: 18, valueProzentGesamt3: 18, valueGesamt1: 6, valueGesamt2: 7, valueGesamt3: 21, value1: 3, value2: 3, value3: 1, value4: 1, value5: 3, value6: 3, value7: 3, value8: 2, value9: 3, value10: 3, value11: 3, value12: 1, value13: 3, value14: 3, value15: 3, value16: 3, value17: 3, value18: 3, value19: 2, value20: 0, value21: 2, value22: 2, value23: 3, value24: 2, value25: 3, value26: 3, value27: 3, value28: 2, value29: 1, value30: 2, value31: 3, value32: 3, value33: 1, value34: 3 },
    { id: "13", dimension: "Einbindung relevanter Stakeholder", value1: 15, valueProzentGesamt1: 15, value2: 26, valueProzentGesamt2: 26, value3: 59, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 9, valueGesamt3: 5, value1: 1, value2: 0, value3: 1, value4: 0, value5: 2, value6: 0, value7: 0, value8: 1, value9: 1, value10: 0, value11: 1, value12: 3, value13: 0, value14: 2, value15: 2, value16: 1, value17: 1, value18: 1, value19: 2, value20: 2, value21: 2, value22: 0, value23: 3, value24: 3, value25: 1, value26: 2, value27: 0, value28: 3, value29: 1, value30: 2, value31: 2, value32: 1, value33: 3, value34: 1 },
    { id: "14", dimension: "Personalentwicklung", value1: 33, valueProzentGesamt1: 33, value2: 38, valueProzentGesamt2: 38, value3: 29, valueProzentGesamt3: 29, valueGesamt1: 10, valueGesamt2: 13, valueGesamt3: 11, value1: 3, value2: 2, value3: 1, value4: 3, value5: 3, value6: 1, value7: 0, value8: 2, value9: 1, value10: 2, value11: 2, value12: 2, value13: 0, value14: 3, value15: 1, value16: 3, value17: 2, value18: 0, value19: 3, value20: 2, value21: 1, value22: 3, value23: 3, value24: 2, value25: 2, value26: 1, value27: 2, value28: 3, value29: 0, value30: 2, value31: 2, value32: 3, value33: 3, value34: 2 },
    { id: "15", dimension: "Organisationsentwicklung", value1: 17, valueProzentGesamt1: 17, value2: 24, valueProzentGesamt2: 24, value3: 59, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 8, valueGesamt3: 6, value1: 2, value2: 1, value3: 1, value4: 3, value5: 3, value6: 2, value7: 2, value8: 1, value9: 1, value10: 1, value11: 1, value12: 1, value13: 0, value14: 1, value15: 1, value16: 3, value17: 2, value18: 0, value19: 3, value20: 2, value21: 0, value22: 1, value23: 3, value24: 2, value25: 2, value26: 1, value27: 1, value28: 2, value29: 0, value30: 1, value31: 1, value32: 3, value33: 1, value34: 1 },

];
var dataUnterDimensionenEinzelStandZeitpunktB = dataUnterDimensionenEinzelStandZB2021; //Datensatz Slider 2. position (=mitte) 

var dataUnterDimensionenEinzelStandTagung2022 = [ //Daten Array für Radarboard Einzelvorhaben
    { id: "1", dimension: "Plattformvernetzung", value1: 38, valueProzentGesamt1: 38, value2: 18, valueProzentGesamt2: 18, value3: 44, valueProzentGesamt3: 44, valueGesamt1: 15, valueGesamt2: 6, valueGesamt3: 13, value1: 1, value2: 3, value3: 1, value4: 2, value5: 2, value6: 1, value7: 3, value8: 3, value9: 3, value10: 1, value11: 0, value12: 3, value13: 1, value14: 1, value15: 1, value16: 1, value17: 3, value18: 3, value19: 1, value20: 1, value21: 2, value22: 0, value23: 3, value24: 2, value25: 1, value26: 1, value27: 2, value28: 3, value29: 2, value30: 3, value31: 3, value32: 1, value33: 3, value34: 3 },
    { id: "2", dimension: "Regionale WB-Landschaften", value1: 8, valueProzentGesamt1: 8, value2: 24, valueProzentGesamt2: 24, value3: 68, valueProzentGesamt3: 68, valueGesamt1: 23, valueGesamt2: 8, valueGesamt3: 3, value1: 0, value2: 2, value3: 1, value4: 2, value5: 1, value6: 1, value7: 3, value8: 2, value9: 1, value10: 0, value11: 0, value12: 1, value13: 0, value14: 1, value15: 2, value16: 0, value17: 0, value18: 1, value19: 0, value20: 2, value21: 1, value22: 0, value23: 0, value24: 1, value25: 0, value26: 1, value27: 1, value28: 3, value29: 2, value30: 1, value31: 2, value32: 1, value33: 3, value34: 2 },
    { id: "3", dimension: "Nachhaltige Geschäftsmodelle", value1: 18, valueProzentGesamt1: 18, value2: 38, valueProzentGesamt2: 38, value3: 44, valueProzentGesamt3: 44, valueGesamt1: 15, valueGesamt2: 13, valueGesamt3: 6, value1: 1, value2: 2, value3: 1, value4: 0, value5: 2, value6: 3, value7: 2, value8: 1, value9: 2, value10: 1, value11: 0, value12: 1, value13: 2, value14: 2, value15: 2, value16: 1, value17: 1, value18: 1, value19: 3, value20: 1, value21: 3, value22: 3, value23: 3, value24: 2, value25: 1, value26: 2, value27: 2, value28: 1, value29: 1, value30: 2, value31: 2, value32: 1, value33: 3, value34: 2 },
    { id: "4", dimension: "Ansprache spezifischer Zielgruppen", value1: 38, valueProzentGesamt1: 38, value2: 21, valueProzentGesamt2: 21, value3: 41, valueProzentGesamt3: 41, valueGesamt1: 14, valueGesamt2: 7, valueGesamt3: 13, value1: 3, value2: 2, value3: 3, value4: 3, value5: 1, value6: 3, value7: 1, value8: 3, value9: 3, value10: 0, value11: 1, value12: 3, value13: 1, value14: 2, value15: 3, value16: 1, value17: 1, value18: 3, value19: 1, value20: 1, value21: 2, value22: 1, value23: 3, value24: 2, value25: 2, value26: 1, value27: 3, value28: 3, value29: 1, value30: 2, value31: 1, value32: 3, value33: 1, value34: 2 },
    { id: "5", dimension: "Barrierefreiheit", value1: 12, valueProzentGesamt1: 12, value2: 41, valueProzentGesamt2: 41, value3: 47, valueProzentGesamt3: 47, valueGesamt1: 16, valueGesamt2: 14, valueGesamt3: 4, value1: 1, value2: 3, value3: 0, value4: 2, value5: 1, value6: 2, value7: 1, value8: 3, value9: 3, value10: 2, value11: 1, value12: 1, value13: 2, value14: 2, value15: 1, value16: 2, value17: 2, value18: 1, value19: 3, value20: 2, value21: 1, value22: 1, value23: 2, value24: 2, value25: 2, value26: 1, value27: 1, value28: 2, value29: 2, value30: 1, value31: 1, value32: 1, value33: 1, value34: 2 },
    { id: "6", dimension: "Mehrsprachigkeit", value1: 9, valueProzentGesamt1: 9, value2: 9, valueProzentGesamt2: 9, value3: 82, valueProzentGesamt3: 82, valueGesamt1: 28, valueGesamt2: 3, valueGesamt3: 3, value1: 1, value2: 1, value3: 0, value4: 3, value5: 1, value6: 0, value7: 0, value8: 0, value9: 0, value10: 0, value11: 2, value12: 0, value13: 0, value14: 0, value15: 0, value16: 1, value17: 2, value18: 0, value19: 0, value20: 0, value21: 0, value22: 3, value23: 1, value24: 3, value25: 0, value26: 0, value27: 0, value28: 0, value29: 1, value30: 1, value31: 2, value32: 1, value33: 0, value34: 0 },
    { id: "7", dimension: "Bestehende Kompetenzmodelle", value1: 36, valueProzentGesamt1: 36, value2: 35, valueProzentGesamt2: 35, value3: 29, valueProzentGesamt3: 29, valueGesamt1: 10, valueGesamt2: 12, valueGesamt3: 12, value1: 3, value2: 3, value3: 1, value4: 2, value5: 2, value6: 1, value7: 3, value8: 2, value9: 1, value10: 0, value11: 1, value12: 3, value13: 3, value14: 1, value15: 3, value16: 3, value17: 2, value18: 3, value19: 2, value20: 2, value21: 1, value22: 3, value23: 2, value24: 3, value25: 1, value26: 2, value27: 2, value28: 0, value29: 0, value30: 2, value31: 2, value32: 3, value33: 2, value34: 3 },
    { id: "8", dimension: "Weiter-Entwicklung von Kompetenzmodellen", value1: 17, valueProzentGesamt1: 17, value2: 18, valueProzentGesamt2: 18, value3: 65, valueProzentGesamt3: 65, valueGesamt1: 22, valueGesamt2: 6, valueGesamt3: 6, value1: 3, value2: 2, value3: 1, value4: 0, value5: 2, value6: 0, value7: 1, value8: 1, value9: 0, value10: 0, value11: 1, value12: 3, value13: 1, value14: 1, value15: 1, value16: 2, value17: 1, value18: 2, value19: 1, value20: 1, value21: 1, value22: 1, value23: 1, value24: 3, value25: 2, value26: 1, value27: 0, value28: 0, value29: 0, value30: 3, value31: 2, value32: 3, value33: 1, value34: 3 },
    { id: "9", dimension: "Erfassung informeller Kompetenzen", value1: 15, valueProzentGesamt1: 15, value2: 26, valueProzentGesamt2: 26, value3: 59, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 9, valueGesamt3: 5, value1: 3, value2: 3, value3: 1, value4: 1, value5: 0, value6: 1, value7: 2, value8: 1, value9: 1, value10: 0, value11: 2, value12: 2, value13: 2, value14: 2, value15: 3, value16: 1, value17: 1, value18: 2, value19: 3, value20: 1, value21: 0, value22: 1, value23: 3, value24: 1, value25: 1, value26: 0, value27: 0, value28: 0, value29: 0, value30: 2, value31: 1, value32: 2, value33: 0, value34: 2 },
    { id: "10", dimension: "Innovative Lernarrangements", value1: 44, valueProzentGesamt1: 44, value2: 32, valueProzentGesamt2: 32, value3: 24, valueProzentGesamt3: 24, valueGesamt1: 8, valueGesamt2: 11, valueGesamt3: 15, value1: 3, value2: 2, value3: 3, value4: 3, value5: 2, value6: 3, value7: 3, value8: 2, value9: 1, value10: 2, value11: 3, value12: 2, value13: 1, value14: 3, value15: 1, value16: 2, value17: 3, value18: 3, value19: 3, value20: 3, value21: 1, value22: 1, value23: 1, value24: 3, value25: 1, value26: 2, value27: 3, value28: 2, value29: 2, value30: 3, value31: 2, value32: 3, value33: 2, value34: 0 },
    { id: "11", dimension: "Adaptive Lernpfade", value1: 55, valueProzentGesamt1: 55, value2: 21, valueProzentGesamt2: 21, value3: 24, valueProzentGesamt3: 24, valueGesamt1: 8, valueGesamt2: 7, valueGesamt3: 19, value1: 3, value2: 2, value3: 2, value4: 3, value5: 3, value6: 3, value7: 3, value8: 1, value9: 0, value10: 3, value11: 3, value12: 2, value13: 3, value14: 3, value15: 0, value16: 3, value17: 2, value18: 3, value19: 1, value20: 2, value21: 3, value22: 0, value23: 1, value24: 3, value25: 3, value26: 3, value27: 3, value28: 3, value29: 2, value30: 3, value31: 2, value32: 3, value33: 1, value34: 0 },
    { id: "12", dimension: "Recommendersysteme", value1: 61, valueProzentGesamt1: 61, value2: 21, valueProzentGesamt2: 21, value3: 18, valueProzentGesamt3: 18, valueGesamt1: 6, valueGesamt2: 7, valueGesamt3: 21, value1: 3, value2: 3, value3: 1, value4: 1, value5: 3, value6: 3, value7: 3, value8: 2, value9: 3, value10: 3, value11: 3, value12: 1, value13: 3, value14: 3, value15: 3, value16: 3, value17: 3, value18: 3, value19: 2, value20: 0, value21: 2, value22: 2, value23: 3, value24: 2, value25: 3, value26: 3, value27: 3, value28: 2, value29: 1, value30: 2, value31: 3, value32: 3, value33: 1, value34: 3 },
    { id: "13", dimension: "Einbindung relevanter Stakeholder", value1: 15, valueProzentGesamt1: 15, value2: 26, valueProzentGesamt2: 26, value3: 59, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 9, valueGesamt3: 5, value1: 1, value2: 0, value3: 1, value4: 0, value5: 2, value6: 0, value7: 0, value8: 1, value9: 1, value10: 0, value11: 1, value12: 3, value13: 0, value14: 2, value15: 2, value16: 1, value17: 1, value18: 1, value19: 2, value20: 2, value21: 2, value22: 0, value23: 3, value24: 3, value25: 1, value26: 2, value27: 0, value28: 3, value29: 1, value30: 2, value31: 2, value32: 1, value33: 3, value34: 1 },
    { id: "14", dimension: "Personalentwicklung", value1: 33, valueProzentGesamt1: 33, value2: 38, valueProzentGesamt2: 38, value3: 29, valueProzentGesamt3: 29, valueGesamt1: 10, valueGesamt2: 13, valueGesamt3: 11, value1: 3, value2: 2, value3: 1, value4: 3, value5: 3, value6: 1, value7: 0, value8: 2, value9: 1, value10: 2, value11: 2, value12: 2, value13: 0, value14: 3, value15: 1, value16: 3, value17: 2, value18: 0, value19: 3, value20: 2, value21: 1, value22: 3, value23: 3, value24: 2, value25: 2, value26: 1, value27: 2, value28: 3, value29: 0, value30: 2, value31: 2, value32: 3, value33: 3, value34: 2 },
    { id: "15", dimension: "Organisationsentwicklung", value1: 17, valueProzentGesamt1: 17, value2: 24, valueProzentGesamt2: 24, value3: 59, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 8, valueGesamt3: 6, value1: 2, value2: 1, value3: 1, value4: 3, value5: 3, value6: 2, value7: 2, value8: 1, value9: 1, value10: 1, value11: 1, value12: 1, value13: 0, value14: 1, value15: 1, value16: 3, value17: 2, value18: 0, value19: 3, value20: 2, value21: 0, value22: 1, value23: 3, value24: 2, value25: 2, value26: 1, value27: 1, value28: 2, value29: 0, value30: 1, value31: 1, value32: 3, value33: 1, value34: 1 },

];
var dataUnterDimensionenEinzelStandZeitpunktC = dataUnterDimensionenEinzelStandTagung2022; //Datensatz Slider 3. position (=rechts) 


//var dataUnterDimensionenEinzel = dataUnterDimensionenEinzelStandZB2021; ///aktuellen Datensatz auf den letzten Stand setzen, dieser ist dann der inital angezeigte Datensatz
var dataUnterDimensionenEinzel = dataUnterDimensionenEinzelStandAntrag; /// slider steht zu Beginn auf StandAntrag
var dataUnterDimensionen = dataUnterDimensionenEinzel; //values nur noch in Einzelarray enthalten

var dataUnterDimensionenEinzelTexte = [ ///Daten Array für Texte jedes Einzel-Radarboards
    { id: "1", name: "ADAPT", entwicklungsfeld: "3", thema: "Adaptives Weiterbildungsunter-\nstützungssystem im Berufsfeld Pflege", branche: "Pflege", schwerpunkte: "KI-basiertes adaptives Weiterbildungs-unterstützungssystem, bild- und videobasiert, Gamification, Qualifikations-Dashboard, Lernreminder, Reduktion subjektiver Lernwiderstände, personalisierte Lernpfade und Userprofile", technologischeZiel: "Lern-Dashboard erfasst Kompetenz und Lernanforderung, NLP-basiertes Matching mit Arbeitsmarktdaten, Web, YouTube und OER, Django/React, Oauth, NLTK", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "2", name: "APOLLO", entwicklungsfeld: "2, 3", thema: ": KI-basierte, plattformübergreifende Companion-App für lebenslange Lern-Optimierung", branche: "übergreifend", schwerpunkte: "KI-basierte Personalisierung und Empfehlungssystem", technologischeZiel: "Cross-Plattform-App, NLP zur Analyse von Qualifikationsunterlagen, Einsatz von Klassifizierungssystemen zur Einschätzung von Kompetenzen, graph-basierter Ansatz zur Verknüpfung von Bestandsdaten, Wissensgraph und Link Prediction zur Generierung von Empfehlungen, MLOps Infrastruktur, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "3", name: "ComP-ASS", entwicklungsfeld: "3", thema: "Computergestütztes Lernen und Lehren im Handwerk mit interaktiven Assistenzsystemen", branche: "Handwerk", schwerpunkte: "digitalgestütztes Weiterbildungsangebot zur Vermittlung von CNC-Kompetenzen für das Handwerk, Simulationen von Materialänderungen, interaktive VR/AR-basierte „CNC-Maschinen-Welt“, Gamification-Elemente, interaktives didaktisches Assistenzsystem", technologischeZiel: "AR/VR Maschinenwelt, Plugin für ILIAS, regelbasierter didaktischer Assistent für Autoren von Lehrinhalten im Handwerk", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "4", name: "DigiPlat4Train", entwicklungsfeld: "1,2,3", thema: "Automatisierte, datenbasierte Rückschlüsse aus der praktischen Arbeit an Fertigungsmaschinen", branche: "Kunststofffertigung", schwerpunkte: "virtueller Produktionsassistent, KI, Kunststofftechnologie, DSGVO, KI mit Fehlercodes, Training direkt an Produktionsmaschine, Abstimmung mit Betriebsrat und Mitarbeitenden", technologischeZiel: "VIPRA erfasst Trainings- und Arbeitsdaten an Maschine, KI bietet Kurse und Micro-Lerneinheiten von Weiterbildungsplattform anhand erkannter Lerndefizite an", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "5", name: "EduPLEx_API", entwicklungsfeld: "2 (untergeordnet 3) ", thema: "Erweiterung einer bestehenden Learning Experience Plattform (LXP) um eine Schnittstelle zu einem KI-basierten Empfehlungssystem bzw. einem Lern-Nachweis-System um eine Mandaten-Fähigkeit der Plattform für die Anwendbarkeit für KMU", branche: "übergreifend, Fokus liegt KMU", schwerpunkte: "Empfehlungsmaschine, Marktplatz, adaptives Lernkonzept (selbstgesteuertes Lernen mit homogenen Inhalten, Trainer-gestütztes Lernen mit heterogenen Lernmaterialien und kollaboratives Arbeiten), Suchen / Sprachmodell (semantische Netze) zur Identifikation von Inhalten", technologischeZiel: "Interoperabilität, Integration von Zusatzdiensten", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "6", name: "ELe-com", entwicklungsfeld: "2,3", thema: "Empowering Learning – Ermöglichung adaptiven Lernens in der beruflichen Weiterbildung am Beispiel des E-Commerce ", branche: "Handel", schwerpunkte: "Individuelles Lernen über die Berücksichtigung von Lernpräferenzen durch den Einsatz  von adaptiven Lernwegen, adaptiven Lernformaten in Form von Micro Learning Einheiten und Empfehlungen durch KI Assistenzsysteme anhand des Themas Customer Journey im E-Commerce.", technologischeZiel: "KI-unterstütztes Assistenzsystem aus zwei Tools: Lernnavigator (LENA) und Entscheidungsmodul (EMIL), Weiterentwicklung myFlexNet.de (ILIAS-Plattform)", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "7", name: "ExpanderWB3", entwicklungsfeld: "2,3", thema: "Vernetzung der „Weiterbildungsdatenbank Suchportal in Berlin und Brandenburg“ mit weiteren Plattformen und KI-gestützte Empfehlung von Inhalten für die berufliche Weiterbildung", branche: "übergreifend, Fokus auf Branchen der industriellen Verarbeitung", schwerpunkte: "Nutzendenzentrierte Individualisierung von beruflichen Lernangeboten mit Bezug zu unternehmens- und arbeitsmarktpolitischen Erfolgsmerkmalen", technologischeZiel: "Entwicklung von interoperablen Standards und Schnittstellen; Begriffs-Klassifikationen und Ontologien; Integration eines Gamification Ansatzes; Implementierung einer semantischen Suche; User-Profile und E-Portfolios auf Kompetenz­basis; Learning Analytics, Lernempfehlungen und Lernpfade", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "8", name: "HUBGrade", entwicklungsfeld: "1,2,3", thema: "Entwicklung eines bundesweiten Weiterbildungs-portals des Handwerks", branche: "Handwerk", schwerpunkte: "Vernetzung bestehender Weiterbildungsplattformen, Weiterbildungsangebote, Verwaltungssysteme und Lernmanagementsysteme der handwerklichen Bildungsanbietenden mit intelligenter Suchfunktion und Single-Sign-On", technologischeZiel: "API-Entwicklung für Weiterbildungsplattformen (ODAV AG, UNIPLUS und B & E), SSO, Learning Record Store mit E-Portfolio, Digitale Zertifikate (EUROPASS und ProNet-Handwerk), intelligente Suche mit Chatbot (Framework Chatterbox)", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "9", name: "IWWB-PLUS", entwicklungsfeld: "2", thema: "Personalisierte Lernumgebung und Suche ", branche: "übergeordnet", schwerpunkte: "Implementierung von dialogischen Technologien, Light Assessments und Interoperabilität mit externen Informationsanbietern", technologischeZiel: "Schaffung von personalisierten Suchfunktionen mit einem Chatbot, Empfehlungsmaschine, Natural Language Processing", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "10", name: "KAINE", entwicklungsfeld: "3", thema: "Steigerung der Effizienz, Effektivität und Nachhaltigkeit des Lernens auf Weiterbildungsplattformen durch smarte, individuelle Lernmaterialbereitstellung und dialogorientiertem Tutoringsystem", branche: "produzierendes Gewerbe", schwerpunkte: "Lernassistenzsystem mit individuellen Learning Journeys, individuelle Lernverlaufsbegleitung durch ein dialogorientiertes Tutorsystem, KI-basierte adaptive Erstellung von individuellen Lernpfaden, Voice- und Chatbot basiertes Lerntutoringsystem", technologischeZiel: "KI-basierte Lernpfade, Voice- und Chatbot, LMS Plugin (moodle), Ontologien", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "11", name: "KAMAELEON", entwicklungsfeld: "3", thema: "Kontextbasierte und adaptive Maßnahmen für effektive Lernunterstützung in der Online-Weiterbildung", branche: "übergreifend (Weiterbildungsangebote im Bereich Digitalisierung, Daten- und Projektmanagement)", schwerpunkte: "KI-basierte Personalisierungskonzepte,  Integration innerer und äußerer Lernfaktoren, die den Lernerfolg beeinflussen", technologischeZiel: "ML-basierte Personalisierung und Adaption von Lerninhalten, Integration in bestehende AWS Cloudplattform, Serverless Architektur, GraphQL, NoSQL DB, Angular, Snowflake Datwarehouse", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "12", name: "KI4CoLearnET", entwicklungsfeld: "1,2,3", thema: "KI für kompetenzbasiertes Lernen im Cluster Energietechnik", branche: "Energietechnik", schwerpunkte: "Serious Games mit Schwierigkeitsanpassung und adaptiven Lernpfaden", technologischeZiel: "Baukastensystem für Serious Games, KI zur Schwierigkeitsanpassung", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "13", name: "KIM", entwicklungsfeld: "2", thema: "Künstliche Intelligenz als Mentoring-Lösung für lebenslanges Lernen", branche: "übergreifend", schwerpunkte: "verzahntes bzw. rückgekoppeltes System, welches auf Basis der erkannten Trends und vorhandener Kompetenzen eine Prognose geeigneter Lerneinheiten liefert", technologischeZiel: "CV Extraktion, adaptive Lernpfade, Trenderkennung", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "14", name: "KIPerWeb", entwicklungsfeld: "2,3", thema: "KI-gestützte Personalisierung in der berufsbezogenen Weiterbildung", branche: "übergreifend", schwerpunkte: "Verbesserung unterschiedlicher Plattformen, Synergien durch gemeinsame Arbeit", technologischeZiel: "Adaptive Lernpfade und personalisierte Kursempfehlungen (Empfehlungssysteme)", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "15", name: "KIRA", entwicklungsfeld: "2,3", thema: "KI-gestütztes Matching individueller und arbeitsmarktbezogener Anforderungen für die berufliche Weiterbildung", branche: "übergreifend, Fokus auf IT-Qualifikationen in transformationsintensiven Branchen", schwerpunkte: "Nutzendenzentrierte Individualisierung von beruflichen Lernangeboten mit Bezug zu unternehmens- und arbeitsmarktpolitischen Erfolgsmerkmalen", technologischeZiel: "Modellierung von Lernformen, -bedarfen und -erfolgen; Empfehlungen von Lerninhalten für Lernende; Entwicklung von KI-Service-Modulen; Reporting über Optimierungsmöglichkeiten für Plattformbetreiber:innen (am Beispiel WBS TRAINING AG)", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "16", name: "KIRA_Pro", entwicklungsfeld: "3", thema: "KI-basierter Rollennavigator und automatisierte Lernpfadermittlung zur beruflichen Weiterbildung im produzierenden Gewerbe", branche: "Produzierendes Gewerbe", schwerpunkte: "Identifikation von am besten geeigneten Mitarbeiter:innen für Weiterbildungen in Trendthemen der digitalen Transformation unter Berücksichtigung der Unternehmensziele.", technologischeZiel: "Kompetenzerfassung, Pfadsuche auf Kompetenzgraph", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "17", name: "KIWI", entwicklungsfeld: "2 (untergeordnet 3)", thema: "Anwendung bzw. Bereitstellung von AR/VR-basierten Lerninhalten auf Smartphones im Bereich „Cobots“ und die KI-gestützte Identifikation von Lernpräferenzen bzw. passgenaue Bereitstellung von Lerninhalten", branche: "Maschinenbau (kollaborative Robotik)", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, VR/AR, mobile und VR-Equipment, personalisierte Lernpfade und Userprofile", technologischeZiel: "strenge Trennung zwischen Content (Unreal Engine) und Kubernetes Container (Flutter für native Apps, Python / TensorFlow, mlflow für KI / Microservice-spezifische DBs (MongoDB, Postgresql, Minio) / Keycloak für ID / Spring Boot für Backend)", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "18", name: "KUPPEL", entwicklungsfeld: "3", thema: "KI-unterstützte plattformübergreifende Professionalisierung erwachsenen-pädagogischer Lehrkräfte", branche: "übergreifend, Fokus auf die digitalen Kompetenzen Lehrender", schwerpunkte: "Zusammenführung von Angeboten zweier existierender Plattformen, Ergänzung um Adaptivität und Zertifikate", technologischeZiel: "Lernbereiche vhs-DTrain (vhs cloud) und EULE (wb-Web) verbinden, cloudbasiertes Multiagentensystem, Lernvorschläge, Kollaboration, Fälschungs- und identitätssichere Zertifikate", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "19", name: "LIMo", entwicklungsfeld: "2", thema: "Unterstützung der Durchführung und Management betrieblicher Weiterbildung, um vermitteltes Wissen bedarfsgerecht zur Verfügung zu stellen und neue Lernangebote zu schaffen", branche: "Industrie", schwerpunkte: "Sicher & mobil, informell & partizipativ, individuell & unterstützt", technologischeZiel: "Empfehlungssystem", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "20", name: "LiSiL", entwicklungsfeld: "3", thema: "Smarte Lernwelten im Sozialwesen – innovative digitale Lernräume für die hybride Vermittlung sensibler Weiterbildungsthemen", branche: "Sozialwesen", schwerpunkte: "Neue Konzepte für die Vermittlung von sensiblen Themen, Erkennung dysfunktionaler emotionaler Belastung im digitalen Raum", technologischeZiel: "Sentiment Analyse aus Nutzerverhalten zur Bestimmung dysfunktionaler emotionaler Belastung", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "21", name: "MINDED_RUHR", entwicklungsfeld: "1,3", thema: "Aufbau eines offenen Systems von digitalen, KI-gestützten Weiterbildungsangeboten verschiedener Plattformen und Formaten der DHAR und Vernetzung mit Moodle.", branche: "Gesundheitswesen, Pflege am Beispiel der Demenz", schwerpunkte: "Anbieter- und plattformübergreifende Bereitstellung von Bildungsinhalten, Schnittstellenentwicklung", technologischeZiel: "Verknüpfung von Moodle-Plattformen mit Tutoolio zum Pooling von Content, KI-unterstützte, bedarfsorientierte Bereitstellung von Lerninhalten", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "22", name: "MyEduLife", entwicklungsfeld: "2", thema: "Die Blockchain als Werkzeug zur dezentralen Speicherung individueller Weiterbildungsbiographien, Entwicklung und Erprobung von Werkzeugen zur Bearbeitung und Präsentation von Qualifikationsportfolios", branche: "übergreifend", schwerpunkte: "Standardisierung von Bildungserwerben, Blockchain für Bildungserwerbsdokumentation", technologischeZiel: "Blockchain mit Second Layer", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "23", name: "NetOEV", entwicklungsfeld: "1,2", thema: "Plattformvernetzung für personalisierte Weiterbildung und kooperativen Wissensaustausch in der Mobilitätsbranche", branche: "Mobilitätsbranche", schwerpunkte: "kooperativer Wissensaustausch, formelle und informelle Weiterbildung, Sichtbarkeit von Expertise, nutzerzentrierte Lernerfahrung", technologischeZiel: "Vernetzung vieler Plattformen durch Schnittstellen mit übergreifender Auswertung, um bessere Lerninhalte durch Recommender System zu empfehlen und Expertise branchenweit sichtbar zu machen", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "24", name: "OnCaPflege", entwicklungsfeld: "2,3", thema: "Entwicklung und Erprobung einer digitalen Plattform für den spezifischen Zielbereich der beruflichen Pflege mit adaptiven Lernpfaden", branche: "Pflege", schwerpunkte: "Qualitative Verbesserung bestehender Weiterbildungsplattformen durch digitale Lehr- und Lernformen sowie die Untersuchung von Weiterbildungsbeteiligung und -verhalten", technologischeZiel: "KI-unterstützte Lehr- und Lernangebote (Recommender- und Unterstützungssysteme; Kompetenzerfassung und -verarbeitung; Verbindung von Learning Nuggets und Metadaten; Motivations-Bot; KI-unterstützte Simultanübersetzung; Badges und Zertifikate mittels Zertifikats-Blockchain; Berücksichtigung von Datenethik-Standards", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "25", name: "PolyEx", entwicklungsfeld: "1,2,3", thema: "Polymer-Excellence - Weiterbildungsplattform für die kunststoffverarbeitende Industrie", branche: "kunststoffverarbeitende Industrie", schwerpunkte: "effiziente Filter- und Sortierungsfunktionen, Personal Learning Environment, adaptives Lernen durch KI-basiertes Empfehlungssystem mit einem Chatbot als Weiterbildungsassistenten, Kompetenzmatrix, Integration von Lernformaten", technologischeZiel: "Lehrinhalte entweder nativ über Online-Formular, Upload (JSON-Datei), Webscrapers oder API, persönliche Lernumgebung (Personal Learning Environment – PLE), KI-basiertes Empfehlungssystem und Weiterbildungsassistent mit Natural Language Processing (NLP), Kompetenzmatrix", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "26", name: "SEARCH", entwicklungsfeld: "2,3", thema: "Entwicklung eines KI-gestützten Assistenzsystems zum adaptiven Lernen und Ausbau der Lernplattform MLS für die bedarfsgerechte Weiterbildung", branche: "übergreifend, Fokus auf das produzierende Gewerbe", schwerpunkte: ": Pädagogisch-didaktisch und technologische Aufbereitung von Lerninhalten sowie Aufzeigen von individuellen und flexibel anpassbaren Lerneinheiten und Lernpfade für Lernende", technologischeZiel: "Anreicherung und Strukturierung von Informationen; Komposition von Lernpfaden; Integration eines KI-gestützten Assistenzsystems; Einbinden von Methoden zur Spracherkennung sowie zur text- und sprachorientierten Videoanalyse; Entwicklung einer Suchfunktion zur intelligenten Suche", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "27", name: "SG4BB", entwicklungsfeld: "1,2,3", thema: "Serious Games für die berufliche Bildung", branche: "übergreifend", schwerpunkte: "KI-gestützte spielerische Lehr- und Lernangebote, „Steam“ für Serious Games, Metadaten-orientierte Suchmaschine, neuer Metadatenstandard ", technologischeZiel: "Verknüpfung von Learning Record Store, LMS, Marktplatz, Suchmaschine und Serious Games, Anbindung von Drittanbietern", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "28", name: "SMALO", entwicklungsfeld: "1,2,3", thema: "Smartes Lernen in der Logistik", branche: "Logistik", schwerpunkte: "KI für erhöhte Beteiligung, bessere Kohärenz und Personalisierung, Vernetzung, Bedarfsorientierung, Zertifizierung, Lern-Ökosystem, Datensicherheit (DSGVO, BSI)", technologischeZiel: "KI für Beteiligung, Kohärenz und Personalisierung, datensicherer Weiterbildungsraum, Überarbeitung der Plattformarchitektur ", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "29", name: "StuBu", entwicklungsfeld: "3", thema: "StudyBuddy: Ein virtueller Companion für die berufliche Weiterbildung", branche: "übergreifend", schwerpunkte: "KI-basierter Funktionsbaukasten für einen virtuellen Companion in der beruflichen Weiterbildung. Erkennung von Lernpräferenzen und Eingehen auf individuelles Lernverhalten.", technologischeZiel: "ML-basierter virtueller Companion, Anbindung an Bot Engine, automatische ML-basierte Lern-Persönlichkeitsanalyse, Nutzung von NPL, NLU und NLG. Node.js, Mongo DB, Rest API, RASA", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "30", name: "TRIPLEADAPT", entwicklungsfeld: "1,2,3", thema: "Adaptive, interoperationale Weiterbildungsplattformen durch einen digitalen Drilling", branche: "übergreifend", schwerpunkte: "Adaptiver Drilling, Adaptive Lernpfade, plattformübergreifende Lernpfade, Adaptive Assistenz in arbeitsplatzähnlicher Umgebung, Common Learning Middleware (CLM), Micro-Zertifikate", technologischeZiel: "Erstellung von KI-Diensten auf Basis Low Code Mendix Plattform für Lernen in der digitalen Produktion, Nutzung von Simulationen und Prozessdaten des digitalen Zwillings", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "31", name: "VerDatAs", entwicklungsfeld: "1,2,3", thema: "Vernetzung und datengestützte Assistenz für die berufliche Bildung", branche: "übergreifend", schwerpunkte: "Plattformvernetzung zu digitalem Marktplatz, Unterstützung von Lehrenden und Lernenden, innovativer Weiterbildungsraum für Informatiker, Ingenieure und qualifizierte Quereinsteiger, pädagogisch-psychologisches Ordnungssystem, Qualifikations-Matching", technologischeZiel: "LMS ILIAS zur Plattformvernetzung, Aufbau eines Learning Record Store, nutzerzentrierte KI für variantenreiche Szenarien beruflicher und betrieblicher Bildung, Entwicklung eines tutoriellen Assistenzsystems", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "32", name: "Wbsmart", entwicklungsfeld: "3", thema: "Bildungswissenschaftliche Grundlegung eines smarten KI-basierten digitalen Weiterbildungsraums für die Altenhilfe mittels personalisierter Empfehlungs-systeme", branche: "Pflege", schwerpunkte: "KI-basiertes, personalisiertes Empfehlungssystem, intelligente Aufbereitung und Empfehlung von Lernangeboten auf adaptiven Lernpfaden, basierend auf individueller Präferenz, Lernfortschritt, Kenntnisstand und auf einem Wissens-modell als Wissensgraph, intelligentes tutorielles Assistenzsystem, Einbeziehung vorhandener OER Ressourcen", technologischeZiel: "semantischer Wissensgraph, White-Box KI, Recommender System", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "33", name: "Weiterbildung 4.OWL", entwicklungsfeld: "2,3", thema: "Entwicklung eines didaktischen und technisch-wirtschaftlichen Instrumentariums zur nutzer- und qualitätszentrierten Verbesserung von intermediären Marktplatz- und Lernplattformen", branche: "übergreifend, Fokus produzierendes Gewerbe", schwerpunkte: "Nutzerorientierte Gestaltung des digitalen Lernens und der Kompetenzentwicklung; Technisch-wirtschaftliche Gestaltung des plattformbasierten Weiterbildungsraums", technologischeZiel: "Tools zur Erfassung strukturierter Bildungsangebotsanfragen und zur Erstellung qualitätsorientierter Lernangebote, Anbindung der Tools an LMS und Spezifikation von Schnittstellen, Kollaborative Bearbeitung von Anfragen & Designs, Anbindung der Tools an übergreifende Matching-Plattform, Rahmenwerk für einzuhaltende Sicherh.-Stand.", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "34", name: "WISYatKI", entwicklungsfeld: "1,2", thema: "WISY@KI-Dein persönlicher Weiterbildungsscout", branche: "übergreifend", schwerpunkte: "Verbesserung der Suche von regionalen Weiterbildungsangeboten / Kursen insbesondere hinsichtlich der Treffgenauigkeit zu den eigenen Kompetenzen / Weiterbildungszielen. Entwicklung und Integration einer kompetenzorientierten Suchfunktion in die WISY-Kursportale in Schleswig-Holstein und Hessen zur Optimierung der Kursergebnisse.", technologischeZiel: "Entwicklung der Kursportale Schleswig-Holstein und Hessen mittels Einsatz von kompetenzorientierten Empfehlungssystemen zur Verbesserung der persönlichen Suchergebnisse.", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },

];

//#endregion ///-----C END Set Data----------------------------------------------------------------------------------------------

