//#region ///--------C Set Data------------------------------------------------------------------------------------------------

var dataUnterDimensionenEinzelTexte = [ ///Daten Array für Texte jedes Einzel-Radarboards

{id:"1", name: "CuC", entwicklungsfeld: "0", thema: "Lizenzen für Digitale Bildungsmedien einfach und rechtssicher verwalten", zielgruppe: " ", innovation: "Das Verbundprojekt Control und Connect (CuC) will das reibungslose Zusammenspiel von Schulverwaltungs- und Lernmanagementsystemen mit Anbietern für digitale Bildungsmedien fördern. Hierfür wird ein vermittelndes Programm, eine sogenannte Middleware, entwickelt. Mit ihrer Hilfe können Lizenzen effizient verwaltet und zugewiesen werden. So können digitale Bildungsmedien einfach, bruchlos und rechtssicher in vielfältigen Systemen und Anwendungen genutzt werden. Dabei werden die Prinzipien der Datensouveränität, Herstelleroffenheit und Vielfalt berücksichtigt.", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/cuc-lizenzen-fuer-digitale-bildungsmedien-einfach-und-rechtssicher-verwalten", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"2", name: "NELE", entwicklungsfeld: "0", thema: "Digitale Qualifizierungsangebote zur Weiterbildung von Pädagoginnen und Pädagogen an Schulen", zielgruppe: " ", innovation: "Das NELE-Projekt trägt den Vernetzungsgedanken von “Mein Bildungsraum” in die Fortbildungspraxis. Rund um das Thema “Neue Lernkultur” schafft NELE eine bundeslandübergreifende, offen zugängliche Fortbildungs-Plattform für Lehrkräfte und Schulleitungen aller Schulformen sowie für viele weitere im Ökosystem Schule engagierte Personen. Die E-Learning-Angebote sollen das Rollenverständnis der Zielgruppe erweitern, da Lern- und Lehransätze fokussiert werden, die die Lernenden und ihre Bedürfnisse in den Mittelpunkt des Lernprozesses stellen. Hierfür werden Inhalte von wissenschaftlichen, gemeinnützigen und wirtschaftlichen Organisationen angeboten. Das Ziel von NELE ist es, als zentraler und vernetzender Verteilungskanal zum Thema “Neue Lernkultur” spannende Angebote, Projektergebnisse und OER-Inhalte bereitzustellen.", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/nele-ehem-lnl2-digitale-qualifizierungsangebote-fuer-eine-neue-bildung", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"3", name: "KUKOBINA", entwicklungsfeld: "0", thema: "Kindgerechte Bildungsangebote, die formale und non-formale Bildung miteinander verbinden", zielgruppe: " ", innovation: " Ziel des Verbundprojekts KUCOBINA ist es, Unterricht und außerunterrichtliche Bildungsarbeit miteinander zu verknüpfen, um eine nahtlose Lernerfahrung für Kinder zu ermöglichen. Hierfür werden im Projekt digitale Lerninhalte kuratiert, didaktisch entwickelt und als Themenpakete für pädagogische Fachkräfte in Ganztagsschulen und der außerschulischen Bildungsarbeit bereitgestellt.", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/kucobina-kindgerechte-bildungsangebote-die-schule-und-nachmittagsbetreuung-besser-verbinden", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"4", name: "Projekt-3", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"5", name: "Projekt-4", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"6", name: "Projekt-5", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"7", name: "Projekt-6", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"8", name: "Projekt-7", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"9", name: "Projekt-8", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"10", name: "Projekt-9", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"11", name: "Projekt-10", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"12", name: "Projekt-11", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"13", name: "Projekt-12", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"14", name: "Projekt-13", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"15", name: "Projekt-14", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"16", name: "Projekt-15", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"17", name: "Projekt-16", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"18", name: "Projekt-17", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"19", name: "Projekt-18", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"20", name: "Projekt-19", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"21", name: "Projekt-20", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"22", name: "Projekt-21", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"23", name: "Projekt-22", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"24", name: "Projekt-23", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"25", name: "Projekt-24", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"26", name: "Projekt-25", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"27", name: "Projekt-26", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"28", name: "Projekt-27", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"29", name: "Projekt-28", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"30", name: "Projekt-29", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"31", name: "Projekt-30", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"32", name: "Projekt-31", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"33", name: "Projekt-32", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},
{id:"34", name: "Projekt-XX", entwicklungsfeld: "0", thema: " ", zielgruppe: " ", innovation: " ", weiterbildungsplattform: "www.meinbildungsraum.de/vorhaben/foerderprojekte-und-partner/aktuelle-foerderprojekte/", branche: " ", projektzieleschwerpunkte: " ", technologischesziel: " ", mehrwert: " ", verbundpartner: " "},

];


