//#region ///--------C Set Data------------------------------------------------------------------------------------------------
var projekteNamen = ['ADAPT', 'APOLLO', 'ComP-ASS', 'DigiPlat4Train', 'EduPLEx_API', 'ELe-com', 'ExpanderWB3', 'HUBGrade', 'IWWB-PLUS', 'KAINE', 'KAMAELEON', 'KI4CoLearnET', 'KIM', 'KIPerWeb', 'KIRA', 'KIRA_Pro', 'KIWI', 'KUPPEL', 'LIMo', 'LiSiL', 'MINDED_RUHR', 'MyEduLife', 'NetOEV', 'OnCaPflege', 'PolyEx', 'SEARCH', 'SG4BB', 'SMALO', 'StuBu', 'TRIPLEADAPT', 'VerDatAs', 'WBsmart', 'Weiterb.4.OWL', 'WISYatKI'];
var projekteAuspraegung = ['Dim k.A.', 'Dim in Ansätzen.', 'Dim adressiert.', 'Dim ausgepr.'];


/// Zustand welche Projekte gerade in Einzeplorjektanzeige an sind
var projekteEinzelStatusInLegende = Array(projekteNamen.length).fill(0);
//console.log("projekteEinzelStatusInLegende:" + projekteEinzelStatusInLegende);

/// daten und Beschreibung der Oberdimensionen 
var dataDimensionenStandAntrag = [
    { id: 1, value1: 18, value2: 15, value3: 67, dimension: "Digitale Ökosysteme", nameKurz: "Digitale Ökosysteme", name: "Digitale Ökosysteme", textLang: "Leistet das betrachtete Projekt einen Beitrag zur Transparenz in der\nWeiterbildungslandschaft durch regionale Vernetzung zu digitalen\nÖko- bzw. Bildungssystemen?" },
    { id: 2, value1: 18, value2: 23, value3: 59, dimension: "Niedrigschwellige Zugangsmöglichkeiten", nameKurz: "Niedrigschwellige Zugangsmöglichkeiten", name: "Niedrigschwellige Zugangsmöglichkeiten", textLang: "Leisten Projektentwicklungen einen Beitrag zur Erhöhung der Weiter\nbildungs-Beteiligung durch niedrigschwellige Zugangsmöglichkeiten?" },
    { id: 3, value1: 26, value2: 14, value3: 60, dimension: "Digitale Kompetenzvalidierung", nameKurz: "Digitale Kompetenzvalidierung", name: "Digitale Kompetenzvalidierung", textLang: "Wird ein Beitrag zur digitalen Kompetenzvalidierung sowie –erfassung\ndurch die Orientierung an bestehenden Kompetenzsystematiken, der\n(Weiter-) Entwicklung von Kompetenzmodellen oder der Erfassung \ninformeller Kompetenzen erbracht?" },
    { id: 4, value1: 45, value2: 33, value3: 22, dimension: "Personalisierung und Adaptivität", nameKurz: "Personalisierung und Adaptivität", name: "Personalisierung und Adaptivität", textLang: "Gibt es einen Beitrag zur Erhöhung der Qualität durch Personalisierung\nund Adaptivität?" },
    { id: 5, value1: 10, value2: 16, value3: 74, dimension: "Unterstützung von KMU beim Strukturwandel", nameKurz: "Unterstützung von KMU beim Strukturwandel", name: "Unterstützung von KMU beim Strukturwandel", textLang: "Wird ein Beitrag zur Strukturentwicklung durch die Unterstützung von\nKMUs durch Agile Management Tools geleistet?" },
    { id: 6, value1: 30, value2: 40, value3: 30, dimension: "Sonstige Aspekte", nameKurz: "Sonstige", name: "Sonstige Aspekte", textLang: "Weitere inhaltliche Merkmale in den Vorhaben die nicht durch die\nanderen Dimensionen abgedeckt sind." },

];
var dataDimensionenStandZeitpunktA = dataDimensionenStandAntrag; //Zeitpunkt A ist 1. auf slider

var dataDimensionenStandDezember2022 = [
    { id: "1", value1: 19, value2: 27, value3: 54, dimension: "Digitale Ökosysteme", nameKurz: "Digitale Ökosysteme", name: "Digitale Ökosysteme", textLang: "Leistet das betrachtete Projekt einen Beitrag zur Transparenz in der\nWeiterbildungslandschaft durch regionale Vernetzung zu digitalen\nÖko- bzw. Bildungssystemen?" },
    { id: "2", value1: 20, value2: 25, value3: 55, dimension: "Niedrigschwellige Zugangsmöglichkeiten", nameKurz: "Niedrigschwellige Zugangsmöglichkeiten", name: "Niedrigschwellige Zugangsmöglichkeiten", textLang: "Leisten Projektentwicklungen einen Beitrag zur Erhöhung der Weiter\nbildungs-Beteiligung durch niedrigschwellige Zugangsmöglichkeiten?" },
    { id: "3", value1: 23, value2: 30, value3: 47, dimension: "Digitale Kompetenzvalidierung", nameKurz: "Digitale Kompetenzvalidierung", name: "Digitale Kompetenzvalidierung", textLang: "Wird ein Beitrag zur digitalen Kompetenzvalidierung sowie –erfassung\ndurch die Orientierung an bestehenden Kompetenzsystematiken, der\n(Weiter-) Entwicklung von Kompetenzmodellen oder der Erfassung \ninformeller Kompetenzen erbracht?" },
    { id: "4", value1: 54, value2: 25, value3: 21, dimension: "Personalisierung und Adaptivität", nameKurz: "Personalisierung und Adaptivität", name: "Personalisierung und Adaptivität", textLang: "Gibt es einen Beitrag zur Erhöhung der Qualität durch Personalisierung\nund Adaptivität?" },
    { id: "5", value1: 22, value2: 26, value3: 52, dimension: "Unterstützung von KMU beim Strukturwandel", nameKurz: "Unterstützung von KMU beim Strukturwandel", name: "Unterstützung von KMU beim Strukturwandel", textLang: "Wird ein Beitrag zur Strukturentwicklung durch die Unterstützung von\nKMUs durch Agile Management Tools geleistet?" },
    { id: "6", value1: 34, value2: 27, value3: 39, dimension: "Sonstige Aspekte", nameKurz: "Sonstige", name: "Sonstige Aspekte", textLang: "Weitere inhaltliche Merkmale in den Vorhaben die nicht durch die\nanderen Dimensionen abgedeckt sind." },

];
var dataDimensionenStandZeitpunktB = dataDimensionenStandDezember2022; //Zeitpunkt B ist 2. auf slider und stellt Stand Dezember 2022 dar

var dataDimensionenStandAugust2023 = [
    { id: "1", value1: 22, value2: 26, value3: 52, dimension: "Digitale Ökosysteme", nameKurz: "Digitale Ökosysteme", name: "Digitale Ökosysteme", textLang: "Leistet das betrachtete Projekt einen Beitrag zur Transparenz in der\nWeiterbildungslandschaft durch regionale Vernetzung zu digitalen\nÖko- bzw. Bildungssystemen?" },
    { id: "2", value1: 20, value2: 23, value3: 57, dimension: "Niedrigschwellige Zugangsmöglichkeiten", nameKurz: "Niedrigschwellige Zugangsmöglichkeiten", name: "Niedrigschwellige Zugangsmöglichkeiten", textLang: "Leisten Projektentwicklungen einen Beitrag zur Erhöhung der Weiter\nbildungs-Beteiligung durch niedrigschwellige Zugangsmöglichkeiten?" },
    { id: "3", value1: 23, value2: 26, value3: 51, dimension: "Digitale Kompetenzvalidierung", nameKurz: "Digitale Kompetenzvalidierung", name: "Digitale Kompetenzvalidierung", textLang: "Wird ein Beitrag zur digitalen Kompetenzvalidierung sowie –erfassung\ndurch die Orientierung an bestehenden Kompetenzsystematiken, der\n(Weiter-) Entwicklung von Kompetenzmodellen oder der Erfassung \ninformeller Kompetenzen erbracht?" },
    { id: "4", value1: 54, value2: 25, value3: 21, dimension: "Personalisierung und Adaptivität", nameKurz: "Personalisierung und Adaptivität", name: "Personalisierung und Adaptivität", textLang: "Gibt es einen Beitrag zur Erhöhung der Qualität durch Personalisierung\nund Adaptivität?" },
    { id: "5", value1: 22, value2: 29, value3: 49, dimension: "Unterstützung von KMU beim Strukturwandel", nameKurz: "Unterstützung von KMU beim Strukturwandel", name: "Unterstützung von KMU beim Strukturwandel", textLang: "Wird ein Beitrag zur Strukturentwicklung durch die Unterstützung von\nKMUs durch Agile Management Tools geleistet?" },
    { id: "6", value1: 33, value2: 33, value3: 34, dimension: "Sonstige Aspekte", nameKurz: "Sonstige", name: "Sonstige Aspekte", textLang: "Weitere inhaltliche Merkmale in den Vorhaben die nicht durch die\nanderen Dimensionen abgedeckt sind." },

];
var dataDimensionenStandZeitpunktC = dataDimensionenStandAugust2023; // 3. Position auf Zeit slider

var dataDimensionen = dataDimensionenStandZeitpunktA;
var dataOhneLetzteDimension = dataDimensionen.slice(0, dataDimensionen.length - 1); //Für Initiale Anzeige Kopie des Datenarray aber ohne das letzte element= Dimension Sontiges

/// Daten für Beschreibung der Unterdimesionen, Prozent und absolut Werte der UnterDim sind jetzt in datensatz Einzeldimension

var dataBeschreibungUnterDimensionen = [ /// hier nur noch Text beschreibungen für die UDims, GesamtValues absolut und Prozent kommen aus Einzeldatensatz
    { dimension: "Plattformvernetzung", nameKurz: "Plattformvernetzung", name: "Plattformvernetzung", oberdimension: "Digitale Ökosysteme", textLang: "Werden Plattformen miteinander vernetzt, um die Weiterbildungslandschaft\nübersichtlicher zu gestalten/Transparenz zu schaffen? Ist eine grundsätzliche\nAnschlussfähigkeit durch Interoperabilität gegeben? Gehen die Vernetzungs-\ninitiativen über einzelne Branchen und/oder den nationalen Kontext hinaus?" },
    { dimension: "Regionale WB-Landschaften", nameKurz: "WB-Landschaften", name: "Regionale WB-Landschaften", oberdimension: "Digitale Ökosysteme", textLang: "Werden regionale Weiterbildungsinitiativen bei der Vernetzung unterstützt\nund durch diese Vernetzung strukturentwickelnde regionale Weiterbildungs-\nlandschaften geschaffen?" },
    { dimension: "Nachhaltige Geschäftsmodelle", nameKurz: "Nachhaltige Geschäftsm.", name: "Nachhaltige Geschäftsmodelle", oberdimension: "Digitale Ökosysteme", textLang: "Gibt es konkrete Überlegungen zu betriebswirtschaftlichen Geschäfts-\nmodellen, die einen nachhaltigen Betrieb der im Projekt entwickelnden\nLösungen sicherstellen? Werden Aktivitäten zur Sicherung potentieller\nAnschlussfähigkeit und zur Möglichkeit der Nachnutzung durch Dritte\nmitgedacht und durchgeführt?" },
    { dimension: "Ansprache spezifischer Zielgruppen", nameKurz: "Zielgruppen", name: "Ansprache spezifischer Zielgruppen", oberdimension: "Niedrigschwellige Zugangsmöglichkeiten", textLang: "Wird ein strategischer Ansatz verfolgt, um konkret Anreize für bisher nicht an\nder Weiterbildung beteiligte Zielgruppen zur Beteiligung an Weiterbildung\nzu schaffen? Gibt es konkrete Kommunikationsstrategien zur Ansprache der\ngenannten Zielgruppe?" },
    { dimension: "Barrierefreiheit", nameKurz: "Barrierefreiheit", name: "Barrierefreiheit", oberdimension: "Niedrigschwellige Zugangsmöglichkeiten", textLang: "Werden die Angebote des Projekts entsprechend den Richtlinien der\nBarrierefreiheit, die über gängige Standards hinausgehen, zugänglich\ngemacht? Wird ein niedrigschwelliger Zugang zu Angeboten gewährt?" },
    { dimension: "Mehrsprachigkeit", nameKurz: "Mehrsprachigkeit", name: "Mehrsprachigkeit", oberdimension: "Niedrigschwellige Zugangsmöglichkeiten", textLang: "Wird der Aspekt der Mehrsprachigkeit berücksichtigt und in der Entwicklung\nvon (Weiter-) Bildungsangeboten mitgedacht? Werden Weiterbildungs-\nangebote für Zielgruppen mit unterschiedlichen Muttersprachen gezielt\nerreichbar gemacht?" },
    { dimension: "Bestehende Kompetenzmodelle", nameKurz: "Kompetenzmodelle", name: "Bestehende Kompetenzmodelle", oberdimension: "Digitale Kompetenzvalidierung", textLang: "Wird grundsätzlich auf bereits bestehende Kompetenzmodelle zurück-\ngegriffen? Werden bestehende Modelle konkret eingebunden?" },
    { dimension: "Weiter-Entwicklung von Kompetenzmodellen", nameKurz: "Entw. Kompetenzmodelle", name: "Weiter-Entwicklung von Kompetenzmodellen", oberdimension: "Digitale Kompetenzvalidierung", textLang: "Ist die Weiterentwicklung von Kompetenzmodellen vorgesehen? Finde\nkonkrete Maßnahmen zur Weiterentwicklung bereits bestehender\nKompetenzmodelle statt?" },
    { dimension: "Erfassung informeller Kompetenzen", nameKurz: "Erfassung inf. Kompet.", name: "Erfassung informeller Kompetenzen", oberdimension: "Digitale Kompetenzvalidierung", textLang: "Wird das Thema der Anerkennung informeller Kompetenzen aufgegriffen/\nberücksichtigt? Inwieweit werden Lösungen zur Anerkennung informell\nerworbener Kompetenzen entwickelt und eingebunden?" },
    { dimension: "Innovative Lernarrangements", nameKurz: "Lernarrangements", name: "Innovative Lernarrangements", oberdimension: "Personalisierung und Adaptivität", textLang: "Werden im Rahmen des Projektes neue technisch oder didaktisch innovative\nLernarrangements entwickelt, die einen höheren Anreiz zur Weiterbildung\nfür die jeweilige Zielgruppen schaffen?" },
    { dimension: "Adaptive Lernpfade", nameKurz: "Adaptive Lernpfade", name: "Adaptive Lernpfade", oberdimension: "Personalisierung und Adaptivität", textLang: "Werden im Projektverlauf neue adaptive Lernpfade entwickelt?" },
    { dimension: "Recommendersysteme", nameKurz: "Recommendersyst.", name: "Recommendersysteme", oberdimension: "Personalisierung und Adaptivität", textLang: "Werden Recommendersysteme mitgedacht, entwickelt und/oder eingesetzt,\num Nutzer:innen personalisiert zu passenden Angeboten zu führen? Gehen\ndiese Systeme über eine bloße Filterfunktion hinaus?" },
    { dimension: "Einbindung relevanter Stakeholder", nameKurz: "Einbindung Stakeholder", name: "Einbindung relevanter Stakeholder", oberdimension: "Unterstützung von KMU beim Strukturwandel", textLang: "Werden relevante Stakeholder beispielsweise als Multiplikatoren für\nMU/Betriebe eingebunden? Welche relevanten Stakeholder werden\neingebunden?" },
    { dimension: "Personalentwicklung", nameKurz: "Personalentwicklung", name: "Personalentwicklung", oberdimension: "Unterstützung von KMU beim Strukturwandel", textLang: "Werden KMU bei der individuellen Personalentwicklung ihrer Mitarbeiten-\nden unterstützt? Gibt es digitale Ansätze zur Unterstützung bei der\nstrategischen und systematischen Personalentwicklung in KMU?" },
    { dimension: "Organisationsentwicklung", nameKurz: "Organisationsentwickl.", name: "Organisationsentwicklung", oberdimension: "Unterstützung von KMU beim Strukturwandel", textLang: "Werden digitale Ansätze entwickelt, um den Zugang zu Weiterbildungs-\nstrukturen und -Plattformen für KMU zu erleichtern? Gehen diese Ansätze  wie\ntechnologischen Entwicklungen, Tools etc. über individuelle Lernanlässe/-\nbedarfe hinaus und adressieren bspw. KMU, weitere Betriebe/Unternehmen\noder ganze Branchen?" },

];

var dataUnterDimensionenEinzelStandAntrag = [ /// --------------------------------------------------------Stand Antrag--------------------------------
    { id: "1", dimension: "Plattformvernetzung", value1: 38, valueProzentGesamt1: 38, value2: 9, valueProzentGesamt2: 9, value3: 53, valueProzentGesamt3: 53, valueGesamt1: 18, valueGesamt2: 3, valueGesamt3: 13, value1: 1, value2: 3, value3: 1, value4: 1, value5: 2, value6: 1, value7: 3, value8: 3, value9: 2, value10: 1, value11: 1, value12: 3, value13: 1, value14: 1, value15: 0, value16: 1, value17: 3, value18: 3, value19: 1, value20: 1, value21: 3, value22: 0, value23: 3, value24: 1, value25: 0, value26: 0, value27: 2, value28: 3, value29: 0, value30: 3, value31: 3, value32: 1, value33: 3, value34: 3 },
    { id: "2", dimension: "Regionale WB-Landschaften", value1: 12, valueProzentGesamt1: 12, value2: 9, valueProzentGesamt2: 9, value3: 79, valueProzentGesamt3: 79, valueGesamt1: 27, valueGesamt2: 3, valueGesamt3: 4, value1: 0, value2: 2, value3: 1, value4: 1, value5: 0, value6: 1, value7: 3, value8: 1, value9: 1, value10: 0, value11: 0, value12: 1, value13: 0, value14: 1, value15: 2, value16: 0, value17: 0, value18: 1, value19: 0, value20: 0, value21: 2, value22: 0, value23: 0, value24: 1, value25: 0, value26: 1, value27: 1, value28: 3, value29: 0, value30: 1, value31: 1, value32: 1, value33: 3, value34: 3 },
    { id: "3", dimension: "Nachhaltige Geschäftsmodelle", value1: 3, valueProzentGesamt1: 3, value2: 26, valueProzentGesamt2: 26, value3: 71, valueProzentGesamt3: 71, valueGesamt1: 24, valueGesamt2: 9, valueGesamt3: 1, value1: 1, value2: 2, value3: 0, value4: 0, value5: 2, value6: 2, value7: 2, value8: 1, value9: 2, value10: 1, value11: 1, value12: 1, value13: 1, value14: 2, value15: 1, value16: 1, value17: 1, value18: 1, value19: 1, value20: 1, value21: 1, value22: 1, value23: 2, value24: 1, value25: 1, value26: 2, value27: 1, value28: 1, value29: 1, value30: 3, value31: 2, value32: 1, value33: 1, value34: 1 },
    { id: "4", dimension: "Ansprache spezifischer Zielgruppen", value1: 23, valueProzentGesamt1: 23, value2: 24, valueProzentGesamt2: 24, value3: 53, valueProzentGesamt3: 53, valueGesamt1: 18, valueGesamt2: 8, valueGesamt3: 8, value1: 3, value2: 2, value3: 2, value4: 3, value5: 0, value6: 3, value7: 1, value8: 1, value9: 3, value10: 0, value11: 1, value12: 1, value13: 1, value14: 2, value15: 1, value16: 1, value17: 0, value18: 3, value19: 1, value20: 3, value21: 1, value22: 1, value23: 2, value24: 2, value25: 2, value26: 1, value27: 3, value28: 3, value29: 1, value30: 2, value31: 1, value32: 2, value33: 1, value34: 1 },
    { id: "5", dimension: "Barrierefreiheit", value1: 21, valueProzentGesamt1: 21, value2: 38, valueProzentGesamt2: 38, value3: 41, valueProzentGesamt3: 41, valueGesamt1: 14, valueGesamt2: 13, valueGesamt3: 7, value1: 2, value2: 3, value3: 1, value4: 2, value5: 1, value6: 2, value7: 1, value8: 3, value9: 3, value10: 2, value11: 3, value12: 1, value13: 2, value14: 1, value15: 2, value16: 2, value17: 2, value18: 2, value19: 3, value20: 1, value21: 1, value22: 1, value23: 3, value24: 2, value25: 2, value26: 1, value27: 3, value28: 1, value29: 1, value30: 2, value31: 1, value32: 1, value33: 1, value34: 2 },
    { id: "6", dimension: "Mehrsprachigkeit", value1: 9, valueProzentGesamt1: 9, value2: 6, valueProzentGesamt2: 6, value3: 85, valueProzentGesamt3: 85, valueGesamt1: 29, valueGesamt2: 2, valueGesamt3: 3, value1: 3, value2: 1, value3: 0, value4: 3, value5: 1, value6: 0, value7: 0, value8: 0, value9: 1, value10: 0, value11: 2, value12: 0, value13: 0, value14: 0, value15: 0, value16: 0, value17: 0, value18: 0, value19: 0, value20: 0, value21: 0, value22: 0, value23: 0, value24: 3, value25: 2, value26: 0, value27: 0, value28: 0, value29: 1, value30: 0, value31: 1, value32: 1, value33: 0, value34: 0 },
    { id: "7", dimension: "Bestehende Kompetenzmodelle", value1: 41, valueProzentGesamt1: 41, value2: 15, valueProzentGesamt2: 15, value3: 44, valueProzentGesamt3: 44, valueGesamt1: 15, valueGesamt2: 5, valueGesamt3: 14, value1: 3, value2: 3, value3: 1, value4: 3, value5: 3, value6: 1, value7: 3, value8: 2, value9: 3, value10: 1, value11: 1, value12: 3, value13: 3, value14: 3, value15: 3, value16: 3, value17: 0, value18: 3, value19: 1, value20: 2, value21: 1, value22: 3, value23: 1, value24: 1, value25: 2, value26: 2, value27: 0, value28: 1, value29: 2, value30: 1, value31: 1, value32: 1, value33: 1, value34: 3 },
    { id: "8", dimension: "Weiter-Entwicklung von Kompetenzmodellen", value1: 17, valueProzentGesamt1: 17, value2: 12, valueProzentGesamt2: 12, value3: 71, valueProzentGesamt3: 71, valueGesamt1: 24, valueGesamt2: 4, valueGesamt3: 6, value1: 3, value2: 2, value3: 1, value4: 0, value5: 1, value6: 0, value7: 1, value8: 1, value9: 3, value10: 0, value11: 1, value12: 3, value13: 1, value14: 1, value15: 1, value16: 2, value17: 0, value18: 1, value19: 1, value20: 1, value21: 0, value22: 1, value23: 1, value24: 2, value25: 3, value26: 2, value27: 0, value28: 0, value29: 1, value30: 0, value31: 3, value32: 1, value33: 1, value34: 3 },
    { id: "9", dimension: "Erfassung informeller Kompetenzen", value1: 20, valueProzentGesamt1: 20, value2: 15, valueProzentGesamt2: 15, value3: 65, valueProzentGesamt3: 65, valueGesamt1: 22, valueGesamt2: 5, valueGesamt3: 7, value1: 3, value2: 3, value3: 1, value4: 1, value5: 0, value6: 1, value7: 1, value8: 1, value9: 3, value10: 1, value11: 2, value12: 1, value13: 1, value14: 2, value15: 1, value16: 1, value17: 1, value18: 2, value19: 3, value20: 3, value21: 1, value22: 1, value23: 3, value24: 1, value25: 1, value26: 0, value27: 0, value28: 1, value29: 2, value30: 1, value31: 1, value32: 2, value33: 1, value34: 3 },
    { id: "10", dimension: "Innovative Lernarrangements", value1: 38, valueProzentGesamt1: 38, value2: 44, valueProzentGesamt2: 44, value3: 18, valueProzentGesamt3: 18, valueGesamt1: 6, valueGesamt2: 15, valueGesamt3: 13, value1: 2, value2: 2, value3: 3, value4: 3, value5: 0, value6: 3, value7: 3, value8: 2, value9: 2, value10: 2, value11: 3, value12: 2, value13: 1, value14: 3, value15: 3, value16: 2, value17: 3, value18: 3, value19: 3, value20: 3, value21: 2, value22: 1, value23: 2, value24: 2, value25: 1, value26: 2, value27: 3, value28: 3, value29: 2, value30: 2, value31: 1, value32: 2, value33: 1, value34: 2 },
    { id: "11", dimension: "Adaptive Lernpfade", value1: 56, valueProzentGesamt1: 56, value2: 29, valueProzentGesamt2: 29, value3: 15, valueProzentGesamt3: 15, valueGesamt1: 5, valueGesamt2: 10, valueGesamt3: 19, value1: 2, value2: 2, value3: 2, value4: 3, value5: 3, value6: 2, value7: 3, value8: 1, value9: 2, value10: 3, value11: 3, value12: 1, value13: 3, value14: 3, value15: 2, value16: 3, value17: 3, value18: 3, value19: 3, value20: 2, value21: 3, value22: 2, value23: 1, value24: 3, value25: 3, value26: 3, value27: 1, value28: 2, value29: 3, value30: 3, value31: 2, value32: 3, value33: 1, value34: 3 },
    { id: "12", dimension: "Recommendersysteme", value1: 42, valueProzentGesamt1: 42, value2: 26, valueProzentGesamt2: 26, value3: 32, valueProzentGesamt3: 32, valueGesamt1: 11, valueGesamt2: 9, valueGesamt3: 14, value1: 3, value2: 3, value3: 1, value4: 1, value5: 2, value6: 1, value7: 3, value8: 2, value9: 3, value10: 3, value11: 3, value12: 1, value13: 1, value14: 2, value15: 3, value16: 3, value17: 2, value18: 2, value19: 2, value20: 1, value21: 3, value22: 2, value23: 1, value24: 1, value25: 1, value26: 2, value27: 3, value28: 2, value29: 1, value30: 3, value31: 0, value32: 3, value33: 3, value34: 3 },
    { id: "13", dimension: "Einbindung relevanter Stakeholder", value1: 0, valueProzentGesamt1: 0, value2: 6, valueProzentGesamt2: 6, value3: 94, valueProzentGesamt3: 94, valueGesamt1: 32, valueGesamt2: 2, valueGesamt3: 0, value1: 0, value2: 0, value3: 0, value4: 0, value5: 0, value6: 0, value7: 0, value8: 1, value9: 0, value10: 0, value11: 0, value12: 0, value13: 0, value14: 0, value15: 0, value16: 1, value17: 1, value18: 1, value19: 1, value20: 1, value21: 0, value22: 0, value23: 0, value24: 1, value25: 1, value26: 1, value27: 0, value28: 1, value29: 0, value30: 2, value31: 1, value32: 1, value33: 1, value34: 2 },
    { id: "14", dimension: "Personalentwicklung", value1: 27, valueProzentGesamt1: 27, value2: 35, valueProzentGesamt2: 35, value3: 38, valueProzentGesamt3: 38, valueGesamt1: 13, valueGesamt2: 12, valueGesamt3: 9, value1: 1, value2: 2, value3: 1, value4: 3, value5: 3, value6: 1, value7: 1, value8: 2, value9: 0, value10: 2, value11: 2, value12: 2, value13: 0, value14: 1, value15: 1, value16: 3, value17: 2, value18: 3, value19: 3, value20: 2, value21: 1, value22: 3, value23: 1, value24: 1, value25: 2, value26: 2, value27: 2, value28: 3, value29: 1, value30: 3, value31: 2, value32: 2, value33: 3, value34: 1 },
    { id: "15", dimension: "Organisationsentwicklung", value1: 3, valueProzentGesamt1: 3, value2: 6, valueProzentGesamt2: 6, value3: 91, valueProzentGesamt3: 91, valueGesamt1: 31, valueGesamt2: 2, valueGesamt3: 1, value1: 1, value2: 1, value3: 1, value4: 1, value5: 1, value6: 2, value7: 1, value8: 1, value9: 1, value10: 1, value11: 1, value12: 1, value13: 1, value14: 1, value15: 1, value16: 1, value17: 1, value18: 1, value19: 3, value20: 1, value21: 1, value22: 1, value23: 1, value24: 1, value25: 1, value26: 1, value27: 1, value28: 1, value29: 1, value30: 2, value31: 1, value32: 1, value33: 1, value34: 1 },

];
var dataUnterDimensionenEinzelStandZeitpunktA = dataUnterDimensionenEinzelStandAntrag; //Datensatz Slider erste position (=links)

var dataUnterDimensionenEinzelStandZB2021 = [ //Daten Array für Radarboard Einzelvorhaben ----------------Stand Dezember 2022------------------------------------------
    { id: "1", dimension: "Plattformvernetzung", valueProzentGesamt1: 35, valueProzentGesamt2: 21, valueProzentGesamt3: 44, valueGesamt1: 15, valueGesamt2: 7, valueGesamt3: 12, value1: 1, value2: 3, value3: 1, value4: 2, value5: 2, value6: 1, value7: 3, value8: 3, value9: 2, value10: 1, value11: 1, value12: 3, value13: 1, value14: 1, value15: 0, value16: 1, value17: 3, value18: 3, value19: 1, value20: 1, value21: 2, value22: 0, value23: 3, value24: 2, value25: 1, value26: 0, value27: 2, value28: 3, value29: 2, value30: 3, value31: 3, value32: 1, value33: 3, value34: 3 },
    { id: "2", dimension: "Regionale WB-Landschaften", valueProzentGesamt1: 8, valueProzentGesamt2: 24, valueProzentGesamt3: 68, valueGesamt1: 23, valueGesamt2: 8, valueGesamt3: 3, value1: 0, value2: 2, value3: 1, value4: 2, value5: 1, value6: 1, value7: 3, value8: 2, value9: 1, value10: 0, value11: 0, value12: 1, value13: 0, value14: 1, value15: 2, value16: 0, value17: 0, value18: 1, value19: 0, value20: 0, value21: 2, value22: 0, value23: 0, value24: 1, value25: 0, value26: 0, value27: 1, value28: 3, value29: 2, value30: 1, value31: 2, value32: 1, value33: 3, value34: 2 },
    { id: "3", dimension: "Nachhaltige Geschäftsmodelle", valueProzentGesamt1: 12, valueProzentGesamt2: 38, valueProzentGesamt3: 50, valueGesamt1: 17, valueGesamt2: 13, valueGesamt3: 4, value1: 1, value2: 2, value3: 1, value4: 0, value5: 2, value6: 3, value7: 2, value8: 1, value9: 2, value10: 1, value11: 1, value12: 1, value13: 2, value14: 2, value15: 1, value16: 1, value17: 1, value18: 1, value19: 3, value20: 1, value21: 1, value22: 3, value23: 2, value24: 2, value25: 1, value26: 2, value27: 2, value28: 1, value29: 1, value30: 2, value31: 2, value32: 1, value33: 3, value34: 2 },
    { id: "4", dimension: "Ansprache spezifischer Zielgruppen", valueProzentGesamt1: 38, valueProzentGesamt2: 21, valueProzentGesamt3: 41, valueGesamt1: 14, valueGesamt2: 7, valueGesamt3: 13, value1: 3, value2: 2, value3: 3, value4: 3, value5: 0, value6: 3, value7: 1, value8: 3, value9: 3, value10: 0, value11: 1, value12: 3, value13: 1, value14: 2, value15: 2, value16: 1, value17: 1, value18: 3, value19: 1, value20: 3, value21: 2, value22: 1, value23: 3, value24: 2, value25: 2, value26: 1, value27: 3, value28: 3, value29: 1, value30: 2, value31: 1, value32: 3, value33: 1, value34: 1 },
    { id: "5", dimension: "Barrierefreiheit", valueProzentGesamt1: 12, valueProzentGesamt2: 44, valueProzentGesamt3: 44, valueGesamt1: 15, valueGesamt2: 15, valueGesamt3: 4, value1: 1, value2: 3, value3: 0, value4: 2, value5: 1, value6: 2, value7: 1, value8: 3, value9: 3, value10: 2, value11: 1, value12: 1, value13: 2, value14: 2, value15: 2, value16: 2, value17: 2, value18: 2, value19: 3, value20: 1, value21: 1, value22: 1, value23: 2, value24: 2, value25: 2, value26: 1, value27: 1, value28: 2, value29: 2, value30: 1, value31: 1, value32: 1, value33: 1, value34: 2 },
    { id: "6", dimension: "Mehrsprachigkeit", valueProzentGesamt1: 9, valueProzentGesamt2: 9, valueProzentGesamt3: 82, valueGesamt1: 28, valueGesamt2: 3, valueGesamt3: 3, value1: 1, value2: 1, value3: 0, value4: 3, value5: 1, value6: 0, value7: 0, value8: 0, value9: 0, value10: 0, value11: 2, value12: 0, value13: 0, value14: 0, value15: 0, value16: 0, value17: 2, value18: 0, value19: 0, value20: 0, value21: 0, value22: 3, value23: 1, value24: 3, value25: 0, value26: 0, value27: 0, value28: 0, value29: 1, value30: 1, value31: 2, value32: 1, value33: 0, value34: 0 },
    { id: "7", dimension: "Bestehende Kompetenzmodelle", valueProzentGesamt1: 39, valueProzentGesamt2: 35, valueProzentGesamt3: 26, valueGesamt1: 9, valueGesamt2: 12, valueGesamt3: 13, value1: 3, value2: 3, value3: 1, value4: 2, value5: 2, value6: 1, value7: 3, value8: 2, value9: 2, value10: 1, value11: 1, value12: 3, value13: 3, value14: 3, value15: 3, value16: 3, value17: 1, value18: 3, value19: 1, value20: 2, value21: 1, value22: 3, value23: 2, value24: 3, value25: 1, value26: 2, value27: 2, value28: 1, value29: 2, value30: 2, value31: 2, value32: 3, value33: 2, value34: 3 },
    { id: "8", dimension: "(Weiter-)Entwicklung von Kompetenzmodellen", valueProzentGesamt1: 17, valueProzentGesamt2: 18, valueProzentGesamt3: 65, valueGesamt1: 22, valueGesamt2: 6, valueGesamt3: 6, value1: 3, value2: 2, value3: 1, value4: 0, value5: 2, value6: 0, value7: 1, value8: 1, value9: 1, value10: 0, value11: 1, value12: 3, value13: 1, value14: 1, value15: 1, value16: 2, value17: 1, value18: 1, value19: 1, value20: 1, value21: 2, value22: 1, value23: 1, value24: 3, value25: 2, value26: 1, value27: 0, value28: 0, value29: 1, value30: 3, value31: 2, value32: 3, value33: 1, value34: 3 },
    { id: "9", dimension: "Erfassung informeller Kompetenzen", valueProzentGesamt1: 12, valueProzentGesamt2: 38, valueProzentGesamt3: 50, valueGesamt1: 17, valueGesamt2: 13, valueGesamt3: 4, value1: 3, value2: 3, value3: 1, value4: 1, value5: 0, value6: 1, value7: 1, value8: 1, value9: 3, value10: 2, value11: 2, value12: 2, value13: 2, value14: 2, value15: 2, value16: 1, value17: 1, value18: 2, value19: 2, value20: 3, value21: 0, value22: 1, value23: 2, value24: 1, value25: 1, value26: 0, value27: 0, value28: 1, value29: 2, value30: 2, value31: 1, value32: 2, value33: 0, value34: 2 },
    { id: "10", dimension: "Innovative Lernarrangements", valueProzentGesamt1: 44, valueProzentGesamt2: 32, valueProzentGesamt3: 24, valueGesamt1: 8, valueGesamt2: 11, valueGesamt3: 15, value1: 3, value2: 2, value3: 3, value4: 3, value5: 2, value6: 3, value7: 3, value8: 2, value9: 1, value10: 2, value11: 3, value12: 2, value13: 1, value14: 3, value15: 2, value16: 2, value17: 3, value18: 3, value19: 3, value20: 3, value21: 1, value22: 1, value23: 1, value24: 3, value25: 1, value26: 1, value27: 3, value28: 2, value29: 2, value30: 3, value31: 2, value32: 3, value33: 2, value34: 0 },
    { id: "11", dimension: "Adaptive Lernpfade", valueProzentGesamt1: 58, valueProzentGesamt2: 21, valueProzentGesamt3: 21, valueGesamt1: 7, valueGesamt2: 7, valueGesamt3: 20, value1: 3, value2: 2, value3: 3, value4: 3, value5: 3, value6: 3, value7: 3, value8: 1, value9: 1, value10: 3, value11: 3, value12: 2, value13: 3, value14: 3, value15: 0, value16: 3, value17: 2, value18: 3, value19: 2, value20: 2, value21: 3, value22: 0, value23: 1, value24: 3, value25: 3, value26: 3, value27: 3, value28: 2, value29: 3, value30: 3, value31: 2, value32: 3, value33: 1, value34: 0 },
    { id: "12", dimension: "Recommendersysteme", valueProzentGesamt1: 58, valueProzentGesamt2: 24, valueProzentGesamt3: 18, valueGesamt1: 6, valueGesamt2: 8, valueGesamt3: 20, value1: 3, value2: 3, value3: 2, value4: 1, value5: 3, value6: 3, value7: 3, value8: 2, value9: 3, value10: 3, value11: 3, value12: 1, value13: 3, value14: 3, value15: 1, value16: 3, value17: 3, value18: 3, value19: 2, value20: 1, value21: 2, value22: 2, value23: 3, value24: 2, value25: 3, value26: 3, value27: 3, value28: 2, value29: 1, value30: 2, value31: 3, value32: 3, value33: 1, value34: 3 },
    { id: "13", dimension: "Einbindung relevanter Stakeholder", valueProzentGesamt1: 11, valueProzentGesamt2: 21, valueProzentGesamt3: 68, valueGesamt1: 23, valueGesamt2: 7, valueGesamt3: 4, value1: 1, value2: 0, value3: 1, value4: 0, value5: 0, value6: 0, value7: 0, value8: 1, value9: 0, value10: 0, value11: 1, value12: 3, value13: 0, value14: 0, value15: 2, value16: 1, value17: 1, value18: 0, value19: 2, value20: 2, value21: 2, value22: 0, value23: 3, value24: 3, value25: 1, value26: 0, value27: 0, value28: 1, value29: 2, value30: 2, value31: 2, value32: 1, value33: 3, value34: 1 },
    { id: "14", dimension: "Personalentwicklung", valueProzentGesamt1: 33, valueProzentGesamt2: 41, valueProzentGesamt3: 26, valueGesamt1: 9, valueGesamt2: 14, valueGesamt3: 11, value1: 3, value2: 2, value3: 1, value4: 3, value5: 3, value6: 1, value7: 1, value8: 2, value9: 0, value10: 2, value11: 2, value12: 2, value13: 0, value14: 3, value15: 2, value16: 3, value17: 2, value18: 0, value19: 3, value20: 2, value21: 1, value22: 3, value23: 3, value24: 2, value25: 2, value26: 1, value27: 2, value28: 3, value29: 1, value30: 2, value31: 2, value32: 3, value33: 3, value34: 2 },
    { id: "15", dimension: "Organisationsentwicklung", valueProzentGesamt1: 20, valueProzentGesamt2: 18, valueProzentGesamt3: 62, valueGesamt1: 21, valueGesamt2: 6, valueGesamt3: 7, value1: 2, value2: 1, value3: 1, value4: 3, value5: 3, value6: 2, value7: 1, value8: 1, value9: 1, value10: 1, value11: 1, value12: 1, value13: 0, value14: 1, value15: 1, value16: 3, value17: 2, value18: 0, value19: 3, value20: 2, value21: 0, value22: 1, value23: 3, value24: 2, value25: 2, value26: 1, value27: 1, value28: 3, value29: 1, value30: 1, value31: 1, value32: 3, value33: 1, value34: 1 },

];
var dataUnterDimensionenEinzelStandZeitpunktB = dataUnterDimensionenEinzelStandZB2021; //Datensatz Slider 2. position (=mitte)

var dataUnterDimensionenEinzelStandTagung2022 = [ //Daten Array für Radarboard Einzelvorhaben --------------Stand August 2023-------------------------
    { id: "1", dimension: "Plattformvernetzung", valueProzentGesamt1: 38, valueProzentGesamt2: 18, valueProzentGesamt3: 44, valueGesamt1: 15, valueGesamt2: 6, valueGesamt3: 13, value1: 1, value2: 3, value3: 1, value4: 2, value5: 2, value6: 1, value7: 3, value8: 3, value9: 3, value10: 1, value11: 0, value12: 3, value13: 1, value14: 1, value15: 1, value16: 1, value17: 3, value18: 3, value19: 1, value20: 1, value21: 2, value22: 0, value23: 3, value24: 2, value25: 1, value26: 1, value27: 2, value28: 3, value29: 2, value30: 3, value31: 3, value32: 1, value33: 3, value34: 3 },
    { id: "2", dimension: "Regionale WB-Landschaften", valueProzentGesamt1: 8, valueProzentGesamt2: 24, valueProzentGesamt3: 68, valueGesamt1: 23, valueGesamt2: 8, valueGesamt3: 3, value1: 0, value2: 2, value3: 1, value4: 2, value5: 1, value6: 1, value7: 3, value8: 2, value9: 1, value10: 0, value11: 0, value12: 1, value13: 0, value14: 1, value15: 2, value16: 0, value17: 0, value18: 1, value19: 0, value20: 2, value21: 1, value22: 0, value23: 0, value24: 1, value25: 0, value26: 1, value27: 1, value28: 3, value29: 2, value30: 1, value31: 2, value32: 1, value33: 3, value34: 2 },
    { id: "3", dimension: "Nachhaltige Geschäftsmodelle", valueProzentGesamt1: 18, valueProzentGesamt2: 38, valueProzentGesamt3: 44, valueGesamt1: 15, valueGesamt2: 13, valueGesamt3: 6, value1: 1, value2: 2, value3: 1, value4: 0, value5: 2, value6: 3, value7: 2, value8: 1, value9: 2, value10: 1, value11: 0, value12: 1, value13: 2, value14: 2, value15: 2, value16: 1, value17: 1, value18: 1, value19: 3, value20: 1, value21: 3, value22: 3, value23: 3, value24: 2, value25: 1, value26: 2, value27: 2, value28: 1, value29: 1, value30: 2, value31: 2, value32: 1, value33: 3, value34: 2 },
    { id: "4", dimension: "Ansprache spezifischer Zielgruppen", valueProzentGesamt1: 38, valueProzentGesamt2: 21, valueProzentGesamt3: 41, valueGesamt1: 14, valueGesamt2: 7, valueGesamt3: 13, value1: 3, value2: 2, value3: 3, value4: 3, value5: 1, value6: 3, value7: 1, value8: 3, value9: 3, value10: 0, value11: 1, value12: 3, value13: 1, value14: 2, value15: 3, value16: 1, value17: 1, value18: 3, value19: 1, value20: 1, value21: 2, value22: 1, value23: 3, value24: 2, value25: 2, value26: 1, value27: 3, value28: 3, value29: 1, value30: 2, value31: 1, value32: 3, value33: 1, value34: 2 },
    { id: "5", dimension: "Barrierefreiheit", valueProzentGesamt1: 12, valueProzentGesamt2: 38, valueProzentGesamt3: 50, valueGesamt1: 17, valueGesamt2: 13, valueGesamt3: 4, value1: 1, value2: 3, value3: 0, value4: 2, value5: 1, value6: 2, value7: 1, value8: 3, value9: 3, value10: 2, value11: 1, value12: 1, value13: 2, value14: 2, value15: 1, value16: 2, value17: 2, value18: 1, value19: 3, value20: 0, value21: 1, value22: 1, value23: 2, value24: 2, value25: 2, value26: 1, value27: 1, value28: 2, value29: 2, value30: 1, value31: 1, value32: 1, value33: 1, value34: 2 },
    { id: "6", dimension: "Mehrsprachigkeit", valueProzentGesamt1: 9, valueProzentGesamt2: 9, valueProzentGesamt3: 82, valueGesamt1: 28, valueGesamt2: 3, valueGesamt3: 3, value1: 1, value2: 1, value3: 0, value4: 3, value5: 1, value6: 0, value7: 0, value8: 0, value9: 0, value10: 0, value11: 2, value12: 0, value13: 0, value14: 0, value15: 0, value16: 1, value17: 2, value18: 0, value19: 0, value20: 0, value21: 0, value22: 3, value23: 1, value24: 3, value25: 0, value26: 0, value27: 0, value28: 0, value29: 1, value30: 1, value31: 2, value32: 1, value33: 0, value34: 0 },
    { id: "7", dimension: "Bestehende Kompetenzmodelle", valueProzentGesamt1: 36, valueProzentGesamt2: 35, valueProzentGesamt3: 29, valueGesamt1: 10, valueGesamt2: 12, valueGesamt3: 12, value1: 3, value2: 3, value3: 1, value4: 2, value5: 2, value6: 1, value7: 3, value8: 2, value9: 1, value10: 0, value11: 1, value12: 3, value13: 3, value14: 1, value15: 3, value16: 3, value17: 2, value18: 3, value19: 2, value20: 2, value21: 1, value22: 3, value23: 2, value24: 3, value25: 1, value26: 2, value27: 2, value28: 0, value29: 0, value30: 2, value31: 2, value32: 3, value33: 2, value34: 3 },
    { id: "8", dimension: "(Weiter-)Entwicklung von Kompetenzmodellen", valueProzentGesamt1: 17, valueProzentGesamt2: 18, valueProzentGesamt3: 65, valueGesamt1: 22, valueGesamt2: 6, valueGesamt3: 6, value1: 3, value2: 2, value3: 1, value4: 0, value5: 2, value6: 0, value7: 1, value8: 1, value9: 0, value10: 0, value11: 1, value12: 3, value13: 1, value14: 1, value15: 1, value16: 2, value17: 1, value18: 2, value19: 1, value20: 1, value21: 1, value22: 1, value23: 1, value24: 3, value25: 2, value26: 1, value27: 0, value28: 0, value29: 0, value30: 3, value31: 2, value32: 3, value33: 1, value34: 3 },
    { id: "9", dimension: "Erfassung informeller Kompetenzen", valueProzentGesamt1: 15, valueProzentGesamt2: 26, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 9, valueGesamt3: 5, value1: 3, value2: 3, value3: 1, value4: 1, value5: 0, value6: 1, value7: 2, value8: 1, value9: 1, value10: 0, value11: 2, value12: 2, value13: 2, value14: 2, value15: 3, value16: 1, value17: 1, value18: 2, value19: 3, value20: 1, value21: 0, value22: 1, value23: 3, value24: 1, value25: 1, value26: 0, value27: 0, value28: 0, value29: 0, value30: 2, value31: 1, value32: 2, value33: 0, value34: 2 },
    { id: "10", dimension: "Innovative Lernarrangements", valueProzentGesamt1: 44, valueProzentGesamt2: 32, valueProzentGesamt3: 24, valueGesamt1: 8, valueGesamt2: 11, valueGesamt3: 15, value1: 3, value2: 2, value3: 3, value4: 3, value5: 2, value6: 3, value7: 3, value8: 2, value9: 1, value10: 2, value11: 3, value12: 2, value13: 1, value14: 3, value15: 1, value16: 2, value17: 3, value18: 3, value19: 3, value20: 3, value21: 1, value22: 1, value23: 1, value24: 3, value25: 1, value26: 2, value27: 3, value28: 2, value29: 2, value30: 3, value31: 2, value32: 3, value33: 2, value34: 0 },
    { id: "11", dimension: "Adaptive Lernpfade", valueProzentGesamt1: 55, valueProzentGesamt2: 21, valueProzentGesamt3: 24, valueGesamt1: 8, valueGesamt2: 7, valueGesamt3: 19, value1: 3, value2: 2, value3: 2, value4: 3, value5: 3, value6: 3, value7: 3, value8: 1, value9: 0, value10: 3, value11: 3, value12: 2, value13: 3, value14: 3, value15: 0, value16: 3, value17: 2, value18: 3, value19: 1, value20: 2, value21: 3, value22: 0, value23: 1, value24: 3, value25: 3, value26: 3, value27: 3, value28: 3, value29: 2, value30: 3, value31: 2, value32: 3, value33: 1, value34: 0 },
    { id: "12", dimension: "Recommendersysteme", valueProzentGesamt1: 64, valueProzentGesamt2: 21, valueProzentGesamt3: 15, valueGesamt1: 5, valueGesamt2: 7, valueGesamt3: 22, value1: 3, value2: 3, value3: 3, value4: 1, value5: 3, value6: 3, value7: 3, value8: 2, value9: 3, value10: 3, value11: 3, value12: 1, value13: 3, value14: 3, value15: 3, value16: 3, value17: 3, value18: 3, value19: 2, value20: 0, value21: 2, value22: 2, value23: 3, value24: 2, value25: 3, value26: 3, value27: 3, value28: 2, value29: 1, value30: 2, value31: 3, value32: 3, value33: 1, value34: 3 },
    { id: "13", dimension: "Einbindung relevanter Stakeholder", valueProzentGesamt1: 15, valueProzentGesamt2: 26, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 9, valueGesamt3: 5, value1: 1, value2: 0, value3: 1, value4: 0, value5: 2, value6: 0, value7: 0, value8: 1, value9: 1, value10: 0, value11: 1, value12: 3, value13: 0, value14: 2, value15: 2, value16: 1, value17: 1, value18: 1, value19: 2, value20: 2, value21: 2, value22: 0, value23: 3, value24: 3, value25: 1, value26: 2, value27: 0, value28: 3, value29: 1, value30: 2, value31: 2, value32: 1, value33: 3, value34: 1 },
    { id: "14", dimension: "Personalentwicklung", valueProzentGesamt1: 33, valueProzentGesamt2: 38, valueProzentGesamt3: 29, valueGesamt1: 10, valueGesamt2: 13, valueGesamt3: 11, value1: 3, value2: 2, value3: 1, value4: 3, value5: 3, value6: 1, value7: 0, value8: 2, value9: 1, value10: 2, value11: 2, value12: 2, value13: 0, value14: 3, value15: 1, value16: 3, value17: 2, value18: 0, value19: 3, value20: 2, value21: 1, value22: 3, value23: 3, value24: 2, value25: 2, value26: 1, value27: 2, value28: 3, value29: 0, value30: 2, value31: 2, value32: 3, value33: 3, value34: 2 },
    { id: "15", dimension: "Organisationsentwicklung", valueProzentGesamt1: 17, valueProzentGesamt2: 24, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 8, valueGesamt3: 6, value1: 2, value2: 1, value3: 1, value4: 3, value5: 3, value6: 2, value7: 2, value8: 1, value9: 1, value10: 1, value11: 1, value12: 1, value13: 0, value14: 1, value15: 1, value16: 3, value17: 2, value18: 0, value19: 3, value20: 2, value21: 0, value22: 1, value23: 3, value24: 2, value25: 2, value26: 1, value27: 1, value28: 2, value29: 0, value30: 1, value31: 1, value32: 3, value33: 1, value34: 1 },

];
var dataUnterDimensionenEinzelStandZeitpunktC = dataUnterDimensionenEinzelStandTagung2022; //Datensatz Slider 3. position (=rechts) = Stand August 2023


//var dataUnterDimensionenEinzel = dataUnterDimensionenEinzelStandZB2021; ///aktuellen Datensatz auf den letzten Stand setzen, dieser ist dann der inital angezeigte Datensatz
var dataUnterDimensionenEinzel = dataUnterDimensionenEinzelStandAntrag; /// slider steht zu Beginn auf StandAntrag
var dataUnterDimensionen = dataUnterDimensionenEinzel; //values nur noch in Einzelarray enthalten

var dataUnterDimensionenEinzelTexte = [ ///Daten Array für Texte jedes Einzel-Radarboards
    { id: "1", name: "ADAPT", entwicklungsfeld: "3", thema: "Adaptives Weiterbildungsunterstützungssystem im Berufsfeld Pflege", zielgruppe: "Fach- und Führungskräfte in der Pflege", innovation: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, personalisierte Lernpfade und Userprofile, Lern-Dashboard erfasst Kompetenz und Lernanforderung, auf natürlicher Sprachverarbeitung basiertes Matching mit Arbeitsmarktdaten", weiterbildungsplattform: "www.edoer.eu", branche: "Pflege", projektzieleschwerpunkte: "ADAPT entwickelt eine Lernumgebung für Pflegende, die individualisiertes und bedarfsgerechtes Lernen ermöglicht.\nDie KI-gestützte, app-basierte Weiterbildungsplattform eDoer unterstützt Pflegende, die für sie passenden Lerninhalte\nzu finden – in Form einer längerfristig angelegten, personalisierten Lernreise oder über kurze, interaktive Lernnuggets.\nEin Schwerpunkt liegt in der digitalen Kompetenzdiagnostik, die zur Fachkräfteentwicklung in der Pflegebranche beiträgt.\nHierzu werden kollektive Veränderungsbedarfe von Pflegeeinrichtungen verknüpft mit (informell erworbenen)\nKompetenzen sowie individuellen Lernbedarfen von Pflegenden. Auf  diese Weise kann eDoer auch als Teil der Personal-\nund Kompetenzentwicklung im Pflegeteam eingesetzt werden. Das eingesetzte Recommendersystem hilft dabei, einen\nindividuellen Lernplan aus Bereichen wie „Lernreise“, „Kurs“, „Lernthema“ und „Bildungsressourcen“ zu erstellen und die\nQualität von öffentlich zugänglichen Bildungsinhalten im Pflegebereich zu überprüfen.", technologischesziel: "Lern-Dashboard erfasst Kompetenz und Lernanforderung, NLP-basiertes Matching mit Arbeitsmarktdaten, Web, YouTube und OER, Django/React, Oauth, NLTK", mehrwert: "• Erhöht die Reichweite beruflicher Weiterbildungsmaßnahmen & steigert die Weiterbildungsbeteiligung der Beschäftigten in der Pflege\n• Verbessert die Lern- und Bildungssituation von Beschäftigten in der beruflichen Pflege\n• Stärkt (digital gestütztes) berufliches Lernen im betrieblichen Kontext\n• Gewährleistet durch die Einbindung der freien Software eDoer einen offenen Zugang zu Bildungsmaterialien", verbundpartner: "• Institut Arbeit und Technik (IAT, Projektleitung)\n• BiG Bildungsinstitut im Gesundheitswesen\n• Pädagogische Hochschule Freiburg\n• maxQ/IFTP im bfw - Unternehmen für Bildung\n• TIB Leibniz-Informationszentrum Technik und Naturwissenschaften Universitätsbibliothek\n• Alten- und Pflegezentren des Main-Kinzig-Kreises (APZ MKK) " },
    { id: "2", name: "APOLLO", entwicklungsfeld: "2, 3", thema: ": KI-basierte, plattformübergreifende Companion-App für lebenslange Lern-Optimierung", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend", projektzieleschwerpunkte: "APOLLO entwickelt eine Companion-App, die Menschen mit einem intelligenten Assistenten auf ihrem lebenslangen\nAus- und Weiterbildungsweg unterstützt. Die Companion-APP erstellt aus einer Vielzahl von Informationen ein individuelles\nKompetenzprofil der Nutzenden, welches den persönlichen Wissensbedarf und die Lernziele berücksichtigt. Neben\nZeugnissen und Lebenslauf können mithilfe eines berufsfachlichen Skill-Assessments auch Softskills und informell\nerworbene Kompetenzen in die Analyse einbezogen werden. Auf Grundlage des Kompetenzprofils empfiehlt ein\nI-basiertes Recommendersystem passgenaue Weiterbildungen aus den verfügbaren Angeboten der untenstehenden\nVerbundpartner. Grundsätzlich ist APOLLO anbieterunabhängig und offen für alle Weiterbildungsträger, die ihre Angebote\nund Leistungen über quelloffene Software-Schnittstellen dem KI-gestützten Algorithmus zur Verfügung zu stellen möchten.\nIm Fokus der manuellen und automatisierten Kompetenzerfassung wird für die Companion-App intensiv der ESCO-Standard\ngenutzt und erweitert, um Kompetenzen detailgetreu abbilden zu können.", technologischesziel: "Cross-Plattform-App, NLP zur Analyse von Qualifikationsunterlagen, Einsatz von Klassifizierungssystemen zur Einschätzung von Kompetenzen, graph-basierter Ansatz zur Verknüpfung von Bestandsdaten, Wissensgraph und Link Prediction zur Generierung von Empfehlungen, MLOps Infrastruktur, kontinuierliche Messung der Qualität der Vorhersagen", mehrwert: "• Fördert durch die passgenaue Empfehlung von Weiterbildungen die nachhaltige Teilhabe am Erwerbsleben, der allgemeinen\n  Weiterbildung und liefert einen Beitrag zur Fachkräftesicherung\n• Inspiriert Weiterbildungsinteressierte aus unterschiedlichen Branchen mit individuell\n  passgenauen Angeboten dazu, ihre eigene persönliche Lernreise und Berufskarriere zu planen", verbundpartner: "• Hochschule der Bayerischen Wirtschaft HDBW gGmbH (Projektleitung)\n• Bildungswerk der Bayerischen Wirtschaft gGmbH\n• Bildungswerk der Baden-Württembergischen Wirtschaft e.V.\n• Bertelsmann Stiftung\n• TÜV Rheinland Akademie GmbH" },
    { id: "3", name: "ComP-ASS", entwicklungsfeld: "3", thema: "Computergestütztes Lernen und Lehren im Handwerk mit interaktiven Assistenzsystemen", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Handwerk", projektzieleschwerpunkte: "digitalgestütztes Weiterbildungsangebot zur Vermittlung von CNC-Kompetenzen für das Handwerk, Simulationen von Materialänderungen, interaktive VR/AR-basierte „CNC-Maschinen-Welt“, Gamification-Elemente, interaktives didaktisches Assistenzsystem", technologischesziel: "AR/VR Maschinenwelt, Plugin für ILIAS, regelbasierter didaktischer Assistent für Autoren von Lehrinhalten im Handwerk", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "4", name: "DigiPlat4Train", entwicklungsfeld: "1,2,3", thema: "Automatisierte, datenbasierte Rückschlüsse aus der praktischen Arbeit an Fertigungsmaschinen", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Kunststofffertigung", projektzieleschwerpunkte: "virtueller Produktionsassistent, KI, Kunststofftechnologie, DSGVO, KI mit Fehlercodes, Training direkt an Produktionsmaschine, Abstimmung mit Betriebsrat und Mitarbeitenden", technologischesziel: "VIPRA erfasst Trainings- und Arbeitsdaten an Maschine, KI bietet Kurse und Micro-Lerneinheiten von Weiterbildungsplattform anhand erkannter Lerndefizite an", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "5", name: "EduPLEx_API", entwicklungsfeld: "2 (untergeordnet 3) ", thema: "Erweiterung einer bestehenden Learning Experience Plattform (LXP) um eine Schnittstelle zu einem KI-basierten Empfehlungssystem bzw. einem Lern-Nachweis-System um eine Mandaten-Fähigkeit der Plattform für die Anwendbarkeit für KMU", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend, Fokus liegt KMU", projektzieleschwerpunkte: "Empfehlungsmaschine, Marktplatz, adaptives Lernkonzept (selbstgesteuertes Lernen mit homogenen Inhalten, Trainer-gestütztes Lernen mit heterogenen Lernmaterialien und kollaboratives Arbeiten), Suchen / Sprachmodell (semantische Netze) zur Identifikation von Inhalten", technologischesziel: "Interoperabilität, Integration von Zusatzdiensten", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "6", name: "ELe-com", entwicklungsfeld: "2,3", thema: "Empowering Learning – Ermöglichung adaptiven Lernens in der beruflichen Weiterbildung am Beispiel des E-Commerce ", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Handel", projektzieleschwerpunkte: "Individuelles Lernen über die Berücksichtigung von Lernpräferenzen durch den Einsatz  von adaptiven Lernwegen, adaptiven Lernformaten in Form von Micro Learning Einheiten und Empfehlungen durch KI Assistenzsysteme anhand des Themas Customer Journey im E-Commerce.", technologischesziel: "KI-unterstütztes Assistenzsystem aus zwei Tools: Lernnavigator (LENA) und Entscheidungsmodul (EMIL), Weiterentwicklung myFlexNet.de (ILIAS-Plattform)", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "7", name: "ExpanderWB3", entwicklungsfeld: "2,3", thema: "Vernetzung der „Weiterbildungsdatenbank Suchportal in Berlin und Brandenburg“ mit weiteren Plattformen und KI-gestützte Empfehlung von Inhalten für die berufliche Weiterbildung", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend, Fokus auf Branchen der industriellen Verarbeitung", projektzieleschwerpunkte: "Nutzendenzentrierte Individualisierung von beruflichen Lernangeboten mit Bezug zu unternehmens- und arbeitsmarktpolitischen Erfolgsmerkmalen", technologischesziel: "Entwicklung von interoperablen Standards und Schnittstellen; Begriffs-Klassifikationen und Ontologien; Integration eines Gamification Ansatzes; Implementierung einer semantischen Suche; User-Profile und E-Portfolios auf Kompetenz­basis; Learning Analytics, Lernempfehlungen und Lernpfade", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "8", name: "HUBGrade", entwicklungsfeld: "1,2,3", thema: "Entwicklung eines bundesweiten Weiterbildungs-portals des Handwerks", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Handwerk", projektzieleschwerpunkte: "Vernetzung bestehender Weiterbildungsplattformen, Weiterbildungsangebote, Verwaltungssysteme und Lernmanagementsysteme der handwerklichen Bildungsanbietenden mit intelligenter Suchfunktion und Single-Sign-On", technologischesziel: "API-Entwicklung für Weiterbildungsplattformen (ODAV AG, UNIPLUS und B & E), SSO, Learning Record Store mit E-Portfolio, Digitale Zertifikate (EUROPASS und ProNet-Handwerk), intelligente Suche mit Chatbot (Framework Chatterbox)", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "9", name: "IWWB-PLUS", entwicklungsfeld: "2", thema: "Personalisierte Lernumgebung und Suche ", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergeordnet", projektzieleschwerpunkte: "Implementierung von dialogischen Technologien, Light Assessments und Interoperabilität mit externen Informationsanbietern", technologischesziel: "Schaffung von personalisierten Suchfunktionen mit einem Chatbot, Empfehlungsmaschine, Natural Language Processing", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "10", name: "KAINE", entwicklungsfeld: "3", thema: "Steigerung der Effizienz, Effektivität und Nachhaltigkeit des Lernens auf Weiterbildungsplattformen durch smarte, individuelle Lernmaterialbereitstellung und dialogorientiertem Tutoringsystem", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "produzierendes Gewerbe", projektzieleschwerpunkte: "Lernassistenzsystem mit individuellen Learning Journeys, individuelle Lernverlaufsbegleitung durch ein dialogorientiertes Tutorsystem, KI-basierte adaptive Erstellung von individuellen Lernpfaden, Voice- und Chatbot basiertes Lerntutoringsystem", technologischesziel: "KI-basierte Lernpfade, Voice- und Chatbot, LMS Plugin (moodle), Ontologien", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "11", name: "KAMAELEON", entwicklungsfeld: "3", thema: "Kontextbasierte und adaptive Maßnahmen für effektive Lernunterstützung in der Online-Weiterbildung", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend (Weiterbildungsangebote im Bereich Digitalisierung, Daten- und Projektmanagement)", projektzieleschwerpunkte: "KI-basierte Personalisierungskonzepte,  Integration innerer und äußerer Lernfaktoren, die den Lernerfolg beeinflussen", technologischesziel: "ML-basierte Personalisierung und Adaption von Lerninhalten, Integration in bestehende AWS Cloudplattform, Serverless Architektur, GraphQL, NoSQL DB, Angular, Snowflake Datwarehouse", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "12", name: "KI4CoLearnET", entwicklungsfeld: "1,2,3", thema: "KI für kompetenzbasiertes Lernen im Cluster Energietechnik", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Energietechnik", projektzieleschwerpunkte: "Serious Games mit Schwierigkeitsanpassung und adaptiven Lernpfaden", technologischesziel: "Baukastensystem für Serious Games, KI zur Schwierigkeitsanpassung", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "13", name: "KIM", entwicklungsfeld: "2", thema: "Künstliche Intelligenz als Mentoring-Lösung für lebenslanges Lernen", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend", projektzieleschwerpunkte: "verzahntes bzw. rückgekoppeltes System, welches auf Basis der erkannten Trends und vorhandener Kompetenzen eine Prognose geeigneter Lerneinheiten liefert", technologischesziel: "CV Extraktion, adaptive Lernpfade, Trenderkennung", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "14", name: "KIPerWeb", entwicklungsfeld: "2,3", thema: "KI-gestützte Personalisierung in der berufsbezogenen Weiterbildung", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend", projektzieleschwerpunkte: "Verbesserung unterschiedlicher Plattformen, Synergien durch gemeinsame Arbeit", technologischesziel: "Adaptive Lernpfade und personalisierte Kursempfehlungen (Empfehlungssysteme)", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "15", name: "KIRA", entwicklungsfeld: "2,3", thema: "KI-gestütztes Matching individueller und arbeitsmarktbezogener Anforderungen für die berufliche Weiterbildung", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend, Fokus auf IT-Qualifikationen in transformationsintensiven Branchen", projektzieleschwerpunkte: "Nutzendenzentrierte Individualisierung von beruflichen Lernangeboten mit Bezug zu unternehmens- und arbeitsmarktpolitischen Erfolgsmerkmalen", technologischesziel: "Modellierung von Lernformen, -bedarfen und -erfolgen; Empfehlungen von Lerninhalten für Lernende; Entwicklung von KI-Service-Modulen; Reporting über Optimierungsmöglichkeiten für Plattformbetreiber:innen (am Beispiel WBS TRAINING AG)", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "16", name: "KIRA_Pro", entwicklungsfeld: "3", thema: "KI-basierter Rollennavigator und automatisierte Lernpfadermittlung zur beruflichen Weiterbildung im produzierenden Gewerbe", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Produzierendes Gewerbe", projektzieleschwerpunkte: "Identifikation von am besten geeigneten Mitarbeiter:innen für Weiterbildungen in Trendthemen der digitalen Transformation unter Berücksichtigung der Unternehmensziele.", technologischesziel: "Kompetenzerfassung, Pfadsuche auf Kompetenzgraph", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "17", name: "KIWI", entwicklungsfeld: "2 (untergeordnet 3)", thema: "Anwendung bzw. Bereitstellung von AR/VR-basierten Lerninhalten auf Smartphones im Bereich „Cobots“ und die KI-gestützte Identifikation von Lernpräferenzen bzw. passgenaue Bereitstellung von Lerninhalten", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Maschinenbau (kollaborative Robotik)", projektzieleschwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, VR/AR, mobile und VR-Equipment, personalisierte Lernpfade und Userprofile", technologischesziel: "strenge Trennung zwischen Content (Unreal Engine) und Kubernetes Container (Flutter für native Apps, Python / TensorFlow, mlflow für KI / Microservice-spezifische DBs (MongoDB, Postgresql, Minio) / Keycloak für ID / Spring Boot für Backend)", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "18", name: "KUPPEL", entwicklungsfeld: "3", thema: "KI-unterstützte plattformübergreifende Professionalisierung erwachsenen-pädagogischer Lehrkräfte", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend, Fokus auf die digitalen Kompetenzen Lehrender", projektzieleschwerpunkte: "Zusammenführung von Angeboten zweier existierender Plattformen, Ergänzung um Adaptivität und Zertifikate", technologischesziel: "Lernbereiche vhs-DTrain (vhs cloud) und EULE (wb-Web) verbinden, cloudbasiertes Multiagentensystem, Lernvorschläge, Kollaboration, Fälschungs- und identitätssichere Zertifikate", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "19", name: "LIMo", entwicklungsfeld: "2", thema: "Unterstützung der Durchführung und Management betrieblicher Weiterbildung, um vermitteltes Wissen bedarfsgerecht zur Verfügung zu stellen und neue Lernangebote zu schaffen", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Industrie", projektzieleschwerpunkte: "Sicher & mobil, informell & partizipativ, individuell & unterstützt", technologischesziel: "Empfehlungssystem", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "20", name: "LiSiL", entwicklungsfeld: "3", thema: "Smarte Lernwelten im Sozialwesen – innovative digitale Lernräume für die hybride Vermittlung sensibler Weiterbildungsthemen", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Sozialwesen", projektzieleschwerpunkte: "Neue Konzepte für die Vermittlung von sensiblen Themen, Erkennung dysfunktionaler emotionaler Belastung im digitalen Raum", technologischesziel: "Sentiment Analyse aus Nutzerverhalten zur Bestimmung dysfunktionaler emotionaler Belastung", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "21", name: "MINDED_RUHR", entwicklungsfeld: "1,3", thema: "Aufbau eines offenen Systems von digitalen, KI-gestützten Weiterbildungsangeboten verschiedener Plattformen und Formaten der DHAR und Vernetzung mit Moodle.", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Gesundheitswesen, Pflege am Beispiel der Demenz", projektzieleschwerpunkte: "Anbieter- und plattformübergreifende Bereitstellung von Bildungsinhalten, Schnittstellenentwicklung", technologischesziel: "Verknüpfung von Moodle-Plattformen mit Tutoolio zum Pooling von Content, KI-unterstützte, bedarfsorientierte Bereitstellung von Lerninhalten", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "22", name: "MyEduLife", entwicklungsfeld: "2", thema: "Die Blockchain als Werkzeug zur dezentralen Speicherung individueller Weiterbildungsbiographien, Entwicklung und Erprobung von Werkzeugen zur Bearbeitung und Präsentation von Qualifikationsportfolios", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend", projektzieleschwerpunkte: "Standardisierung von Bildungserwerben, Blockchain für Bildungserwerbsdokumentation", technologischesziel: "Blockchain mit Second Layer", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "23", name: "NetOEV", entwicklungsfeld: "1,2", thema: "Plattformvernetzung für personalisierte Weiterbildung und kooperativen Wissensaustausch in der Mobilitätsbranche", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Mobilitätsbranche", projektzieleschwerpunkte: "kooperativer Wissensaustausch, formelle und informelle Weiterbildung, Sichtbarkeit von Expertise, nutzerzentrierte Lernerfahrung", technologischesziel: "Vernetzung vieler Plattformen durch Schnittstellen mit übergreifender Auswertung, um bessere Lerninhalte durch Recommender System zu empfehlen und Expertise branchenweit sichtbar zu machen", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "24", name: "OncaPflege", entwicklungsfeld: "2,3", thema: "Entwicklung und Erprobung einer digitalen Plattform für den spezifischen Zielbereich der beruflichen Pflege mit adaptiven Lernpfaden", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Pflege", projektzieleschwerpunkte: "Qualitative Verbesserung bestehender Weiterbildungsplattformen durch digitale Lehr- und Lernformen sowie die Untersuchung von Weiterbildungsbeteiligung und -verhalten", technologischesziel: "KI-unterstützte Lehr- und Lernangebote (Recommender- und Unterstützungssysteme; Kompetenzerfassung und -verarbeitung; Verbindung von Learning Nuggets und Metadaten; Motivations-Bot; KI-unterstützte Simultanübersetzung; Badges und Zertifikate mittels Zertifikats-Blockchain; Berücksichtigung von Datenethik-Standards", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "25", name: "PolyEx", entwicklungsfeld: "1,2,3", thema: "Polymer-Excellence - Weiterbildungsplattform für die kunststoffverarbeitende Industrie", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "kunststoffverarbeitende Industrie", projektzieleschwerpunkte: "effiziente Filter- und Sortierungsfunktionen, Personal Learning Environment, adaptives Lernen durch KI-basiertes Empfehlungssystem mit einem Chatbot als Weiterbildungsassistenten, Kompetenzmatrix, Integration von Lernformaten", technologischesziel: "Lehrinhalte entweder nativ über Online-Formular, Upload (JSON-Datei), Webscrapers oder API, persönliche Lernumgebung (Personal Learning Environment – PLE), KI-basiertes Empfehlungssystem und Weiterbildungsassistent mit Natural Language Processing (NLP), Kompetenzmatrix", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "26", name: "SEARCH", entwicklungsfeld: "2,3", thema: "Entwicklung eines KI-gestützten Assistenzsystems zum adaptiven Lernen und Ausbau der Lernplattform MLS für die bedarfsgerechte Weiterbildung", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend, Fokus auf das produzierende Gewerbe", projektzieleschwerpunkte: ": Pädagogisch-didaktisch und technologische Aufbereitung von Lerninhalten sowie Aufzeigen von individuellen und flexibel anpassbaren Lerneinheiten und Lernpfade für Lernende", technologischesziel: "Anreicherung und Strukturierung von Informationen; Komposition von Lernpfaden; Integration eines KI-gestützten Assistenzsystems; Einbinden von Methoden zur Spracherkennung sowie zur text- und sprachorientierten Videoanalyse; Entwicklung einer Suchfunktion zur intelligenten Suche", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "27", name: "SG4BB", entwicklungsfeld: "1,2,3", thema: "Serious Games für die berufliche Bildung", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend", projektzieleschwerpunkte: "KI-gestützte spielerische Lehr- und Lernangebote, „Steam“ für Serious Games, Metadaten-orientierte Suchmaschine, neuer Metadatenstandard ", technologischesziel: "Verknüpfung von Learning Record Store, LMS, Marktplatz, Suchmaschine und Serious Games, Anbindung von Drittanbietern", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "28", name: "SMALO", entwicklungsfeld: "1,2,3", thema: "Smartes Lernen in der Logistik", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Logistik", projektzieleschwerpunkte: "KI für erhöhte Beteiligung, bessere Kohärenz und Personalisierung, Vernetzung, Bedarfsorientierung, Zertifizierung, Lern-Ökosystem, Datensicherheit (DSGVO, BSI)", technologischesziel: "KI für Beteiligung, Kohärenz und Personalisierung, datensicherer Weiterbildungsraum, Überarbeitung der Plattformarchitektur ", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "29", name: "StuBu", entwicklungsfeld: "3", thema: "StudyBuddy: Ein virtueller Companion für die berufliche Weiterbildung", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend", projektzieleschwerpunkte: "KI-basierter Funktionsbaukasten für einen virtuellen Companion in der beruflichen Weiterbildung. Erkennung von Lernpräferenzen und Eingehen auf individuelles Lernverhalten.", technologischesziel: "ML-basierter virtueller Companion, Anbindung an Bot Engine, automatische ML-basierte Lern-Persönlichkeitsanalyse, Nutzung von NPL, NLU und NLG. Node.js, Mongo DB, Rest API, RASA", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "30", name: "TRIPLEADAPT", entwicklungsfeld: "1,2,3", thema: "Adaptive, interoperationale Weiterbildungsplattformen durch einen digitalen Drilling", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend", projektzieleschwerpunkte: "Adaptiver Drilling, Adaptive Lernpfade, plattformübergreifende Lernpfade, Adaptive Assistenz in arbeitsplatzähnlicher Umgebung, Common Learning Middleware (CLM), Micro-Zertifikate", technologischesziel: "Erstellung von KI-Diensten auf Basis Low Code Mendix Plattform für Lernen in der digitalen Produktion, Nutzung von Simulationen und Prozessdaten des digitalen Zwillings", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "31", name: "VerDatAs", entwicklungsfeld: "1,2,3", thema: "Vernetzung und datengestützte Assistenz für die berufliche Bildung", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend", projektzieleschwerpunkte: "Plattformvernetzung zu digitalem Marktplatz, Unterstützung von Lehrenden und Lernenden, innovativer Weiterbildungsraum für Informatiker, Ingenieure und qualifizierte Quereinsteiger, pädagogisch-psychologisches Ordnungssystem, Qualifikations-Matching", technologischesziel: "LMS ILIAS zur Plattformvernetzung, Aufbau eines Learning Record Store, nutzerzentrierte KI für variantenreiche Szenarien beruflicher und betrieblicher Bildung, Entwicklung eines tutoriellen Assistenzsystems", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "32", name: "Wbsmart", entwicklungsfeld: "3", thema: "Bildungswissenschaftliche Grundlegung eines smarten KI-basierten digitalen Weiterbildungsraums für die Altenhilfe mittels personalisierter Empfehlungs-systeme", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "Pflege", projektzieleschwerpunkte: "KI-basiertes, personalisiertes Empfehlungssystem, intelligente Aufbereitung und Empfehlung von Lernangeboten auf adaptiven Lernpfaden, basierend auf individueller Präferenz, Lernfortschritt, Kenntnisstand und auf einem Wissens-modell als Wissensgraph, intelligentes tutorielles Assistenzsystem, Einbeziehung vorhandener OER Ressourcen", technologischesziel: "semantischer Wissensgraph, White-Box KI, Recommender System", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "33", name: "Weiterbildung 4.OWL", entwicklungsfeld: "2,3", thema: "Entwicklung eines didaktischen und technisch-wirtschaftlichen Instrumentariums zur nutzer- und qualitätszentrierten Verbesserung von intermediären Marktplatz- und Lernplattformen", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend, Fokus produzierendes Gewerbe", projektzieleschwerpunkte: "Nutzerorientierte Gestaltung des digitalen Lernens und der Kompetenzentwicklung; Technisch-wirtschaftliche Gestaltung des plattformbasierten Weiterbildungsraums", technologischesziel: "Tools zur Erfassung strukturierter Bildungsangebotsanfragen und zur Erstellung qualitätsorientierter Lernangebote, Anbindung der Tools an LMS und Spezifikation von Schnittstellen, Kollaborative Bearbeitung von Anfragen & Designs, Anbindung der Tools an übergreifende Matching-Plattform, Rahmenwerk für einzuhaltende Sicherh.-Stand.", mehrwert: "ILIAS", verbundpartner: "" },
    { id: "34", name: "WISYatKI", entwicklungsfeld: "1,2", thema: "WISY@KI-Dein persönlicher Weiterbildungsscout", zielgruppe: "Weiterbildungsinteressierte", innovation: "KI-basierte Personalisierung und Recommendersystem, Erfassung von (informellen) Kompetenzen, Erstellung eines individuellen Profils, kontinuierliche Qualitätsmessung der Empfehlungen, Vernetzung von Weiterbildungsanbietern/-inhalten", weiterbildungsplattform: "ILIAS", branche: "übergreifend", projektzieleschwerpunkte: "Verbesserung der Suche von regionalen Weiterbildungsangeboten / Kursen insbesondere hinsichtlich der Treffgenauigkeit zu den eigenen Kompetenzen / Weiterbildungszielen. Entwicklung und Integration einer kompetenzorientierten Suchfunktion in die WISY-Kursportale in Schleswig-Holstein und Hessen zur Optimierung der Kursergebnisse.", technologischesziel: "Entwicklung der Kursportale Schleswig-Holstein und Hessen mittels Einsatz von kompetenzorientierten Empfehlungssystemen zur Verbesserung der persönlichen Suchergebnisse.", mehrwert: "ILIAS", verbundpartner: "" },

];

//#endregion ///-----C END Set Data----------------------------------------------------------------------------------------------

