//#region ///--------C Set Data------------------------------------------------------------------------------------------------
var projekteNamen = ['ADAPT', 'APOLLO', 'ComP-ASS', 'DigiPlat4Train', 'EduPLEx_API', 'ELe-com', 'ExpanderWB3', 'HUBGrade', 'IWWB-PLUS', 'KAINE', 'KAMAELEON', 'KI4CoLearnET', 'KIM', 'KIPerWeb', 'KIRA', 'KIRA_Pro', 'KIWI', 'KUPPEL', 'LIMo', 'LiSiL', 'MINDED_RUHR', 'MyEduLife', 'NetOEV', 'OncaPflege', 'PolyEx', 'SEARCH', 'SG4BB', 'SMALO', 'StuBu', 'TRIPLEADAPT', 'VerDatAs', 'WBsmart', 'Weiterb.4.OWL', 'WISYatKI'];
var projekteAuspraegung = ['Dim k.A.', 'Dim in Ansätzen.', 'Dim adressiert.', 'Dim ausgepr.'];


/// Zustand welche Projekte gerade in Einzeplorjektanzeige an sind
var projekteEinzelStatusInLegende = Array(projekteNamen.length).fill(0);
//console.log("projekteEinzelStatusInLegende:" + projekteEinzelStatusInLegende);

/// daten und Beschreibung der Oberdimensionen 
var dataDimensionenStandAntrag = [
    { id: 1, value1: 16, value2: 25, value3: 59, dimension: "Interoperabilität durch offene Bildungstandards", nameKurz: "Interoperabilität", name: "Interoperabilität durch offene Bildungstandards", textLang: "Fragen der unterstützten Standards und Technologien zur Etablierung\neines gemeinsamen digitalen Weiterbildungsraumes, z. B. zu Kompe-\ntenzen und Wissen, sowie dem Austausch von Kurs-, Leistungs- oder\n Lernergebnissen und Lerninhalten." },
    { id: 2, value1: 38, value2: 27, value3: 35, dimension: "Algorithmen zur Unterstützung der Lernenden", nameKurz: "Algorithmen", name: "Algorithmen zur Unterstützung der Lernenden", textLang: "Fragen des Einsatzes und der Entwicklung von Algorithmen z.B. zur\nSprachverarbeitung (NLP, NLU, NLG), Analyse des Lernverhaltens\n(Learning Analytics) oder der Anpassungsfähigkeit von Lernangeboten\nund -empfehlungen sowie Suchfunktionen durch Nutzende." },
    { id: 3, value1: 5, value2: 23, value3: 72, dimension: "Mitgestaltung, Zugänglichkeit und Zusammenarbeit", nameKurz: "Mitgestaltung", name: "Mitgestaltung, Zugänglichkeit und Zusammenarbeit", textLang: "Spektrum der geplanten und umgesetzten Möglichkeiten der Beteiligung,\nZusammenarbeit und Mitgestaltung von Lerninhalten durch Nutzende\nsowie Lösungen zur Nutzbarkeit und zum Nutzungserlebnis." },
    { id: 4, value1: 21, value2: 29, value3: 50, dimension: "Nachnutzbarkeit durch Dritte", nameKurz: "Nachnutzbarkeit", name: "Nachnutzbarkeit durch Dritte", textLang: "Fragen der Offenheit der eingesetzten und zu entwickelnden Systeme,\nModelle und Funktionalitäten bspw. als Open Source Software oder über\ngut dokumentierte API." },
    { id: 5, value1: 12, value2: 56, value3: 32, dimension: "Informationssicherheit & Datensouveränität", nameKurz: "Informationssicherheit", name: "Informationssicherheit & Datensouveränität", textLang: "Fragen der eingesetzten oder zu entwickelnden Sicherheits- und Schutz-\nmaßnahmen im Rahmen von Plattformen und Funktionalitäten im Sinne\nder gesetzlichen Anforderungen sowie darüber hinaus Fragen der Daten-\nethik und Selbstbestimmung im Umgang mit und bei der Ablage von\npersonenbezogenen Informationen." },
    { id: 6, value1: 30, value2: 40, value3: 30, dimension: "Sonstige technologische Aspekte", nameKurz: "Sonstige", name: "Sonstige technologische Aspekte", textLang: "Weitere technologische Merkmale in den Vorhaben die nicht durch die\nanderen Dimensionen abgedeckt sind." },

];
var dataDimensionenStandZeitpunktA = dataDimensionenStandAntrag; //Zeitpunkt A ist 1. auf slider

var dataDimensionenStandDezember2022 = [
    { id: "1", value1: 20, value2: 33, value3: 47, dimension: "Interoperabilität durch offene Bildungstandards", nameKurz: "Interoperabilität", name: "Interoperabilität durch offene Bildungstandards", textLang: "Fragen der unterstützten Standards und Technologien zur Etablierung\neines gemeinsamen digitalen Weiterbildungsraumes, z. B. zu Kompe-\ntenzen und Wissen, sowie dem Austausch von Kurs-, Leistungs- oder\n Lernergebnissen und Lerninhalten." },
    { id: "2", value1: 43, value2: 23, value3: 34, dimension: "Algorithmen zur Unterstützung der Lernenden", nameKurz: "Algorithmen", name: "Algorithmen zur Unterstützung der Lernenden", textLang: "Fragen des Einsatzes und der Entwicklung von Algorithmen z.B. zur\nSprachverarbeitung (NLP, NLU, NLG), Analyse des Lernverhaltens\n(Learning Analytics) oder der Anpassungsfähigkeit von Lernangeboten\nund -empfehlungen sowie Suchfunktionen durch Nutzende." },
    { id: "3", value1: 10, value2: 29, value3: 61, dimension: "Mitgestaltung, Zugänglichkeit und Zusammenarbeit", nameKurz: "Mitgestaltung", name: "Mitgestaltung, Zugänglichkeit und Zus.arbeit", textLang: "Spektrum der geplanten und umgesetzten Möglichkeiten der Beteiligung,\nZusammenarbeit und Mitgestaltung von Lerninhalten durch Nutzende\nsowie Lösungen zur Nutzbarkeit und zum Nutzungserlebnis." },
    { id: "4", value1: 26, value2: 31, value3: 43, dimension: "Nachnutzbarkeit durch Dritte", nameKurz: "Nachnutzbarkeit", name: "Nachnutzbarkeit durch Dritte", textLang: "Fragen der Offenheit der eingesetzten und zu entwickelnden Systeme,\nModelle und Funktionalitäten bspw. als Open Source Software oder über\ngut dokumentierte API." },
    { id: "5", value1: 15, value2: 58, value3: 27, dimension: "Informationssicherheit & Datensouveränität", nameKurz: "Informationssicherheit", name: "Informationssicherheit & Datensouveränität", textLang: "Fragen der eingesetzten oder zu entwickelnden Sicherheits- und Schutz-\nmaßnahmen im Rahmen von Plattformen und Funktionalitäten im Sinne\nder gesetzlichen Anforderungen sowie darüber hinaus Fragen der Daten-\nethik und Selbstbestimmung im Umgang mit und bei der Ablage von\npersonenbezogenen Informationen." },
    { id: "6", value1: 34, value2: 27, value3: 39, dimension: "Sonstige technologische Aspekte", nameKurz: "Sonstige", name: "Sonstige technologische Aspekte", textLang: "Weitere technologische Merkmale in den Vorhaben die nicht durch die\nanderen Dimensionen abgedeckt sind." },

];
var dataDimensionenStandZeitpunktB = dataDimensionenStandDezember2022; //Zeitpunkt B ist 2. auf slider und stellt Stand Dezember 2022 dar

var dataDimensionenStandAugust2023 = [
    { id: "1", value1: 21, value2: 28, value3: 51, dimension: "Interoperabilität durch offene Bildungstandards", nameKurz: "Interoperabilität", name: "Interoperabilität durch offene Bildungstandards", textLang: "Fragen der unterstützten Standards und Technologien zur Etablierung\neines gemeinsamen digitalen Weiterbildungsraumes, z. B. zu Kompe-\ntenzen und Wissen, sowie dem Austausch von Kurs-, Leistungs- oder\n Lernergebnissen und Lerninhalten." },
    { id: "2", value1: 43, value2: 22, value3: 35, dimension: "Algorithmen zur Unterstützung der Lernenden", nameKurz: "Algorithmen", name: "Algorithmen zur Unterstützung der Lernenden", textLang: "Fragen des Einsatzes und der Entwicklung von Algorithmen z.B. zur\nSprachverarbeitung (NLP, NLU, NLG), Analyse des Lernverhaltens\n(Learning Analytics) oder der Anpassungsfähigkeit von Lernangeboten\nund -empfehlungen sowie Suchfunktionen durch Nutzende." },
    { id: "3", value1: 12, value2: 32, value3: 56, dimension: "Mitgestaltung, Zugänglichkeit und Zusammenarbeit", nameKurz: "Mitgestaltung", name: "Mitgestaltung, Zugänglichkeit und Zusammenarbeit", textLang: "Spektrum der geplanten und umgesetzten Möglichkeiten der Beteiligung,\nZusammenarbeit und Mitgestaltung von Lerninhalten durch Nutzende\nsowie Lösungen zur Nutzbarkeit und zum Nutzungserlebnis." },
    { id: "4", value1: 30, value2: 29, value3: 41, dimension: "Nachnutzbarkeit durch Dritte", nameKurz: "Nachnutzbarkeit", name: "Nachnutzbarkeit durch Dritte", textLang: "Fragen der Offenheit der eingesetzten und zu entwickelnden Systeme,\nModelle und Funktionalitäten bspw. als Open Source Software oder über\ngut dokumentierte API." },
    { id: "5", value1: 15, value2: 57, value3: 28, dimension: "Informationssicherheit & Datensouveränität", nameKurz: "Informationssicherheit", name: "Informationssicherheit & Datensouveränität", textLang: "Fragen der eingesetzten oder zu entwickelnden Sicherheits- und Schutz-\nmaßnahmen im Rahmen von Plattformen und Funktionalitäten im Sinne\nder gesetzlichen Anforderungen sowie darüber hinaus Fragen der Daten-\nethik und Selbstbestimmung im Umgang mit und bei der Ablage von\npersonenbezogenen Informationen." },
    { id: "6", value1: 33, value2: 33, value3: 34, dimension: "Sonstige technologische Aspekte", nameKurz: "Sonstige", name: "Sonstige technologische Aspekte", textLang: "Weitere technologische Merkmale in den Vorhaben die nicht durch die\nanderen Dimensionen abgedeckt sind." },

];
var dataDimensionenStandZeitpunktC = dataDimensionenStandAugust2023; // 3. Position auf Zeit slider

var dataDimensionen = dataDimensionenStandZeitpunktA;
var dataOhneLetzteDimension = dataDimensionen.slice(0, dataDimensionen.length - 1); //Für Initiale Anzeige Kopie des Datenarray aber ohne das letzte element= Dimension Sontiges

/// Daten für Beschreibung der Unterdimesionen, Prozent und absolut Werte der UnterDim sind jetzt in datensatz Einzeldimension

var dataBeschreibungUnterDimensionen = [ /// hier nur noch Text beschreibungen für die UDims, GesamtValues absolut und Prozent kommen aus Einzeldatensatz
    { dimension: "Kompetenzstandards", nameKurz: "Kompetenzstand.", name: "Kompetenzstandards", oberdimension: "Interoperabilität", textLang: "(ESCO, EQR, Europass) Kompetenzstandards dienen der Beschreibung\nvon Fähigkeiten, Qualifikationen und Berufen. Sie können dazu genutzt\nwerden den Weiterbildungsbedarf der Lernenden standardisiert zu\nerheben, Lernziele zu definieren, Lerninhalte einer Weiterbildungsplatt-\nform zu beschreiben und bei Bildungsnachweisen das erreichte\nKompetenzlevel zu dokumentieren." },
    { dimension: "Bildungsnachweise", nameKurz: "Bildungsnachw.", name: "Bildungsnachweise", oberdimension: "Interoperabilität", textLang: "Standards zum Austausch von digitalen Bildungsnachweisen wie  Euro-\npass und EDCI. Es werden einheitliche digitale Nachweise für\nLernleistungen und Qualifikationen ausgestellt. EDCI definiert auch ein\ndazu passendes Datenmodell." },
    { dimension: "Standards Lerninhalte", nameKurz: "Lerninhalte", name: "Standards Lerninhalte", oberdimension: "Interoperabilität", textLang: "Standards zum Datenaustausch von Lerninhalten wie z.B. HP5, xAPI und\nSCORM. Es wird die Kommunikation zwischen Lernmanagementsystemen\nermöglicht, indem Lerninhalte standardisiert beschrieben werden. Damit\nkönnen auch Autorenwerkzeuge Lerninhalte erstellen die in verschiedenen\nLMS verwendet werden können. xAPI geht über SCORM hinaus indem\nzusätzlich Aktivitäten der Lernenden beschrieben und zwischen LMS\nausgetauscht werden können" },
    { dimension: "Wissensrepräsen.", nameKurz: "Wissensrepräs.", name: "Wissensrepräsentation", oberdimension: "Interoperabilität", textLang: "Bei Wissensrepräsentationen werden eine Menge von Begriffen und ihre\nBeziehung untereinander beschrieben. Damit kann „Wissen“\n(z.B. in der Pflege) maschinenlesbar abgespeichert und verarbeitet werden." },
    { dimension: "Intelligente Suche", nameKurz: "Intellig. Suche", name: "Intelligente Suche", oberdimension: "Algorithmen", textLang: "Intelligente Suchfunktionen gehen über die einfache Suche nach Wörtern\nin Text hinaus. Dies umschließt Suchalgorithmen von traditionellen,\nintelligenten Such-Algorithmen, welche die regelbasierte Verarbeitung\nvon Suchwörtern durchführen, bis hin zu solchen, welche menschliche\nSprache verstehen und die semantische Suche mit einem kontext-\nbezogenen Verständnis der Abfrage ermöglichen. Maschinelles und\nDeep Learning werden eingesetzt, um dem Kern der Suchabfrage auf\nden Grund zu gehen." },
    { dimension: "Learning Analytics", nameKurz: "Learn. Analytics", name: "Learning Analytics", oberdimension: "Algorithmen", textLang: "Learning Analytics verwendet Datenaggregation, Data Mining und\nweitere Algorithmen, um Trends und Bewertungsmetriken im Zeit\nverlauf zu verstehen. Je nach Entwicklungsstufe des zugrundeliegenden\nSystems bietet dieses einen Einblick in vergangene Lernerfahrungen,\nerklärt die Ursachen von Ereignissen im Lernverlauf und gibt Empfeh-\nlungen zu möglichen zukünftigen Lernereignissen." },
    { dimension: "Adaptive Lerninh.", nameKurz: "Adapt. Lerninh.", name: "Adaptive Lerninhalte", oberdimension: "Algorithmen", textLang: "Adaptive Lerninhalte und –pfade passen die Art der Wissensvermittlung\nan den Wissensstand, die Lernpräferenzen und das Umfeld des Lernenden\nan, um einen für alle Lernenden vergleichbaren Lernerfolg zu erzielen." },
    { dimension: "Recommendersysteme", nameKurz: "Recomm. Systeme", name: "Recommendersysteme", oberdimension: "Algorithmen", textLang: "Lernempfehlungssysteme sind nutzerzentrierte Recommender Systeme\nfür Lernplattformen. Auf Basis vorheriger Nutzerentscheidungen werden\npassende Lerninhalte empfohlen." },
    { dimension: "Kollaboration", nameKurz: "Kollaboration", name: "Kollaboration", oberdimension: "Mitgestaltung", textLang: "Kollaboration bedeutet, gemeinsam mit anderen Lernenden zu arbeiten.\nBei der Kollaboration zwischen Lernenden sind alle Lernenden am gemein-\nsamen Prozess, bei dem gemeinsam ein Ergebnis konstruiert wird, in allen\nArbeitsschritten beteiligt und bringen sich in den Prozess ein. Das\nVorhaben sollte adäquaten digitalen Tool zur Unterstützung des gemein-\nsamen Lernens einsetzten." },
    { dimension: "Peer-Support", nameKurz: "Peer-Support", name: "Peer-Support", oberdimension: "Mitgestaltung", textLang: "Lernpatenschaften/ Peer-Support bedeutet die Unterstützung beim Lernen\ndurch einen Mentor. Bei Lernpatenschaften und Peer-Support arbeiten die\nLernenden bzw. Lehrenden zusammen und unterstützen sich, um Leistungs-\ndefizite auszugleichen. Das Vorhaben sollte adäquaten digitalen Tool zur\nUnterstützung des Lernen mit einem Mentor einsetzen." },
    { dimension: "Partizipation", nameKurz: "Partizipation", name: "Partizipation", oberdimension: "Mitgestaltung", textLang: "(Partizipative Gestaltung) Bei der partizipativen Gestaltung werden die\n (Bedürfnisse der) Stakeholder bei der Anpassung der Plattform mitein-\nbezogen. Dieses kann z.B. auch durch den Einsatz von KI geschehen.\nPlattform bietet Feedbackmöglichkeiten an. " },
    { dimension: "Accessibility", nameKurz: "Accessibility", name: "Accessibility", oberdimension: "Mitgestaltung", textLang: "(Accessability und Usability) Web-Zugänglichkeit (Accessibility) bezieht\nsich auf die inklusive Praxis, Websites für Menschen aller Fähigkeiten und\nBehinderungen nutzbar zu machen. Ein internationaler Standard wird mit\nden Content Accessibility Guidelines (WCAG) des W3C gesetzt (seit 2012\n ISO-Standard ISO/IEC 40500:2012). Die WCAG bieten\nEmpfehlungen für die barrierefreie Gestaltung von Webseiten und\nmobilen Anwendungen. Die WCAG 2.1 umfassen 13 Richtlinien, die vier\nübergeordneten Prinzipien zuzuordnen sind: Wahrnehmbarkeit, \nedienbarkeit, Verständlichkeit und Robustheit. Das Vorhaben sollte die\nGuidelines und / oder Prinzipien umsetzten." },
    { dimension: "OSS & KI Modelle", nameKurz: "OSS & KI Modelle", name: "OSS & KI Modelle", oberdimension: "Nachnutzbarkeit", textLang: "Lizenzierung der Software als Open Source & Lizenzierung der KI Modelle\nals Open Source, Verwendung von „Standard“ KI-Bibliotheken\n(etwa Keras, pytorch, TensorFlow) und Publikation des trainierten Modells\n(etwa in binärer Form). Im besten Fall wird zusätzlich auch der Code zum\nTraining des Models publiziert. " },
    { dimension: "OSS LMS & Plugin", nameKurz: "OSS LMS & Plugin", name: "OSS LMS & Plugin", oberdimension: "Nachnutzbarkeit", textLang: "(Free Open Source Software, Nutzung von Open Source Lernmanagement-\nsystemen & Erstellung von Plugins) Basis der Software-Entwicklung ist ein\nFOSS LMS. Wesentlich ist, dass Quellcode des Ursprungsprojekts\ngewartet wird, und dies auch zukünftig zu erwarten ist. Das Projekt muss\ndarüber hinaus glaubhaft machen, dass eine Nachnutzung möglich ist, etwas\ndurch Implementation als ein Plugin und Dokumentation der Integration.\nIm besten Fall wird das Plugin in einem „offiziellen“ Kanal des LMS publiziert." },
    { dimension: "API Zugriff", nameKurz: "API Zugriff", name: "API Zugriff", oberdimension: "Nachnutzbarkeit", textLang: "(Zugriff auf Plattform über gut dokumentierte API Bsp. REST API) Kriterium\nist wie weitreichend die API die Funktionalitäten des Projekts abdeckt. Ist\ndas zentrale Element (etwa das KI Modell) nicht darüber erreichbar, wäre\ndas Kriterium nicht voll erfüllt. Weitere Kriterien sind Dokumentation der\nSchnittstelle, sowie Dauerhaftigkeit der Erreichbarkeit." },
    { dimension: "OER", nameKurz: "OER", name: "OER", oberdimension: "Nachnutzbarkeit", textLang: "(Bereitstellung von Ergebnissen als Open Educational Resources) Die auf\nder Plattform verfügbaren Lerninhalte sind mit einer freien Lizenz publiziert\n(CC, GPL, oder vergleichbar) und glaubhaft dauerhaft publiziert, etwa auf\neiner Drittplattform (Github, Gitlab, OER Drittplattform)." },
    { dimension: "IT-Sicherheit", nameKurz: "IT-Sicherheit", name: "IT-Sicherheit", oberdimension: "Informationssicherheit", textLang: "Aufrechterhaltung der Schutzziele Vertraulichkeit, Integrität und\nVerfügbarkeit von Informationen.  Absicherung der Weiterbildungs-\nPlattform gegen Cyberattacken Datendiebstahl und weitere Sicherheits-\nrisiken.  Berücksichtigung einschlägiger Normen und Standards wie\nISO 27001/27002 oder BSI-Grundschutz. Beachtung der Grundsätze\nsichere Softwareentwicklung" },
    { dimension: "Datenschutz", nameKurz: "Datenschutz", name: "Datenschutz", oberdimension: "Informationssicherheit", textLang: "(Datenschutz und Privacy) Einhaltung der gesetzlichen und vertraglichen\nAnforderungen bzgl. Schutz personenbezogener Daten Beachtung der\nAnforderungen der ISO 27701 in Ergänzung der ISO 27001/27002 unter\nanderem privacy by design/by default, Anonymisierung, Pseudo¬\nnymisierung, Mandaten Trennung. Informations- und Transparenz-\npflichten. Umgang mit Betroffenenrechten, Übernahme von Corporate\nDigital Responsibility (CDR)" },
    { dimension: "Datenethik", nameKurz: "Datenethik", name: "Datenethik", oberdimension: "Informationssicherheit", textLang: "Die Digitale Ethik oder Datenethik beschäftigt sich mit den sittlichen\nNormsetzungen, die für Digitalisierung, Big Data und KI gelten sollen.\nDie Vorhaben sollten berücksichtigen, welchen Bias die Daten möglicherweise\nenthalten und auch wie ethisch verantwortungsvoll mit den gesammelten\nDaten umgegangen werden kann. Zudem müssen in den Projekten die Ethik-\nLeitlienien für vertrauenswürdige KI enthalten und die Empfehlungen der\nDatenethik-kommission der Bundesregierung beachtet werden." },
    { dimension: "Digitale Identitäten", nameKurz: "Dig. Identitäten", name: "Digitale Identitäten", oberdimension: "Informationssicherheit", textLang: "Mit Digital Credentials sollen mit Hilfe kryptographischer Software Zeug-\nnisse und Leistungsnachweise sicher dokumentiert und gemanaged werden.\nDazu gehören u.a. Authentifizierung, eID, Learning Record Store, Blockchain\nzur fälschungssicheren Ablage als Teil der Digital Credentials Infrastruktur." },

];

var dataUnterDimensionenEinzelStandAntrag = [ /// Array für Radarboard Unterdimensionen und Radarboard Einzelvorhaben zusammen, damit Daten an einer Stelle
    { id: "1", dimension: "Kompetenzstandards", value1: 15, valueProzentGesamt1: 15, value2: 29, valueProzentGesamt2: 29, value3: 56, valueProzentGesamt3: 56, valueGesamt1: 19, valueGesamt2: 10, valueGesamt3: 5, value1: 2, value2: 3, value3: 1, value4: 2, value5: 1, value6: 1, value7: 2, value8: 0, value9: 1, value10: 1, value11: 0, value12: 1, value13: 2, value14: 1, value15: 2, value16: 2, value17: 0, value18: 2, value19: 0, value20: 0, value21: 0, value22: 3, value23: 0, value24: 1, value25: 0, value26: 2, value27: 1, value28: 2, value29: 1, value30: 3, value31: 3, value32: 2, value33: 3, value34: 1 },
    { id: "2", dimension: "Bildungsnachweise", value1: 17, valueProzentGesamt1: 17, value2: 15, valueProzentGesamt2: 15, value3: 68, valueProzentGesamt3: 68, valueGesamt1: 23, valueGesamt2: 5, valueGesamt3: 6, value1: 1, value2: 3, value3: 1, value4: 1, value5: 0, value6: 1, value7: 2, value8: 3, value9: 1, value10: 0, value11: 0, value12: 0, value13: 2, value14: 1, value15: 1, value16: 0, value17: 0, value18: 3, value19: 0, value20: 0, value21: 0, value22: 3, value23: 0, value24: 2, value25: 0, value26: 0, value27: 0, value28: 2, value29: 0, value30: 3, value31: 3, value32: 0, value33: 2, value34: 1 },
    { id: "3", dimension: "Standards Lerninhalte", value1: 15, valueProzentGesamt1: 15, value2: 29, valueProzentGesamt2: 29, value3: 56, valueProzentGesamt3: 56, valueGesamt1: 19, valueGesamt2: 10, valueGesamt3: 5, value1: 1, value2: 1, value3: 0, value4: 2, value5: 2, value6: 0, value7: 2, value8: 0, value9: 1, value10: 1, value11: 1, value12: 0, value13: 0, value14: 0, value15: 2, value16: 0, value17: 1, value18: 0, value19: 1, value20: 1, value21: 3, value22: 0, value23: 2, value24: 2, value25: 2, value26: 2, value27: 3, value28: 3, value29: 0, value30: 2, value31: 3, value32: 2, value33: 3, value34: 0 },
    { id: "4", dimension: "Wissensrepräsen.", value1: 18, valueProzentGesamt1: 18, value2: 26, valueProzentGesamt2: 26, value3: 56, valueProzentGesamt3: 56, valueGesamt1: 19, valueGesamt2: 9, valueGesamt3: 6, value1: 3, value2: 3, value3: 3, value4: 2, value5: 2, value6: 1, value7: 1, value8: 0, value9: 0, value10: 2, value11: 2, value12: 0, value13: 0, value14: 0, value15: 0, value16: 2, value17: 0, value18: 2, value19: 1, value20: 0, value21: 2, value22: 1, value23: 1, value24: 1, value25: 2, value26: 2, value27: 1, value28: 0, value29: 3, value30: 1, value31: 3, value32: 3, value33: 0, value34: 0 },
    { id: "5", dimension: "Intelligente Suche", value1: 20, valueProzentGesamt1: 20, value2: 18, valueProzentGesamt2: 18, value3: 62, valueProzentGesamt3: 62, valueGesamt1: 21, valueGesamt2: 6, valueGesamt3: 7, value1: 3, value2: 1, value3: 1, value4: 1, value5: 1, value6: 0, value7: 3, value8: 3, value9: 3, value10: 1, value11: 2, value12: 0, value13: 0, value14: 2, value15: 0, value16: 0, value17: 0, value18: 0, value19: 1, value20: 0, value21: 1, value22: 0, value23: 1, value24: 2, value25: 2, value26: 3, value27: 3, value28: 2, value29: 1, value30: 1, value31: 3, value32: 1, value33: 0, value34: 2 },
    { id: "6", dimension: "Learning Analytics", value1: 36, valueProzentGesamt1: 36, value2: 26, valueProzentGesamt2: 26, value3: 38, valueProzentGesamt3: 38, valueGesamt1: 13, valueGesamt2: 9, valueGesamt3: 12, value1: 3, value2: 1, value3: 3, value4: 3, value5: 1, value6: 3, value7: 1, value8: 2, value9: 1, value10: 3, value11: 3, value12: 2, value13: 2, value14: 2, value15: 1, value16: 0, value17: 1, value18: 3, value19: 1, value20: 3, value21: 2, value22: 0, value23: 1, value24: 2, value25: 3, value26: 3, value27: 2, value28: 1, value29: 2, value30: 3, value31: 3, value32: 2, value33: 1, value34: 1 },
    { id: "7", dimension: "Adaptive Lerninh.", value1: 44, valueProzentGesamt1: 44, value2: 35, valueProzentGesamt2: 35, value3: 21, valueProzentGesamt3: 21, valueGesamt1: 7, valueGesamt2: 12, valueGesamt3: 15, value1: 2, value2: 1, value3: 3, value4: 3, value5: 2, value6: 3, value7: 2, value8: 0, value9: 2, value10: 3, value11: 3, value12: 3, value13: 3, value14: 3, value15: 2, value16: 3, value17: 2, value18: 3, value19: 2, value20: 3, value21: 2, value22: 0, value23: 0, value24: 1, value25: 2, value26: 3, value27: 3, value28: 1, value29: 2, value30: 3, value31: 2, value32: 3, value33: 0, value34: 2 },
    { id: "8", dimension: "Recommendersysteme", value1: 53, valueProzentGesamt1: 53, value2: 29, valueProzentGesamt2: 29, value3: 18, valueProzentGesamt3: 18, valueGesamt1: 6, valueGesamt2: 10, valueGesamt3: 18, value1: 3, value2: 1, value3: 3, value4: 3, value5: 2, value6: 3, value7: 2, value8: 0, value9: 1, value10: 3, value11: 3, value12: 2, value13: 3, value14: 3, value15: 3, value16: 3, value17: 2, value18: 3, value19: 2, value20: 3, value21: 2, value22: 0, value23: 3, value24: 2, value25: 3, value26: 2, value27: 0, value28: 3, value29: 2, value30: 3, value31: 3, value32: 3, value33: 0, value34: 2 },
    { id: "9", dimension: "Kollaboration", value1: 3, valueProzentGesamt1: 3, value2: 15, valueProzentGesamt2: 15, value3: 82, valueProzentGesamt3: 82, valueGesamt1: 28, valueGesamt2: 5, valueGesamt3: 1, value1: 1, value2: 0, value3: 1, value4: 1, value5: 2, value6: 0, value7: 1, value8: 0, value9: 0, value10: 1, value11: 0, value12: 0, value13: 0, value14: 0, value15: 0, value16: 0, value17: 0, value18: 2, value19: 0, value20: 0, value21: 0, value22: 0, value23: 3, value24: 1, value25: 0, value26: 1, value27: 2, value28: 2, value29: 1, value30: 1, value31: 2, value32: 0, value33: 1, value34: 0 },
    { id: "10", dimension: "Peer-Support", value1: 3, valueProzentGesamt1: 3, value2: 18, valueProzentGesamt2: 18, value3: 79, valueProzentGesamt3: 79, valueGesamt1: 27, valueGesamt2: 6, valueGesamt3: 1, value1: 1, value2: 0, value3: 0, value4: 0, value5: 2, value6: 0, value7: 2, value8: 0, value9: 0, value10: 0, value11: 0, value12: 0, value13: 0, value14: 0, value15: 0, value16: 0, value17: 0, value18: 2, value19: 1, value20: 2, value21: 0, value22: 0, value23: 3, value24: 0, value25: 1, value26: 1, value27: 0, value28: 1, value29: 2, value30: 1, value31: 2, value32: 0, value33: 0, value34: 0 },
    { id: "11", dimension: "Partizipation", value1: 14, valueProzentGesamt1: 14, value2: 24, valueProzentGesamt2: 24, value3: 62, valueProzentGesamt3: 62, valueGesamt1: 21, valueGesamt2: 8, valueGesamt3: 5, value1: 1, value2: 1, value3: 1, value4: 2, value5: 0, value6: 1, value7: 3, value8: 0, value9: 2, value10: 1, value11: 2, value12: 1, value13: 1, value14: 1, value15: 1, value16: 1, value17: 1, value18: 0, value19: 1, value20: 1, value21: 1, value22: 0, value23: 3, value24: 2, value25: 2, value26: 2, value27: 2, value28: 3, value29: 1, value30: 1, value31: 3, value32: 3, value33: 2, value34: 1 },
    { id: "12", dimension: "Accessability", value1: 0, valueProzentGesamt1: 0, value2: 35, valueProzentGesamt2: 35, value3: 65, valueProzentGesamt3: 65, valueGesamt1: 22, valueGesamt2: 12, valueGesamt3: 0, value1: 2, value2: 2, value3: 2, value4: 1, value5: 1, value6: 0, value7: 1, value8: 2, value9: 2, value10: 1, value11: 2, value12: 1, value13: 1, value14: 0, value15: 0, value16: 0, value17: 1, value18: 1, value19: 1, value20: 1, value21: 1, value22: 1, value23: 1, value24: 2, value25: 2, value26: 1, value27: 0, value28: 0, value29: 2, value30: 2, value31: 1, value32: 2, value33: 1, value34: 2 },
    { id: "13", dimension: "OSS & KI Modelle", value1: 36, valueProzentGesamt1: 36, value2: 29, valueProzentGesamt2: 29, value3: 35, valueProzentGesamt3: 35, valueGesamt1: 12, valueGesamt2: 10, valueGesamt3: 12, value1: 2, value2: 2, value3: 3, value4: 3, value5: 0, value6: 2, value7: 2, value8: 1, value9: 1, value10: 1, value11: 3, value12: 3, value13: 3, value14: 3, value15: 2, value16: 1, value17: 0, value18: 1, value19: 0, value20: 3, value21: 1, value22: 3, value23: 0, value24: 1, value25: 2, value26: 2, value27: 3, value28: 2, value29: 2, value30: 2, value31: 3, value32: 3, value33: 0, value34: 3 },
    { id: "14", dimension: "OSS LMS & Plugin", value1: 26, valueProzentGesamt1: 26, value2: 24, valueProzentGesamt2: 24, value3: 50, valueProzentGesamt3: 50, valueGesamt1: 17, valueGesamt2: 8, valueGesamt3: 9, value1: 1, value2: 3, value3: 3, value4: 2, value5: 1, value6: 3, value7: 0, value8: 0, value9: 0, value10: 3, value11: 0, value12: 0, value13: 3, value14: 3, value15: 3, value16: 0, value17: 2, value18: 0, value19: 2, value20: 0, value21: 1, value22: 0, value23: 1, value24: 2, value25: 0, value26: 2, value27: 2, value28: 2, value29: 1, value30: 0, value31: 2, value32: 1, value33: 3, value34: 3 },
    { id: "15", dimension: "API Zugriff", value1: 15, valueProzentGesamt1: 15, value2: 47, valueProzentGesamt2: 47, value3: 38, valueProzentGesamt3: 38, valueGesamt1: 13, valueGesamt2: 16, valueGesamt3: 5, value1: 2, value2: 1, value3: 2, value4: 1, value5: 2, value6: 2, value7: 3, value8: 2, value9: 2, value10: 1, value11: 3, value12: 2, value13: 2, value14: 2, value15: 2, value16: 1, value17: 2, value18: 0, value19: 1, value20: 2, value21: 1, value22: 3, value23: 1, value24: 0, value25: 0, value26: 1, value27: 2, value28: 1, value29: 2, value30: 1, value31: 3, value32: 2, value33: 3, value34: 2 },
    { id: "16", dimension: "OER", value1: 6, valueProzentGesamt1: 6, value2: 15, valueProzentGesamt2: 15, value3: 79, valueProzentGesamt3: 79, valueGesamt1: 27, valueGesamt2: 5, valueGesamt3: 2, value1: 2, value2: 0, value3: 0, value4: 2, value5: 0, value6: 0, value7: 1, value8: 1, value9: 0, value10: 1, value11: 1, value12: 3, value13: 0, value14: 0, value15: 0, value16: 0, value17: 0, value18: 0, value19: 0, value20: 0, value21: 0, value22: 0, value23: 0, value24: 1, value25: 0, value26: 2, value27: 1, value28: 1, value29: 0, value30: 2, value31: 2, value32: 3, value33: 1, value34: 0 },
    { id: "17", dimension: "IT-Sicherheit", value1: 6, valueProzentGesamt1: 6, value2: 62, valueProzentGesamt2: 62, value3: 32, valueProzentGesamt3: 32, valueGesamt1: 11, valueGesamt2: 21, valueGesamt3: 2, value1: 2, value2: 1, value3: 2, value4: 2, value5: 1, value6: 0, value7: 2, value8: 2, value9: 0, value10: 1, value11: 2, value12: 0, value13: 1, value14: 2, value15: 2, value16: 2, value17: 1, value18: 2, value19: 1, value20: 2, value21: 2, value22: 3, value23: 1, value24: 2, value25: 2, value26: 2, value27: 2, value28: 2, value29: 1, value30: 2, value31: 3, value32: 2, value33: 2, value34: 2 },
    { id: "18", dimension: "Datenschutz", value1: 12, valueProzentGesamt1: 12, value2: 82, valueProzentGesamt2: 82, value3: 6, valueProzentGesamt3: 6, valueGesamt1: 2, valueGesamt2: 28, valueGesamt3: 4, value1: 2, value2: 2, value3: 3, value4: 2, value5: 1, value6: 2, value7: 2, value8: 3, value9: 1, value10: 2, value11: 2, value12: 2, value13: 2, value14: 2, value15: 2, value16: 2, value17: 2, value18: 2, value19: 2, value20: 2, value21: 2, value22: 3, value23: 2, value24: 2, value25: 2, value26: 2, value27: 2, value28: 2, value29: 2, value30: 2, value31: 3, value32: 2, value33: 2, value34: 2 },
    { id: "19", dimension: "Datenethik", value1: 14, valueProzentGesamt1: 14, value2: 68, valueProzentGesamt2: 68, value3: 18, valueProzentGesamt3: 18, valueGesamt1: 6, valueGesamt2: 23, valueGesamt3: 5, value1: 2, value2: 2, value3: 2, value4: 3, value5: 0, value6: 2, value7: 2, value8: 2, value9: 1, value10: 1, value11: 3, value12: 2, value13: 2, value14: 2, value15: 2, value16: 2, value17: 2, value18: 2, value19: 1, value20: 2, value21: 2, value22: 3, value23: 1, value24: 2, value25: 2, value26: 2, value27: 2, value28: 1, value29: 2, value30: 2, value31: 3, value32: 3, value33: 2, value34: 2 },
    { id: "20", dimension: "Digitale Identitäten", value1: 14, valueProzentGesamt1: 14, value2: 12, valueProzentGesamt2: 12, value3: 74, valueProzentGesamt3: 74, valueGesamt1: 25, valueGesamt2: 4, valueGesamt3: 5, value1: 0, value2: 3, value3: 0, value4: 1, value5: 0, value6: 0, value7: 1, value8: 1, value9: 0, value10: 0, value11: 0, value12: 0, value13: 1, value14: 0, value15: 0, value16: 0, value17: 0, value18: 3, value19: 0, value20: 0, value21: 0, value22: 3, value23: 0, value24: 2, value25: 0, value26: 1, value27: 2, value28: 2, value29: 0, value30: 3, value31: 3, value32: 1, value33: 2, value34: 1 },

];
var dataUnterDimensionenEinzelStandZeitpunktA = dataUnterDimensionenEinzelStandAntrag; //Datensatz Slider erste position (=links) 

var dataUnterDimensionenEinzelStandZB2021 = [ //Daten Array für Radarboard Einzelvorhaben
    { id: "1", dimension: "Kompetenzstandards", valueProzentGesamt1: 30, valueProzentGesamt2: 41, valueProzentGesamt3: 29, valueGesamt1: 10, valueGesamt2: 14, valueGesamt3: 10, value1: 3, value2: 3, value3: 1, value4: 3, value5: 3, value6: 1, value7: 3, value8: 2, value9: 2, value10: 1, value11: 2, value12: 1, value13: 2, value14: 2, value15: 2, value16: 2, value17: 1, value18: 2, value19: 1, value20: 0, value21: 2, value22: 3, value23: 2, value24: 3, value25: 2, value26: 2, value27: 1, value28: 2, value29: 1, value30: 3, value31: 1, value32: 2, value33: 3, value34: 3 },
    { id: "2", dimension: "Bildungsnachweise", valueProzentGesamt1: 12, valueProzentGesamt2: 29, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 10, valueGesamt3: 4, value1: 1, value2: 3, value3: 1, value4: 1, value5: 1, value6: 2, value7: 2, value8: 2, value9: 2, value10: 0, value11: 0, value12: 0, value13: 2, value14: 1, value15: 1, value16: 0, value17: 0, value18: 3, value19: 1, value20: 1, value21: 2, value22: 3, value23: 0, value24: 2, value25: 0, value26: 0, value27: 0, value28: 2, value29: 0, value30: 3, value31: 2, value32: 0, value33: 2, value34: 0 },
    { id: "3", dimension: "Standards Lerninhalte", valueProzentGesamt1: 18, valueProzentGesamt2: 35, valueProzentGesamt3: 47, valueGesamt1: 16, valueGesamt2: 12, valueGesamt3: 6, value1: 1, value2: 1, value3: 0, value4: 2, value5: 3, value6: 3, value7: 2, value8: 0, value9: 1, value10: 1, value11: 1, value12: 1, value13: 0, value14: 2, value15: 2, value16: 0, value17: 1, value18: 2, value19: 3, value20: 1, value21: 2, value22: 0, value23: 2, value24: 2, value25: 0, value26: 2, value27: 2, value28: 2, value29: 0, value30: 3, value31: 3, value32: 2, value33: 3, value34: 0 },
    { id: "4", dimension: "Wissensrepräsen.", valueProzentGesamt1: 21, valueProzentGesamt2: 26, valueProzentGesamt3: 53, valueGesamt1: 18, valueGesamt2: 9, valueGesamt3: 7, value1: 3, value2: 3, value3: 2, value4: 2, value5: 1, value6: 1, value7: 1, value8: 0, value9: 2, value10: 3, value11: 2, value12: 0, value13: 0, value14: 1, value15: 0, value16: 2, value17: 0, value18: 2, value19: 1, value20: 3, value21: 0, value22: 0, value23: 1, value24: 1, value25: 2, value26: 3, value27: 1, value28: 0, value29: 3, value30: 1, value31: 2, value32: 3, value33: 2, value34: 1 },
    { id: "5", dimension: "Intelligente Suche", valueProzentGesamt1: 26, valueProzentGesamt2: 9, valueProzentGesamt3: 65, valueGesamt1: 22, valueGesamt2: 3, valueGesamt3: 9, value1: 3, value2: 1, value3: 1, value4: 1, value5: 1, value6: 0, value7: 3, value8: 3, value9: 3, value10: 1, value11: 2, value12: 0, value13: 0, value14: 3, value15: 0, value16: 1, value17: 0, value18: 0, value19: 2, value20: 1, value21: 1, value22: 0, value23: 1, value24: 1, value25: 2, value26: 3, value27: 3, value28: 3, value29: 1, value30: 1, value31: 1, value32: 1, value33: 1, value34: 3 },
    { id: "6", dimension: "Learning Analytics", valueProzentGesamt1: 33, valueProzentGesamt2: 29, valueProzentGesamt3: 38, valueGesamt1: 13, valueGesamt2: 10, valueGesamt3: 11, value1: 3, value2: 1, value3: 3, value4: 2, value5: 3, value6: 3, value7: 1, value8: 2, value9: 1, value10: 3, value11: 3, value12: 2, value13: 0, value14: 2, value15: 1, value16: 0, value17: 1, value18: 2, value19: 0, value20: 3, value21: 2, value22: 0, value23: 0, value24: 2, value25: 3, value26: 2, value27: 3, value28: 1, value29: 2, value30: 3, value31: 3, value32: 2, value33: 1, value34: 0 },
    { id: "7", dimension: "Adaptive Lerninh.", valueProzentGesamt1: 53, valueProzentGesamt2: 29, valueProzentGesamt3: 18, valueGesamt1: 6, valueGesamt2: 10, valueGesamt3: 18, value1: 2, value2: 1, value3: 3, value4: 3, value5: 3, value6: 3, value7: 2, value8: 0, value9: 2, value10: 3, value11: 3, value12: 3, value13: 2, value14: 3, value15: 2, value16: 3, value17: 2, value18: 3, value19: 2, value20: 3, value21: 3, value22: 0, value23: 0, value24: 2, value25: 2, value26: 3, value27: 3, value28: 3, value29: 3, value30: 3, value31: 2, value32: 3, value33: 0, value34: 0 },
    { id: "8", dimension: "Lernempfehlungssyst.", valueProzentGesamt1: 61, valueProzentGesamt2: 24, valueProzentGesamt3: 15, valueGesamt1: 5, valueGesamt2: 8, valueGesamt3: 21, value1: 3, value2: 2, value3: 3, value4: 3, value5: 3, value6: 3, value7: 2, value8: 2, value9: 1, value10: 3, value11: 3, value12: 2, value13: 3, value14: 3, value15: 3, value16: 3, value17: 3, value18: 3, value19: 2, value20: 1, value21: 2, value22: 0, value23: 3, value24: 2, value25: 3, value26: 3, value27: 1, value28: 3, value29: 2, value30: 3, value31: 3, value32: 3, value33: 1, value34: 3 },
    { id: "9", dimension: "Kollaboration", valueProzentGesamt1: 9, valueProzentGesamt2: 12, valueProzentGesamt3: 79, valueGesamt1: 27, valueGesamt2: 4, valueGesamt3: 3, value1: 1, value2: 0, value3: 1, value4: 1, value5: 2, value6: 0, value7: 1, value8: 0, value9: 0, value10: 1, value11: 0, value12: 0, value13: 0, value14: 0, value15: 0, value16: 0, value17: 2, value18: 2, value19: 0, value20: 1, value21: 0, value22: 0, value23: 1, value24: 1, value25: 0, value26: 0, value27: 0, value28: 2, value29: 3, value30: 1, value31: 3, value32: 0, value33: 3, value34: 0 },
    { id: "10", dimension: "Peer-Support", valueProzentGesamt1: 3, valueProzentGesamt2: 18, valueProzentGesamt3: 79, valueGesamt1: 27, valueGesamt2: 6, valueGesamt3: 1, value1: 1, value2: 1, value3: 0, value4: 0, value5: 3, value6: 0, value7: 2, value8: 0, value9: 0, value10: 0, value11: 0, value12: 0, value13: 0, value14: 0, value15: 0, value16: 0, value17: 1, value18: 2, value19: 1, value20: 2, value21: 0, value22: 0, value23: 1, value24: 0, value25: 1, value26: 0, value27: 2, value28: 1, value29: 1, value30: 1, value31: 2, value32: 2, value33: 0, value34: 0 },
    { id: "11", dimension: "Partizipation", valueProzentGesamt1: 21, valueProzentGesamt2: 50, valueProzentGesamt3: 29, valueGesamt1: 10, valueGesamt2: 17, valueGesamt3: 7, value1: 2, value2: 2, value3: 2, value4: 2, value5: 1, value6: 2, value7: 3, value8: 0, value9: 2, value10: 1, value11: 2, value12: 1, value13: 1, value14: 2, value15: 1, value16: 1, value17: 2, value18: 1, value19: 2, value20: 1, value21: 2, value22: 3, value23: 3, value24: 2, value25: 2, value26: 2, value27: 2, value28: 3, value29: 1, value30: 2, value31: 3, value32: 3, value33: 3, value34: 2 },
    { id: "12", dimension: "Accessability", valueProzentGesamt1: 6, valueProzentGesamt2: 35, valueProzentGesamt3: 59, valueGesamt1: 20, valueGesamt2: 12, valueGesamt3: 2, value1: 2, value2: 2, value3: 3, value4: 1, value5: 1, value6: 1, value7: 1, value8: 2, value9: 1, value10: 1, value11: 2, value12: 1, value13: 1, value14: 2, value15: 0, value16: 0, value17: 1, value18: 1, value19: 3, value20: 1, value21: 0, value22: 1, value23: 2, value24: 2, value25: 2, value26: 1, value27: 1, value28: 1, value29: 2, value30: 2, value31: 1, value32: 2, value33: 1, value34: 2 },
    { id: "13", dimension: "OSS & KI Modelle", valueProzentGesamt1: 45, valueProzentGesamt2: 29, valueProzentGesamt3: 26, valueGesamt1: 9, valueGesamt2: 10, valueGesamt3: 15, value1: 3, value2: 2, value3: 3, value4: 3, value5: 1, value6: 2, value7: 2, value8: 1, value9: 2, value10: 1, value11: 3, value12: 3, value13: 2, value14: 3, value15: 3, value16: 1, value17: 2, value18: 1, value19: 0, value20: 3, value21: 2, value22: 3, value23: 0, value24: 1, value25: 2, value26: 3, value27: 3, value28: 3, value29: 2, value30: 2, value31: 3, value32: 3, value33: 0, value34: 3 },
    { id: "14", dimension: "OSS LMS & Plugin", valueProzentGesamt1: 35, valueProzentGesamt2: 21, valueProzentGesamt3: 44, valueGesamt1: 15, valueGesamt2: 7, valueGesamt3: 12, value1: 3, value2: 3, value3: 3, value4: 2, value5: 2, value6: 3, value7: 0, value8: 0, value9: 0, value10: 3, value11: 0, value12: 0, value13: 2, value14: 1, value15: 1, value16: 0, value17: 2, value18: 0, value19: 3, value20: 3, value21: 2, value22: 2, value23: 0, value24: 3, value25: 0, value26: 2, value27: 3, value28: 3, value29: 1, value30: 0, value31: 3, value32: 1, value33: 3, value34: 0 },
    { id: "15", dimension: "API Zugriff", valueProzentGesamt1: 17, valueProzentGesamt2: 62, valueProzentGesamt3: 21, valueGesamt1: 7, valueGesamt2: 21, valueGesamt3: 6, value1: 2, value2: 2, value3: 2, value4: 2, value5: 3, value6: 2, value7: 3, value8: 2, value9: 2, value10: 1, value11: 3, value12: 2, value13: 2, value14: 2, value15: 2, value16: 1, value17: 2, value18: 2, value19: 2, value20: 2, value21: 1, value22: 2, value23: 2, value24: 0, value25: 2, value26: 1, value27: 2, value28: 3, value29: 2, value30: 1, value31: 3, value32: 2, value33: 3, value34: 0 },
    { id: "16", dimension: "OER", valueProzentGesamt1: 9, valueProzentGesamt2: 12, valueProzentGesamt3: 79, valueGesamt1: 27, valueGesamt2: 4, valueGesamt3: 3, value1: 3, value2: 0, value3: 0, value4: 1, value5: 1, value6: 1, value7: 1, value8: 0, value9: 1, value10: 2, value11: 1, value12: 3, value13: 0, value14: 0, value15: 0, value16: 0, value17: 1, value18: 2, value19: 2, value20: 1, value21: 0, value22: 0, value23: 0, value24: 2, value25: 0, value26: 1, value27: 1, value28: 1, value29: 0, value30: 1, value31: 1, value32: 3, value33: 1, value34: 0 },
    { id: "17", dimension: "IT-Sicherheit", valueProzentGesamt1: 8, valueProzentGesamt2: 68, valueProzentGesamt3: 24, valueGesamt1: 8, valueGesamt2: 23, valueGesamt3: 3, value1: 2, value2: 1, value3: 2, value4: 2, value5: 2, value6: 2, value7: 2, value8: 2, value9: 1, value10: 1, value11: 2, value12: 1, value13: 1, value14: 1, value15: 2, value16: 2, value17: 2, value18: 2, value19: 3, value20: 2, value21: 2, value22: 3, value23: 2, value24: 2, value25: 2, value26: 2, value27: 1, value28: 3, value29: 1, value30: 2, value31: 2, value32: 2, value33: 2, value34: 2 },
    { id: "18", dimension: "Datenschutz", valueProzentGesamt1: 21, valueProzentGesamt2: 79, valueProzentGesamt3: 0, valueGesamt1: 0, valueGesamt2: 27, valueGesamt3: 7, value1: 2, value2: 2, value3: 2, value4: 2, value5: 2, value6: 2, value7: 2, value8: 3, value9: 2, value10: 2, value11: 2, value12: 2, value13: 2, value14: 2, value15: 2, value16: 2, value17: 2, value18: 2, value19: 3, value20: 2, value21: 3, value22: 3, value23: 3, value24: 2, value25: 2, value26: 2, value27: 2, value28: 3, value29: 2, value30: 2, value31: 3, value32: 2, value33: 2, value34: 2 },
    { id: "19", dimension: "Datenethik", valueProzentGesamt1: 11, valueProzentGesamt2: 74, valueProzentGesamt3: 15, valueGesamt1: 5, valueGesamt2: 25, valueGesamt3: 4, value1: 2, value2: 2, value3: 2, value4: 3, value5: 0, value6: 2, value7: 2, value8: 1, value9: 1, value10: 1, value11: 3, value12: 2, value13: 2, value14: 2, value15: 2, value16: 2, value17: 2, value18: 2, value19: 2, value20: 2, value21: 3, value22: 3, value23: 2, value24: 2, value25: 2, value26: 2, value27: 2, value28: 2, value29: 2, value30: 2, value31: 2, value32: 2, value33: 1, value34: 2 },
    { id: "20", dimension: "Digitale Identitäten", valueProzentGesamt1: 17, valueProzentGesamt2: 12, valueProzentGesamt3: 71, valueGesamt1: 24, valueGesamt2: 4, valueGesamt3: 6, value1: 0, value2: 3, value3: 1, value4: 1, value5: 3, value6: 2, value7: 1, value8: 0, value9: 0, value10: 0, value11: 0, value12: 0, value13: 1, value14: 0, value15: 0, value16: 0, value17: 0, value18: 3, value19: 0, value20: 0, value21: 0, value22: 3, value23: 0, value24: 2, value25: 0, value26: 0, value27: 2, value28: 2, value29: 0, value30: 3, value31: 3, value32: 1, value33: 1, value34: 0 },

];
var dataUnterDimensionenEinzelStandZeitpunktB = dataUnterDimensionenEinzelStandZB2021; //Datensatz Slider 2. position (=mitte) = Stand Dezember 2022

var dataUnterDimensionenEinzelStandTagung2022 = [ //Daten Array für Radarboard Einzelvorhaben
    { id: "1", dimension: "Kompetenzstandards", valueProzentGesamt1: 33, valueProzentGesamt2: 35, valueProzentGesamt3: 32, valueGesamt1: 11, valueGesamt2: 12, valueGesamt3: 11, value1: 3, value2: 3, value3: 1, value4: 3, value5: 3, value6: 1, value7: 3, value8: 2, value9: 1, value10: 1, value11: 2, value12: 1, value13: 2, value14: 2, value15: 3, value16: 2, value17: 2, value18: 2, value19: 1, value20: 1, value21: 2, value22: 3, value23: 2, value24: 3, value25: 2, value26: 2, value27: 1, value28: 1, value29: 1, value30: 3, value31: 1, value32: 2, value33: 3, value34: 3 },
    { id: "2", dimension: "Bildungsnachweise", valueProzentGesamt1: 11, valueProzentGesamt2: 21, valueProzentGesamt3: 68, valueGesamt1: 23, valueGesamt2: 7, valueGesamt3: 4, value1: 1, value2: 3, value3: 1, value4: 1, value5: 1, value6: 1, value7: 2, value8: 2, value9: 1, value10: 0, value11: 0, value12: 0, value13: 2, value14: 1, value15: 0, value16: 0, value17: 0, value18: 3, value19: 1, value20: 1, value21: 2, value22: 3, value23: 0, value24: 2, value25: 0, value26: 0, value27: 0, value28: 1, value29: 0, value30: 3, value31: 2, value32: 0, value33: 2, value34: 0 },
    { id: "3", dimension: "Standards Lerninhalte", valueProzentGesamt1: 18, valueProzentGesamt2: 32, valueProzentGesamt3: 50, valueGesamt1: 17, valueGesamt2: 11, valueGesamt3: 6, value1: 1, value2: 1, value3: 0, value4: 2, value5: 3, value6: 3, value7: 2, value8: 0, value9: 1, value10: 1, value11: 1, value12: 1, value13: 0, value14: 2, value15: 0, value16: 0, value17: 1, value18: 2, value19: 3, value20: 2, value21: 2, value22: 0, value23: 1, value24: 2, value25: 0, value26: 2, value27: 2, value28: 2, value29: 0, value30: 3, value31: 3, value32: 2, value33: 3, value34: 0 },
    { id: "4", dimension: "Wissensrepräsen.", valueProzentGesamt1: 23, valueProzentGesamt2: 24, valueProzentGesamt3: 53, valueGesamt1: 18, valueGesamt2: 8, valueGesamt3: 8, value1: 3, value2: 3, value3: 2, value4: 2, value5: 1, value6: 1, value7: 1, value8: 0, value9: 2, value10: 3, value11: 2, value12: 0, value13: 0, value14: 1, value15: 1, value16: 2, value17: 0, value18: 2, value19: 1, value20: 3, value21: 0, value22: 0, value23: 1, value24: 1, value25: 3, value26: 3, value27: 1, value28: 0, value29: 3, value30: 1, value31: 2, value32: 3, value33: 2, value34: 1 },
    { id: "5", dimension: "Intelligente Suche", valueProzentGesamt1: 26, valueProzentGesamt2: 9, valueProzentGesamt3: 65, valueGesamt1: 22, valueGesamt2: 3, valueGesamt3: 9, value1: 3, value2: 1, value3: 1, value4: 1, value5: 1, value6: 0, value7: 3, value8: 3, value9: 3, value10: 1, value11: 2, value12: 0, value13: 0, value14: 3, value15: 1, value16: 1, value17: 0, value18: 0, value19: 2, value20: 1, value21: 1, value22: 0, value23: 1, value24: 1, value25: 2, value26: 3, value27: 3, value28: 3, value29: 1, value30: 1, value31: 1, value32: 1, value33: 1, value34: 3 },
    { id: "6", dimension: "Learning Analytics", valueProzentGesamt1: 33, valueProzentGesamt2: 29, valueProzentGesamt3: 38, valueGesamt1: 13, valueGesamt2: 10, valueGesamt3: 11, value1: 3, value2: 1, value3: 3, value4: 2, value5: 3, value6: 3, value7: 0, value8: 2, value9: 1, value10: 3, value11: 3, value12: 2, value13: 0, value14: 2, value15: 1, value16: 1, value17: 1, value18: 2, value19: 0, value20: 3, value21: 2, value22: 0, value23: 0, value24: 2, value25: 3, value26: 2, value27: 3, value28: 1, value29: 2, value30: 3, value31: 3, value32: 2, value33: 1, value34: 0 },
    { id: "7", dimension: "Adaptive Lerninh.", valueProzentGesamt1: 50, valueProzentGesamt2: 24, valueProzentGesamt3: 26, valueGesamt1: 9, valueGesamt2: 8, valueGesamt3: 17, value1: 2, value2: 1, value3: 3, value4: 3, value5: 3, value6: 3, value7: 2, value8: 0, value9: 0, value10: 3, value11: 3, value12: 3, value13: 2, value14: 3, value15: 0, value16: 3, value17: 2, value18: 3, value19: 2, value20: 2, value21: 3, value22: 0, value23: 0, value24: 2, value25: 1, value26: 3, value27: 3, value28: 3, value29: 3, value30: 3, value31: 2, value32: 3, value33: 0, value34: 0 },
    { id: "8", dimension: "Lernempfehlungssyst.", valueProzentGesamt1: 65, valueProzentGesamt2: 26, valueProzentGesamt3: 9, valueGesamt1: 3, valueGesamt2: 9, valueGesamt3: 22, value1: 3, value2: 2, value3: 3, value4: 2, value5: 3, value6: 3, value7: 3, value8: 2, value9: 3, value10: 3, value11: 3, value12: 3, value13: 3, value14: 3, value15: 3, value16: 3, value17: 3, value18: 3, value19: 2, value20: 2, value21: 2, value22: 0, value23: 3, value24: 2, value25: 3, value26: 3, value27: 1, value28: 3, value29: 2, value30: 3, value31: 3, value32: 3, value33: 1, value34: 2 },
    { id: "9", dimension: "Kollaboration", valueProzentGesamt1: 8, valueProzentGesamt2: 21, valueProzentGesamt3: 71, valueGesamt1: 24, valueGesamt2: 7, valueGesamt3: 3, value1: 1, value2: 0, value3: 1, value4: 1, value5: 2, value6: 0, value7: 1, value8: 0, value9: 0, value10: 1, value11: 0, value12: 2, value13: 0, value14: 0, value15: 0, value16: 0, value17: 2, value18: 2, value19: 1, value20: 2, value21: 0, value22: 0, value23: 2, value24: 1, value25: 0, value26: 0, value27: 0, value28: 2, value29: 3, value30: 1, value31: 3, value32: 0, value33: 3, value34: 0 },
    { id: "10", dimension: "Peer-Support", valueProzentGesamt1: 3, valueProzentGesamt2: 21, valueProzentGesamt3: 76, valueGesamt1: 26, valueGesamt2: 7, valueGesamt3: 1, value1: 1, value2: 1, value3: 0, value4: 0, value5: 3, value6: 0, value7: 2, value8: 0, value9: 0, value10: 0, value11: 0, value12: 0, value13: 0, value14: 0, value15: 0, value16: 0, value17: 0, value18: 2, value19: 1, value20: 2, value21: 0, value22: 0, value23: 1, value24: 0, value25: 1, value26: 0, value27: 2, value28: 1, value29: 2, value30: 1, value31: 2, value32: 2, value33: 0, value34: 0 },
    { id: "11", dimension: "Partizipation", valueProzentGesamt1: 29, valueProzentGesamt2: 50, valueProzentGesamt3: 21, valueGesamt1: 7, valueGesamt2: 17, valueGesamt3: 10, value1: 2, value2: 2, value3: 2, value4: 2, value5: 1, value6: 2, value7: 3, value8: 0, value9: 2, value10: 1, value11: 2, value12: 1, value13: 1, value14: 2, value15: 1, value16: 1, value17: 2, value18: 2, value19: 2, value20: 3, value21: 2, value22: 3, value23: 3, value24: 2, value25: 3, value26: 2, value27: 2, value28: 3, value29: 3, value30: 2, value31: 3, value32: 3, value33: 3, value34: 2 },
    { id: "12", dimension: "Accessability", valueProzentGesamt1: 6, valueProzentGesamt2: 38, valueProzentGesamt3: 56, valueGesamt1: 19, valueGesamt2: 13, valueGesamt3: 2, value1: 2, value2: 2, value3: 3, value4: 1, value5: 1, value6: 2, value7: 1, value8: 2, value9: 1, value10: 1, value11: 2, value12: 1, value13: 1, value14: 2, value15: 1, value16: 0, value17: 1, value18: 1, value19: 3, value20: 1, value21: 0, value22: 1, value23: 2, value24: 2, value25: 2, value26: 1, value27: 1, value28: 1, value29: 2, value30: 2, value31: 1, value32: 2, value33: 1, value34: 2 },
    { id: "13", dimension: "OSS & KI Modelle", valueProzentGesamt1: 44, valueProzentGesamt2: 32, valueProzentGesamt3: 24, valueGesamt1: 8, valueGesamt2: 11, valueGesamt3: 15, value1: 3, value2: 2, value3: 3, value4: 3, value5: 1, value6: 2, value7: 2, value8: 1, value9: 2, value10: 1, value11: 3, value12: 3, value13: 2, value14: 3, value15: 3, value16: 1, value17: 2, value18: 2, value19: 0, value20: 3, value21: 2, value22: 3, value23: 0, value24: 1, value25: 2, value26: 3, value27: 3, value28: 3, value29: 2, value30: 2, value31: 3, value32: 3, value33: 0, value34: 3 },
    { id: "14", dimension: "OSS LMS & Plugin", valueProzentGesamt1: 41, valueProzentGesamt2: 15, valueProzentGesamt3: 44, valueGesamt1: 15, valueGesamt2: 5, valueGesamt3: 14, value1: 3, value2: 3, value3: 3, value4: 3, value5: 2, value6: 3, value7: 0, value8: 0, value9: 0, value10: 3, value11: 0, value12: 0, value13: 2, value14: 1, value15: 0, value16: 0, value17: 3, value18: 0, value19: 3, value20: 3, value21: 2, value22: 2, value23: 0, value24: 3, value25: 0, value26: 2, value27: 3, value28: 3, value29: 1, value30: 0, value31: 3, value32: 1, value33: 3, value34: 0 },
    { id: "15", dimension: "API Zugriff", valueProzentGesamt1: 26, valueProzentGesamt2: 56, valueProzentGesamt3: 18, valueGesamt1: 6, valueGesamt2: 19, valueGesamt3: 9, value1: 2, value2: 2, value3: 2, value4: 3, value5: 3, value6: 2, value7: 3, value8: 2, value9: 2, value10: 1, value11: 3, value12: 2, value13: 2, value14: 2, value15: 2, value16: 1, value17: 2, value18: 2, value19: 2, value20: 2, value21: 1, value22: 2, value23: 2, value24: 0, value25: 3, value26: 3, value27: 2, value28: 3, value29: 2, value30: 1, value31: 3, value32: 2, value33: 3, value34: 0 },
    { id: "16", dimension: "OER", valueProzentGesamt1: 9, valueProzentGesamt2: 12, valueProzentGesamt3: 79, valueGesamt1: 27, valueGesamt2: 4, valueGesamt3: 3, value1: 3, value2: 0, value3: 0, value4: 1, value5: 1, value6: 1, value7: 1, value8: 0, value9: 1, value10: 2, value11: 1, value12: 3, value13: 0, value14: 0, value15: 0, value16: 0, value17: 1, value18: 2, value19: 2, value20: 1, value21: 0, value22: 0, value23: 0, value24: 2, value25: 0, value26: 1, value27: 1, value28: 1, value29: 0, value30: 1, value31: 1, value32: 3, value33: 1, value34: 0 },
    { id: "17", dimension: "IT-Sicherheit", valueProzentGesamt1: 8, valueProzentGesamt2: 68, valueProzentGesamt3: 24, valueGesamt1: 8, valueGesamt2: 23, valueGesamt3: 3, value1: 2, value2: 1, value3: 2, value4: 2, value5: 2, value6: 2, value7: 2, value8: 2, value9: 1, value10: 1, value11: 2, value12: 1, value13: 1, value14: 1, value15: 2, value16: 2, value17: 2, value18: 2, value19: 3, value20: 2, value21: 2, value22: 3, value23: 2, value24: 2, value25: 2, value26: 2, value27: 1, value28: 3, value29: 1, value30: 2, value31: 2, value32: 2, value33: 2, value34: 2 },
    { id: "18", dimension: "Datenschutz", valueProzentGesamt1: 21, valueProzentGesamt2: 79, valueProzentGesamt3: 0, valueGesamt1: 0, valueGesamt2: 27, valueGesamt3: 7, value1: 2, value2: 2, value3: 2, value4: 2, value5: 2, value6: 2, value7: 2, value8: 3, value9: 2, value10: 2, value11: 2, value12: 2, value13: 2, value14: 2, value15: 2, value16: 2, value17: 2, value18: 2, value19: 3, value20: 2, value21: 3, value22: 3, value23: 3, value24: 2, value25: 2, value26: 2, value27: 2, value28: 3, value29: 2, value30: 2, value31: 3, value32: 2, value33: 2, value34: 2 },
    { id: "19", dimension: "Datenethik", valueProzentGesamt1: 14, valueProzentGesamt2: 71, valueProzentGesamt3: 15, valueGesamt1: 5, valueGesamt2: 24, valueGesamt3: 5, value1: 2, value2: 2, value3: 2, value4: 3, value5: 2, value6: 2, value7: 2, value8: 1, value9: 1, value10: 1, value11: 3, value12: 2, value13: 2, value14: 2, value15: 2, value16: 2, value17: 1, value18: 2, value19: 2, value20: 2, value21: 3, value22: 3, value23: 2, value24: 2, value25: 3, value26: 2, value27: 2, value28: 2, value29: 2, value30: 2, value31: 2, value32: 2, value33: 1, value34: 2 },
    { id: "20", dimension: "Digitale Identitäten", valueProzentGesamt1: 17, valueProzentGesamt2: 12, valueProzentGesamt3: 71, valueGesamt1: 24, valueGesamt2: 4, valueGesamt3: 6, value1: 0, value2: 3, value3: 1, value4: 1, value5: 3, value6: 1, value7: 2, value8: 0, value9: 0, value10: 0, value11: 0, value12: 0, value13: 1, value14: 0, value15: 0, value16: 0, value17: 0, value18: 3, value19: 0, value20: 0, value21: 0, value22: 3, value23: 0, value24: 2, value25: 0, value26: 0, value27: 2, value28: 2, value29: 0, value30: 3, value31: 3, value32: 1, value33: 1, value34: 0 },

];
var dataUnterDimensionenEinzelStandZeitpunktC = dataUnterDimensionenEinzelStandTagung2022; //Datensatz Slider 3. position (=rechts) = August 2023


//var dataUnterDimensionenEinzel = dataUnterDimensionenEinzelStandZB2021; ///aktuellen Datensatz auf den letzten Stand setzen, dieser ist dann der inital angezeigte Datensatz
var dataUnterDimensionenEinzel = dataUnterDimensionenEinzelStandAntrag; /// slider steht zu Beginn auf StandAntrag
var dataUnterDimensionen = dataUnterDimensionenEinzel; //values nur noch in Einzelarray enthalten

var dataUnterDimensionenEinzelTexte = [ ///Daten Array für Texte jedes Einzel-Radarboards
    { id: "1", name: "ADAPT", entwicklungsfeld: "3", thema: "Adaptives Weiterbildungsunter-\nstützungssystem im Berufsfeld Pflege", branche: "Pflege", schwerpunkte: "KI-basiertes adaptives Weiterbildungs-unterstützungssystem, bild- und videobasiert, Gamification, Qualifikations-Dashboard, Lernreminder, Reduktion subjektiver Lernwiderstände, personalisierte Lernpfade und Userprofile", technologischeZiel: "Lern-Dashboard erfasst Kompetenz und Lernanforderung, NLP-basiertes Matching mit Arbeitsmarktdaten, Web, YouTube und OER, Django/React, Oauth, NLTK", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "2", name: "APOLLO", entwicklungsfeld: "2, 3", thema: ": KI-basierte, plattformübergreifende Companion-App für lebenslange Lern-Optimierung", branche: "übergreifend", schwerpunkte: "KI-basierte Personalisierung und Empfehlungssystem", technologischeZiel: "Cross-Plattform-App, NLP zur Analyse von Qualifikationsunterlagen, Einsatz von Klassifizierungssystemen zur Einschätzung von Kompetenzen, graph-basierter Ansatz zur Verknüpfung von Bestandsdaten, Wissensgraph und Link Prediction zur Generierung von Empfehlungen, MLOps Infrastruktur, kontinuierliche Messung der Qualität der Vorhersagen", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "3", name: "ComP-ASS", entwicklungsfeld: "3", thema: "Computergestütztes Lernen und Lehren im Handwerk mit interaktiven Assistenzsystemen", branche: "Handwerk", schwerpunkte: "digitalgestütztes Weiterbildungsangebot zur Vermittlung von CNC-Kompetenzen für das Handwerk, Simulationen von Materialänderungen, interaktive VR/AR-basierte „CNC-Maschinen-Welt“, Gamification-Elemente, interaktives didaktisches Assistenzsystem", technologischeZiel: "AR/VR Maschinenwelt, Plugin für ILIAS, regelbasierter didaktischer Assistent für Autoren von Lehrinhalten im Handwerk", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "4", name: "DigiPlat4Train", entwicklungsfeld: "1,2,3", thema: "Automatisierte, datenbasierte Rückschlüsse aus der praktischen Arbeit an Fertigungsmaschinen", branche: "Kunststofffertigung", schwerpunkte: "virtueller Produktionsassistent, KI, Kunststofftechnologie, DSGVO, KI mit Fehlercodes, Training direkt an Produktionsmaschine, Abstimmung mit Betriebsrat und Mitarbeitenden", technologischeZiel: "VIPRA erfasst Trainings- und Arbeitsdaten an Maschine, KI bietet Kurse und Micro-Lerneinheiten von Weiterbildungsplattform anhand erkannter Lerndefizite an", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "5", name: "EduPLEx_API", entwicklungsfeld: "2 (untergeordnet 3) ", thema: "Erweiterung einer bestehenden Learning Experience Plattform (LXP) um eine Schnittstelle zu einem KI-basierten Empfehlungssystem bzw. einem Lern-Nachweis-System um eine Mandaten-Fähigkeit der Plattform für die Anwendbarkeit für KMU", branche: "übergreifend, Fokus liegt KMU", schwerpunkte: "Empfehlungsmaschine, Marktplatz, adaptives Lernkonzept (selbstgesteuertes Lernen mit homogenen Inhalten, Trainer-gestütztes Lernen mit heterogenen Lernmaterialien und kollaboratives Arbeiten), Suchen / Sprachmodell (semantische Netze) zur Identifikation von Inhalten", technologischeZiel: "Interoperabilität, Integration von Zusatzdiensten", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "6", name: "ELe-com", entwicklungsfeld: "2,3", thema: "Empowering Learning – Ermöglichung adaptiven Lernens in der beruflichen Weiterbildung am Beispiel des E-Commerce ", branche: "Handel", schwerpunkte: "Individuelles Lernen über die Berücksichtigung von Lernpräferenzen durch den Einsatz  von adaptiven Lernwegen, adaptiven Lernformaten in Form von Micro Learning Einheiten und Empfehlungen durch KI Assistenzsysteme anhand des Themas Customer Journey im E-Commerce.", technologischeZiel: "KI-unterstütztes Assistenzsystem aus zwei Tools: Lernnavigator (LENA) und Entscheidungsmodul (EMIL), Weiterentwicklung myFlexNet.de (ILIAS-Plattform)", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "7", name: "ExpanderWB3", entwicklungsfeld: "2,3", thema: "Vernetzung der „Weiterbildungsdatenbank Suchportal in Berlin und Brandenburg“ mit weiteren Plattformen und KI-gestützte Empfehlung von Inhalten für die berufliche Weiterbildung", branche: "übergreifend, Fokus auf Branchen der industriellen Verarbeitung", schwerpunkte: "Nutzendenzentrierte Individualisierung von beruflichen Lernangeboten mit Bezug zu unternehmens- und arbeitsmarktpolitischen Erfolgsmerkmalen", technologischeZiel: "Entwicklung von interoperablen Standards und Schnittstellen; Begriffs-Klassifikationen und Ontologien; Integration eines Gamification Ansatzes; Implementierung einer semantischen Suche; User-Profile und E-Portfolios auf Kompetenz­basis; Learning Analytics, Lernempfehlungen und Lernpfade", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "8", name: "HUBGrade", entwicklungsfeld: "1,2,3", thema: "Entwicklung eines bundesweiten Weiterbildungs-portals des Handwerks", branche: "Handwerk", schwerpunkte: "Vernetzung bestehender Weiterbildungsplattformen, Weiterbildungsangebote, Verwaltungssysteme und Lernmanagementsysteme der handwerklichen Bildungsanbietenden mit intelligenter Suchfunktion und Single-Sign-On", technologischeZiel: "API-Entwicklung für Weiterbildungsplattformen (ODAV AG, UNIPLUS und B & E), SSO, Learning Record Store mit E-Portfolio, Digitale Zertifikate (EUROPASS und ProNet-Handwerk), intelligente Suche mit Chatbot (Framework Chatterbox)", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "9", name: "IWWB-PLUS", entwicklungsfeld: "2", thema: "Personalisierte Lernumgebung und Suche ", branche: "übergeordnet", schwerpunkte: "Implementierung von dialogischen Technologien, Light Assessments und Interoperabilität mit externen Informationsanbietern", technologischeZiel: "Schaffung von personalisierten Suchfunktionen mit einem Chatbot, Empfehlungsmaschine, Natural Language Processing", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "10", name: "KAINE", entwicklungsfeld: "3", thema: "Steigerung der Effizienz, Effektivität und Nachhaltigkeit des Lernens auf Weiterbildungsplattformen durch smarte, individuelle Lernmaterialbereitstellung und dialogorientiertem Tutoringsystem", branche: "produzierendes Gewerbe", schwerpunkte: "Lernassistenzsystem mit individuellen Learning Journeys, individuelle Lernverlaufsbegleitung durch ein dialogorientiertes Tutorsystem, KI-basierte adaptive Erstellung von individuellen Lernpfaden, Voice- und Chatbot basiertes Lerntutoringsystem", technologischeZiel: "KI-basierte Lernpfade, Voice- und Chatbot, LMS Plugin (moodle), Ontologien", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "11", name: "KAMAELEON", entwicklungsfeld: "3", thema: "Kontextbasierte und adaptive Maßnahmen für effektive Lernunterstützung in der Online-Weiterbildung", branche: "übergreifend (Weiterbildungsangebote im Bereich Digitalisierung, Daten- und Projektmanagement)", schwerpunkte: "KI-basierte Personalisierungskonzepte,  Integration innerer und äußerer Lernfaktoren, die den Lernerfolg beeinflussen", technologischeZiel: "ML-basierte Personalisierung und Adaption von Lerninhalten, Integration in bestehende AWS Cloudplattform, Serverless Architektur, GraphQL, NoSQL DB, Angular, Snowflake Datwarehouse", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "12", name: "KI4CoLearnET", entwicklungsfeld: "1,2,3", thema: "KI für kompetenzbasiertes Lernen im Cluster Energietechnik", branche: "Energietechnik", schwerpunkte: "Serious Games mit Schwierigkeitsanpassung und adaptiven Lernpfaden", technologischeZiel: "Baukastensystem für Serious Games, KI zur Schwierigkeitsanpassung", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "13", name: "KIM", entwicklungsfeld: "2", thema: "Künstliche Intelligenz als Mentoring-Lösung für lebenslanges Lernen", branche: "übergreifend", schwerpunkte: "verzahntes bzw. rückgekoppeltes System, welches auf Basis der erkannten Trends und vorhandener Kompetenzen eine Prognose geeigneter Lerneinheiten liefert", technologischeZiel: "CV Extraktion, adaptive Lernpfade, Trenderkennung", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "14", name: "KIPerWeb", entwicklungsfeld: "2,3", thema: "KI-gestützte Personalisierung in der berufsbezogenen Weiterbildung", branche: "übergreifend", schwerpunkte: "Verbesserung unterschiedlicher Plattformen, Synergien durch gemeinsame Arbeit", technologischeZiel: "Adaptive Lernpfade und personalisierte Kursempfehlungen (Empfehlungssysteme)", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "15", name: "KIRA", entwicklungsfeld: "2,3", thema: "KI-gestütztes Matching individueller und arbeitsmarktbezogener Anforderungen für die berufliche Weiterbildung", branche: "übergreifend, Fokus auf IT-Qualifikationen in transformationsintensiven Branchen", schwerpunkte: "Nutzendenzentrierte Individualisierung von beruflichen Lernangeboten mit Bezug zu unternehmens- und arbeitsmarktpolitischen Erfolgsmerkmalen", technologischeZiel: "Modellierung von Lernformen, -bedarfen und -erfolgen; Empfehlungen von Lerninhalten für Lernende; Entwicklung von KI-Service-Modulen; Reporting über Optimierungsmöglichkeiten für Plattformbetreiber:innen (am Beispiel WBS TRAINING AG)", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "16", name: "KIRA_Pro", entwicklungsfeld: "3", thema: "KI-basierter Rollennavigator und automatisierte Lernpfadermittlung zur beruflichen Weiterbildung im produzierenden Gewerbe", branche: "Produzierendes Gewerbe", schwerpunkte: "Identifikation von am besten geeigneten Mitarbeiter:innen für Weiterbildungen in Trendthemen der digitalen Transformation unter Berücksichtigung der Unternehmensziele.", technologischeZiel: "Kompetenzerfassung, Pfadsuche auf Kompetenzgraph", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "17", name: "KIWI", entwicklungsfeld: "2 (untergeordnet 3)", thema: "Anwendung bzw. Bereitstellung von AR/VR-basierten Lerninhalten auf Smartphones im Bereich „Cobots“ und die KI-gestützte Identifikation von Lernpräferenzen bzw. passgenaue Bereitstellung von Lerninhalten", branche: "Maschinenbau (kollaborative Robotik)", schwerpunkte: "KI-basiertes adaptives Weiterbildungsunterstützungssystem, VR/AR, mobile und VR-Equipment, personalisierte Lernpfade und Userprofile", technologischeZiel: "strenge Trennung zwischen Content (Unreal Engine) und Kubernetes Container (Flutter für native Apps, Python / TensorFlow, mlflow für KI / Microservice-spezifische DBs (MongoDB, Postgresql, Minio) / Keycloak für ID / Spring Boot für Backend)", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "18", name: "KUPPEL", entwicklungsfeld: "3", thema: "KI-unterstützte plattformübergreifende Professionalisierung erwachsenen-pädagogischer Lehrkräfte", branche: "übergreifend, Fokus auf die digitalen Kompetenzen Lehrender", schwerpunkte: "Zusammenführung von Angeboten zweier existierender Plattformen, Ergänzung um Adaptivität und Zertifikate", technologischeZiel: "Lernbereiche vhs-DTrain (vhs cloud) und EULE (wb-Web) verbinden, cloudbasiertes Multiagentensystem, Lernvorschläge, Kollaboration, Fälschungs- und identitätssichere Zertifikate", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "19", name: "LIMo", entwicklungsfeld: "2", thema: "Unterstützung der Durchführung und Management betrieblicher Weiterbildung, um vermitteltes Wissen bedarfsgerecht zur Verfügung zu stellen und neue Lernangebote zu schaffen", branche: "Industrie", schwerpunkte: "Sicher & mobil, informell & partizipativ, individuell & unterstützt", technologischeZiel: "Empfehlungssystem", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "20", name: "LiSiL", entwicklungsfeld: "3", thema: "Smarte Lernwelten im Sozialwesen – innovative digitale Lernräume für die hybride Vermittlung sensibler Weiterbildungsthemen", branche: "Sozialwesen", schwerpunkte: "Neue Konzepte für die Vermittlung von sensiblen Themen, Erkennung dysfunktionaler emotionaler Belastung im digitalen Raum", technologischeZiel: "Sentiment Analyse aus Nutzerverhalten zur Bestimmung dysfunktionaler emotionaler Belastung", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "21", name: "MINDED_RUHR", entwicklungsfeld: "1,3", thema: "Aufbau eines offenen Systems von digitalen, KI-gestützten Weiterbildungsangeboten verschiedener Plattformen und Formaten der DHAR und Vernetzung mit Moodle.", branche: "Gesundheitswesen, Pflege am Beispiel der Demenz", schwerpunkte: "Anbieter- und plattformübergreifende Bereitstellung von Bildungsinhalten, Schnittstellenentwicklung", technologischeZiel: "Verknüpfung von Moodle-Plattformen mit Tutoolio zum Pooling von Content, KI-unterstützte, bedarfsorientierte Bereitstellung von Lerninhalten", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "22", name: "MyEduLife", entwicklungsfeld: "2", thema: "Die Blockchain als Werkzeug zur dezentralen Speicherung individueller Weiterbildungsbiographien, Entwicklung und Erprobung von Werkzeugen zur Bearbeitung und Präsentation von Qualifikationsportfolios", branche: "übergreifend", schwerpunkte: "Standardisierung von Bildungserwerben, Blockchain für Bildungserwerbsdokumentation", technologischeZiel: "Blockchain mit Second Layer", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "23", name: "NetOEV", entwicklungsfeld: "1,2", thema: "Plattformvernetzung für personalisierte Weiterbildung und kooperativen Wissensaustausch in der Mobilitätsbranche", branche: "Mobilitätsbranche", schwerpunkte: "kooperativer Wissensaustausch, formelle und informelle Weiterbildung, Sichtbarkeit von Expertise, nutzerzentrierte Lernerfahrung", technologischeZiel: "Vernetzung vieler Plattformen durch Schnittstellen mit übergreifender Auswertung, um bessere Lerninhalte durch Recommender System zu empfehlen und Expertise branchenweit sichtbar zu machen", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "24", name: "OncaPflege", entwicklungsfeld: "2,3", thema: "Entwicklung und Erprobung einer digitalen Plattform für den spezifischen Zielbereich der beruflichen Pflege mit adaptiven Lernpfaden", branche: "Pflege", schwerpunkte: "Qualitative Verbesserung bestehender Weiterbildungsplattformen durch digitale Lehr- und Lernformen sowie die Untersuchung von Weiterbildungsbeteiligung und -verhalten", technologischeZiel: "KI-unterstützte Lehr- und Lernangebote (Recommender- und Unterstützungssysteme; Kompetenzerfassung und -verarbeitung; Verbindung von Learning Nuggets und Metadaten; Motivations-Bot; KI-unterstützte Simultanübersetzung; Badges und Zertifikate mittels Zertifikats-Blockchain; Berücksichtigung von Datenethik-Standards", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "25", name: "PolyEx", entwicklungsfeld: "1,2,3", thema: "Polymer-Excellence - Weiterbildungsplattform für die kunststoffverarbeitende Industrie", branche: "kunststoffverarbeitende Industrie", schwerpunkte: "effiziente Filter- und Sortierungsfunktionen, Personal Learning Environment, adaptives Lernen durch KI-basiertes Empfehlungssystem mit einem Chatbot als Weiterbildungsassistenten, Kompetenzmatrix, Integration von Lernformaten", technologischeZiel: "Lehrinhalte entweder nativ über Online-Formular, Upload (JSON-Datei), Webscrapers oder API, persönliche Lernumgebung (Personal Learning Environment – PLE), KI-basiertes Empfehlungssystem und Weiterbildungsassistent mit Natural Language Processing (NLP), Kompetenzmatrix", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "26", name: "SEARCH", entwicklungsfeld: "2,3", thema: "Entwicklung eines KI-gestützten Assistenzsystems zum adaptiven Lernen und Ausbau der Lernplattform MLS für die bedarfsgerechte Weiterbildung", branche: "übergreifend, Fokus auf das produzierende Gewerbe", schwerpunkte: ": Pädagogisch-didaktisch und technologische Aufbereitung von Lerninhalten sowie Aufzeigen von individuellen und flexibel anpassbaren Lerneinheiten und Lernpfade für Lernende", technologischeZiel: "Anreicherung und Strukturierung von Informationen; Komposition von Lernpfaden; Integration eines KI-gestützten Assistenzsystems; Einbinden von Methoden zur Spracherkennung sowie zur text- und sprachorientierten Videoanalyse; Entwicklung einer Suchfunktion zur intelligenten Suche", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "27", name: "SG4BB", entwicklungsfeld: "1,2,3", thema: "Serious Games für die berufliche Bildung", branche: "übergreifend", schwerpunkte: "KI-gestützte spielerische Lehr- und Lernangebote, „Steam“ für Serious Games, Metadaten-orientierte Suchmaschine, neuer Metadatenstandard ", technologischeZiel: "Verknüpfung von Learning Record Store, LMS, Marktplatz, Suchmaschine und Serious Games, Anbindung von Drittanbietern", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "28", name: "SMALO", entwicklungsfeld: "1,2,3", thema: "Smartes Lernen in der Logistik", branche: "Logistik", schwerpunkte: "KI für erhöhte Beteiligung, bessere Kohärenz und Personalisierung, Vernetzung, Bedarfsorientierung, Zertifizierung, Lern-Ökosystem, Datensicherheit (DSGVO, BSI)", technologischeZiel: "KI für Beteiligung, Kohärenz und Personalisierung, datensicherer Weiterbildungsraum, Überarbeitung der Plattformarchitektur ", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "29", name: "StuBu", entwicklungsfeld: "3", thema: "StudyBuddy: Ein virtueller Companion für die berufliche Weiterbildung", branche: "übergreifend", schwerpunkte: "KI-basierter Funktionsbaukasten für einen virtuellen Companion in der beruflichen Weiterbildung. Erkennung von Lernpräferenzen und Eingehen auf individuelles Lernverhalten.", technologischeZiel: "ML-basierter virtueller Companion, Anbindung an Bot Engine, automatische ML-basierte Lern-Persönlichkeitsanalyse, Nutzung von NPL, NLU und NLG. Node.js, Mongo DB, Rest API, RASA", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "30", name: "TRIPLEADAPT", entwicklungsfeld: "1,2,3", thema: "Adaptive, interoperationale Weiterbildungsplattformen durch einen digitalen Drilling", branche: "übergreifend", schwerpunkte: "Adaptiver Drilling, Adaptive Lernpfade, plattformübergreifende Lernpfade, Adaptive Assistenz in arbeitsplatzähnlicher Umgebung, Common Learning Middleware (CLM), Micro-Zertifikate", technologischeZiel: "Erstellung von KI-Diensten auf Basis Low Code Mendix Plattform für Lernen in der digitalen Produktion, Nutzung von Simulationen und Prozessdaten des digitalen Zwillings", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "31", name: "VerDatAs", entwicklungsfeld: "1,2,3", thema: "Vernetzung und datengestützte Assistenz für die berufliche Bildung", branche: "übergreifend", schwerpunkte: "Plattformvernetzung zu digitalem Marktplatz, Unterstützung von Lehrenden und Lernenden, innovativer Weiterbildungsraum für Informatiker, Ingenieure und qualifizierte Quereinsteiger, pädagogisch-psychologisches Ordnungssystem, Qualifikations-Matching", technologischeZiel: "LMS ILIAS zur Plattformvernetzung, Aufbau eines Learning Record Store, nutzerzentrierte KI für variantenreiche Szenarien beruflicher und betrieblicher Bildung, Entwicklung eines tutoriellen Assistenzsystems", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "32", name: "Wbsmart", entwicklungsfeld: "3", thema: "Bildungswissenschaftliche Grundlegung eines smarten KI-basierten digitalen Weiterbildungsraums für die Altenhilfe mittels personalisierter Empfehlungs-systeme", branche: "Pflege", schwerpunkte: "KI-basiertes, personalisiertes Empfehlungssystem, intelligente Aufbereitung und Empfehlung von Lernangeboten auf adaptiven Lernpfaden, basierend auf individueller Präferenz, Lernfortschritt, Kenntnisstand und auf einem Wissens-modell als Wissensgraph, intelligentes tutorielles Assistenzsystem, Einbeziehung vorhandener OER Ressourcen", technologischeZiel: "semantischer Wissensgraph, White-Box KI, Recommender System", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "33", name: "Weiterbildung 4.OWL", entwicklungsfeld: "2,3", thema: "Entwicklung eines didaktischen und technisch-wirtschaftlichen Instrumentariums zur nutzer- und qualitätszentrierten Verbesserung von intermediären Marktplatz- und Lernplattformen", branche: "übergreifend, Fokus produzierendes Gewerbe", schwerpunkte: "Nutzerorientierte Gestaltung des digitalen Lernens und der Kompetenzentwicklung; Technisch-wirtschaftliche Gestaltung des plattformbasierten Weiterbildungsraums", technologischeZiel: "Tools zur Erfassung strukturierter Bildungsangebotsanfragen und zur Erstellung qualitätsorientierter Lernangebote, Anbindung der Tools an LMS und Spezifikation von Schnittstellen, Kollaborative Bearbeitung von Anfragen & Designs, Anbindung der Tools an übergreifende Matching-Plattform, Rahmenwerk für einzuhaltende Sicherh.-Stand.", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },
    { id: "34", name: "WISYatKI", entwicklungsfeld: "1,2", thema: "WISY@KI-Dein persönlicher Weiterbildungsscout", branche: "übergreifend", schwerpunkte: "Verbesserung der Suche von regionalen Weiterbildungsangeboten / Kursen insbesondere hinsichtlich der Treffgenauigkeit zu den eigenen Kompetenzen / Weiterbildungszielen. Entwicklung und Integration einer kompetenzorientierten Suchfunktion in die WISY-Kursportale in Schleswig-Holstein und Hessen zur Optimierung der Kursergebnisse.", technologischeZiel: "Entwicklung der Kursportale Schleswig-Holstein und Hessen mittels Einsatz von kompetenzorientierten Empfehlungssystemen zur Verbesserung der persönlichen Suchergebnisse.", weiterbildungsplattformen: "ILIAS", zielgruppe: "Niedrigqualifizierte, Quereinsteiger*innen und Umschüler*innen sowie Fachkräfte mit Migrationshintergrund", besonderheiten: "Das Projekt adressiert gesellschaftlich dringliche Innovationsbedarfe in der Pflegebranche und trägt durch die digital gestützte Kompetenzdiagnostik zur Fachkräfteentwicklung in der Pflegebranche bei. Durch die Einbindung der freien Software ILIAS werden – in Bezug auf Interoperabilität/Vernetzung – ein offener Zugang gewährleistet und Transfer ermöglicht." },

];

//#endregion ///-----C END Set Data----------------------------------------------------------------------------------------------

